export interface VerseResult {
  detected_category: string;
  message: string;
  verse_reference: string;
  verse_text: string;
}

type V = { r: string; t: string; c: string[] };

const VERSES: V[] = [
  {r:"Salmos 46:1",t:"Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.",c:["Confianza","Dios","Fortaleza","Esperanza viva"]},
  {r:"Isaías 41:10",t:"No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia.",c:["Confianza","Dios","Fortaleza","Amor incondicional"]},
  {r:"Salmos 27:1",t:"Dios es mi luz y mi salvación: ¿de quién temeré? Dios es la fortaleza de mi vida: ¿de quién me receleré?",c:["Confianza","Dios","Luz","Salvación","Fortaleza"]},
  {r:"Jeremías 17:7",t:"Bendito el varón que confía en Dios, y cuya confianza es Dios.",c:["Confianza","Dios","Bendición"]},
  {r:"Proverbios 3:5",t:"Confía en Dios de todo tu corazón, y no te apoyes en tu propia prudencia.",c:["Confianza","Sabiduría","Dios"]},
  {r:"Salmos 62:8",t:"Esperad en él en todo tiempo, oh pueblos: derramad delante de él vuestro corazón: Dios es nuestro refugio.",c:["Confianza","Dios","Oración"]},
  {r:"Salmos 9:10",t:"En ti confiarán los que conocen tu nombre; por cuanto no desamparaste á los que te buscaron.",c:["Confianza","Dios","Amor incondicional"]},
  {r:"Nahum 1:7",t:"Dios es bueno, fortaleza en el día de la angustia; y conoce á los que en él esperan.",c:["Confianza","Dios","Fortaleza","Esperanza"]},
  {r:"Salmos 56:3",t:"El día que temo, yo en ti confío.",c:["Confianza","Fe"]},
  {r:"Isaías 26:4",t:"Confiad en Dios para siempre; porque en Dios el Señor está la fortaleza de los siglos.",c:["Confianza","Dios","Fortaleza","Eternidad"]},
  {r:"Hebreos 13:5",t:"No te desampararé, ni te dejaré.",c:["Dios","Amor incondicional","Confianza"]},
  {r:"Mateo 28:20",t:"He aquí, yo estoy con vosotros todos los días, hasta el fin del mundo.",c:["Dios","Amor incondicional","Eternidad"]},
  {r:"Salmos 27:10",t:"Aunque mi padre y mi madre me dejaran, con todo, Dios me recogerá.",c:["Dios","Amor incondicional"]},
  {r:"Isaías 43:2",t:"Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán.",c:["Dios","Confianza","Fortaleza","Esperanza viva"]},
  {r:"Isaías 49:15",t:"¿Olvidará la mujer su niño que mamanta? Aunque éstas olvidaran, yo nunca me olvidaré de ti.",c:["Dios","Amor incondicional"]},
  {r:"Salmos 68:5",t:"Padre de los huérfanos y defensor de las viudas es Dios en su santa morada.",c:["Dios","Amor incondicional","Justicia"]},
  {r:"Deuteronomio 31:8",t:"Dios es el que va delante de ti; él será contigo, no te dejará, ni te desamparará.",c:["Dios","Confianza","Amor incondicional"]},
  {r:"Salmos 139:7",t:"¿A dónde me iré de tu espíritu? ¿Y á dónde huiré de tu presencia?",c:["Dios","Amor incondicional"]},
  {r:"Romanos 8:38",t:"Estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni potestades, ni lo presente, ni lo por venir, ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios.",c:["Amor incondicional","Eternidad","Dios"]},
  {r:"Juan 3:16",t:"Porque de tal manera amó Dios al mundo, que ha dado á su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.",c:["Amor incondicional","Salvación","Dios","Vida","Eternidad"]},
  {r:"1 Juan 4:8",t:"El que no ama, no conoce á Dios; porque Dios es amor.",c:["Amor","Dios"]},
  {r:"1 Juan 4:16",t:"Dios es amor; y el que está en amor, está en Dios, y Dios en él.",c:["Amor","Dios"]},
  {r:"1 Juan 4:19",t:"Nosotros le amamos á él, porque él nos amó primero.",c:["Amor","Amor incondicional","Dios"]},
  {r:"1 Corintios 13:4",t:"La caridad es sufrida, es benigna; la caridad no tiene envidia, la caridad no es jactanciosa, no se ensoberbece.",c:["Amor","Amor incondicional"]},
  {r:"1 Corintios 13:13",t:"Y ahora permanecen la fe, la esperanza, el amor, estos tres; pero el mayor de ellos es el amor.",c:["Amor","Fe","Esperanza"]},
  {r:"Juan 15:13",t:"Nadie tiene mayor amor que éste, que ponga alguno su vida por sus amigos.",c:["Amor incondicional","Sacrificio","Dios"]},
  {r:"1 Pedro 4:8",t:"Y ante todo, tened entre vosotros fervorosa caridad; porque la caridad cubrirá multitud de pecados.",c:["Amor","Perdón"]},
  {r:"Romanos 5:8",t:"Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros.",c:["Amor incondicional","Sacrificio","Salvación","Gracia divina"]},
  {r:"Efesios 3:18",t:"Para que seáis plenamente capaces de comprender cuál sea la anchura, la longitud, la profundidad y la altura del amor de Cristo.",c:["Amor incondicional","Eternidad","Dios"]},
  {r:"2 Timoteo 1:7",t:"Porque no nos ha dado Dios el espíritu de cobardía, sino de poder, de amor y de templanza.",c:["Amor","Poder","Fortaleza","Dios"]},
  {r:"Hebreos 11:1",t:"Es pues la fe la certeza de lo que se espera, la demostración de lo que no se ve.",c:["Fe","Esperanza"]},
  {r:"Marcos 9:23",t:"Si puedes creer, al que cree todo le es posible.",c:["Fe","Fe activa","Poder"]},
  {r:"Hebreos 11:6",t:"Pero sin fe es imposible agradar á Dios; porque es necesario que el que se allega á Dios, crea que le hay.",c:["Fe","Dios"]},
  {r:"Romanos 10:17",t:"Así que la fe es por el oír, y el oír, por la palabra de Dios.",c:["Fe","Verdad","Dios"]},
  {r:"Mateo 17:20",t:"Si tuviéreis fe como un grano de mostaza, diréis á este monte: Pásate de aquí allá, y se pasará; y nada os será imposible.",c:["Fe activa","Poder","Fe"]},
  {r:"Santiago 2:17",t:"Así también la fe, si no tuviere obras, es muerta en sí misma.",c:["Fe activa","Obediencia","Fe"]},
  {r:"Marcos 11:22",t:"Tened fe en Dios.",c:["Fe","Dios"]},
  {r:"Romanos 1:17",t:"El justo por la fe vivirá.",c:["Fe","Vida","Justicia"]},
  {r:"Gálatas 6:9",t:"Y no nos cansemos de hacer bien; porque á su tiempo segaremos, si no desmayáremos.",c:["Fe activa","Esperanza","Obediencia"]},
  {r:"Santiago 1:12",t:"Bienaventurado el varón que soporta la prueba; porque cuando fuere probado, recibirá la corona de vida.",c:["Fe activa","Esperanza viva","Bendición"]},
  {r:"Apocalipsis 2:10",t:"Sé fiel hasta la muerte, y yo te daré la corona de la vida.",c:["Fe activa","Eternidad","Vida"]},
  {r:"Hebreos 12:1",t:"Corramos con paciencia la carrera que tenemos por delante.",c:["Fe activa","Fortaleza"]},
  {r:"Jeremías 29:11",t:"Porque yo sé los pensamientos que tengo acerca de vosotros, dice Dios, pensamientos de paz y no de mal, para daros el fin que esperáis.",c:["Esperanza","Esperanza viva","Confianza","Dios","Paz"]},
  {r:"Romanos 15:13",t:"Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por la virtud del Espíritu Santo.",c:["Esperanza","Paz","Poder","Alabanza"]},
  {r:"Isaías 40:31",t:"Pero los que esperan á Dios tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.",c:["Esperanza viva","Fortaleza","Fe activa","Esperanza"]},
  {r:"Romanos 5:5",t:"Y la esperanza no avergüenza; porque el amor de Dios está derramado en nuestros corazones por el Espíritu Santo que nos fue dado.",c:["Esperanza","Amor incondicional","Gracia divina"]},
  {r:"Salmos 31:24",t:"Esforzaos, y aliente vuestro corazón, todos los que esperáis en Dios.",c:["Esperanza","Fe activa","Confianza"]},
  {r:"Salmos 42:11",t:"¿Por qué te abates, oh alma mía? Espera en Dios; porque aún le tengo que alabar.",c:["Esperanza","Alabanza","Confianza"]},
  {r:"Lamentaciones 3:25",t:"Bueno es Dios á los que en él esperan, al alma que le busca.",c:["Esperanza","Dios","Misericordia"]},
  {r:"Romanos 8:24",t:"Porque en esperanza fuimos salvos; pero la esperanza que se ve, no es esperanza.",c:["Esperanza viva","Salvación"]},
  {r:"Salmos 30:5",t:"Por la tarde durará el lloro, y á la mañana vendrá la alegría.",c:["Esperanza","Misericordia","Alabanza","Esperanza viva"]},
  {r:"1 Pedro 1:3",t:"Bendito el Dios y Padre de nuestro Señor Jesucristo, que según su grande misericordia nos regeneró para una esperanza viva, por la resurrección de Jesucristo.",c:["Esperanza viva","Misericordia","Bendición","Resurrección"]},
  {r:"1 Juan 1:9",t:"Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad.",c:["Perdón","Perdón eterno","Gracia divina","Arrepentimiento"]},
  {r:"Salmos 103:12",t:"Cuanto está lejos el oriente del occidente, hizo alejar de nosotros nuestras rebeliones.",c:["Perdón eterno","Misericordia"]},
  {r:"Isaías 43:25",t:"Yo, yo soy el que borro tus rebeliones por amor de mí mismo; y no me acordaré de tus pecados.",c:["Perdón eterno","Gracia divina","Amor incondicional"]},
  {r:"Efesios 4:32",t:"Sed pues benignos unos con otros, misericordiosos, perdonándoos unos á otros, como también Dios os perdonó á vosotros en Cristo.",c:["Perdón","Amor","Gracia divina","Misericordia"]},
  {r:"Miqueas 7:18",t:"¿Qué Dios como tú, que perdona la maldad, y olvida el pecado del remanente de su heredad?",c:["Perdón eterno","Dios","Misericordia"]},
  {r:"Salmos 32:5",t:"Mi pecado te declaré, y no encubrí mi iniquidad. Dije: Confesaré mis rebeliones á Dios; y tú perdonaste la maldad de mi pecado.",c:["Perdón","Arrepentimiento","Pecado"]},
  {r:"Isaías 44:22",t:"Yo desvanecí como nube tus transgresiones, y como niebla tus pecados: vuélvete á mí, porque yo te redimí.",c:["Perdón","Redención","Gracia divina"]},
  {r:"Hechos 3:19",t:"Arrepentíos y convertíos, para que sean borrados vuestros pecados.",c:["Arrepentimiento","Perdón","Salvación","Pecado"]},
  {r:"Mateo 6:14",t:"Porque si perdonáis á los hombres sus ofensas, os perdonará también á vosotros vuestro Padre celestial.",c:["Perdón","Amor","Obediencia"]},
  {r:"Lucas 15:20",t:"Y levantándose, vino á su padre. Y cuando aún estaba lejos, le vió su padre, y fué movido á misericordia, y corrió, y se echó sobre su cuello, y le besó.",c:["Perdón eterno","Amor incondicional","Misericordia","Gracia divina"]},
  {r:"Salmos 86:5",t:"Porque tú, oh Señor, eres bueno y perdonador, y grande en misericordia á todos los que te invocan.",c:["Perdón","Misericordia","Dios","Oración"]},
  {r:"Mateo 18:22",t:"No te digo hasta siete, sino hasta setenta veces siete.",c:["Perdón","Amor incondicional"]},
  {r:"Romanos 10:9",t:"Que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.",c:["Salvación","Fe","Resurrección"]},
  {r:"Hechos 4:12",t:"Y en ningún otro hay salvación; porque no hay otro nombre debajo del cielo dado á los hombres, en que podamos ser salvos.",c:["Salvación","Verdad"]},
  {r:"Juan 14:6",t:"Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.",c:["Salvación","Verdad","Vida","Luz"]},
  {r:"Efesios 2:8",t:"Porque por gracia sois salvos por la fe; y esto no de vosotros, pues es don de Dios.",c:["Salvación","Gracia divina","Fe"]},
  {r:"2 Timoteo 1:9",t:"El cual nos salvó y llamó con llamamiento santo, no conforme á nuestras obras, sino según el propósito suyo y la gracia que nos fue dada en Cristo Jesús.",c:["Salvación","Gracia divina","Santificación"]},
  {r:"Isaías 12:2",t:"He aquí Dios es salvación mía; me aseguraré y no temeré.",c:["Salvación","Confianza","Dios"]},
  {r:"Tito 3:5",t:"Nos salvó, no por obras de justicia que nosotros hubiésemos hecho, sino por su misericordia.",c:["Salvación","Misericordia","Gracia divina"]},
  {r:"2 Corintios 12:9",t:"Bástate mi gracia; porque mi potencia en la flaqueza se perfecciona.",c:["Gracia divina","Fortaleza","Poder"]},
  {r:"Juan 1:16",t:"Porque de su plenitud tomamos todos, y gracia sobre gracia.",c:["Gracia divina","Dios","Amor incondicional"]},
  {r:"Hebreos 4:16",t:"Lleguémonos pues confiadamente al trono de la gracia, para que alcancemos misericordia, y hallemos gracia para el oportuno socorro.",c:["Gracia divina","Misericordia","Oración"]},
  {r:"Romanos 5:20",t:"Mas donde el pecado abundó, sobreabundó la gracia.",c:["Gracia divina","Pecado","Perdón"]},
  {r:"1 Pedro 5:10",t:"Mas el Dios de toda gracia, que nos llamó á su gloria eterna en Cristo Jesús, después que hayáis padecido un poco de tiempo, él mismo os perfeccione, confirme, corrobore y establezca.",c:["Gracia divina","Gloria","Eternidad","Fortaleza"]},
  {r:"Efesios 1:7",t:"En quien tenemos redención por su sangre, el perdón de los pecados según las riquezas de su gracia.",c:["Gracia divina","Redención","Perdón eterno"]},
  {r:"Juan 14:27",t:"La paz os dejo, mi paz os doy; no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo.",c:["Paz","Paz interior","Confianza"]},
  {r:"Filipenses 4:7",t:"Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús.",c:["Paz","Paz interior","Dios"]},
  {r:"Isaías 26:3",t:"Tú guardarás en completa paz á aquel cuyo pensamiento en ti persevera; porque en ti ha confiado.",c:["Paz","Paz interior","Confianza"]},
  {r:"Filipenses 4:6",t:"Por nada estéis afanosos; sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con hacimiento de gracias.",c:["Paz interior","Oración","Confianza"]},
  {r:"Mateo 11:28",t:"Venid á mí todos los que estáis trabajados y cargados, y yo os haré descansar.",c:["Paz interior","Amor incondicional","Dios"]},
  {r:"Salmos 4:8",t:"En paz me acostaré asimismo, y dormiré; porque solo tú, Dios, me haces vivir confiado.",c:["Paz","Paz interior","Confianza"]},
  {r:"Romanos 8:6",t:"Pero el ocuparse del Espíritu es vida y paz.",c:["Paz","Vida","Santificación"]},
  {r:"Colosenses 3:15",t:"Y la paz de Dios gobierne en vuestros corazones, á la que asimismo fuisteis llamados en un cuerpo; y sed agradecidos.",c:["Paz","Paz interior","Alabanza"]},
  {r:"Juan 16:33",t:"Estas cosas os he hablado para que en mí tengáis paz. En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo.",c:["Paz","Confianza","Fortaleza","Esperanza viva"]},
  {r:"Mateo 5:9",t:"Bienaventurados los pacificadores; porque ellos serán llamados hijos de Dios.",c:["Paz","Bendición","Dios"]},
  {r:"Mateo 5:6",t:"Bienaventurados los que tienen hambre y sed de justicia; porque ellos serán hartos.",c:["Justicia","Bendición"]},
  {r:"Proverbios 21:3",t:"El hacer justicia y juicio es más acepto á Dios que el sacrificio.",c:["Justicia","Obediencia","Dios"]},
  {r:"Amós 5:24",t:"Corra, empero, el juicio como las aguas, y la justicia como poderoso arroyo.",c:["Justicia"]},
  {r:"Romanos 3:22",t:"La justicia de Dios por la fe de Jesucristo, para todos los que creen en él.",c:["Justicia","Fe","Salvación"]},
  {r:"Isaías 1:17",t:"Aprended á hacer bien; buscad el juicio, restituid al agraviado, haced justicia al huérfano, amparad á la viuda.",c:["Justicia","Obediencia","Amor"]},
  {r:"Salmos 37:28",t:"Porque Dios ama la rectitud, y no desampara á sus santos; para siempre serán guardados.",c:["Justicia","Dios","Confianza","Eternidad"]},
  {r:"Miqueas 6:8",t:"Qué pide Dios de ti: solamente hacer juicio, y amar misericordia, y humillarte ante tu Dios.",c:["Justicia","Humildad","Misericordia","Obediencia"]},
  {r:"Santiago 1:5",t:"Y si alguno de vosotros tiene falta de sabiduría, demándela á Dios, el cual da á todos abundantemente y sin reproche; y le será dada.",c:["Sabiduría","Oración","Dios"]},
  {r:"Proverbios 2:6",t:"Porque Dios da la sabiduría; y de su boca viene el conocimiento y la inteligencia.",c:["Sabiduría","Dios","Verdad"]},
  {r:"Salmos 32:8",t:"Te haré entender, y te enseñaré el camino en que debes andar; sobre ti fijaré mis ojos.",c:["Sabiduría","Dios","Confianza"]},
  {r:"Proverbios 16:3",t:"Encomienda á Dios tus obras, y tus pensamientos serán afirmados.",c:["Confianza","Sabiduría","Dios"]},
  {r:"Isaías 30:21",t:"Entonces tus oídos oirán á tus espaldas palabra que diga: Este es el camino, andad por él.",c:["Sabiduría","Dios","Verdad"]},
  {r:"Salmos 119:105",t:"Lámpara es á mis pies tu palabra, y lumbrera á mi camino.",c:["Luz","Verdad","Sabiduría"]},
  {r:"Proverbios 3:6",t:"Reconócelo en todos tus caminos, y él enderezará tus veredas.",c:["Sabiduría","Confianza","Dios"]},
  {r:"Proverbios 9:10",t:"El temor de Dios es el principio de la sabiduría; y el conocimiento del Santísimo es la inteligencia.",c:["Sabiduría","Dios"]},
  {r:"Eclesiastés 12:13",t:"Teme á Dios, y guarda sus mandamientos; porque esto es el todo del hombre.",c:["Sabiduría","Obediencia","Dios"]},
  {r:"Mateo 7:7",t:"Pedid, y se os dará; buscad, y hallaréis; llamad, y os será abierto.",c:["Oración","Fe","Confianza"]},
  {r:"1 Juan 5:14",t:"Esta es la confianza que tenemos en él: que si demandamos alguna cosa conforme á su voluntad, él nos oye.",c:["Oración","Confianza","Fe"]},
  {r:"1 Tesalonicenses 5:17",t:"Orad sin cesar.",c:["Oración","Fe activa"]},
  {r:"Jeremías 33:3",t:"Clama á mí, y yo te responderé, y te enseñaré cosas grandes y dificultosas que tú no conoces.",c:["Oración","Dios","Sabiduría"]},
  {r:"Romanos 12:12",t:"Gozosos en la esperanza; pacientes en la tribulación; constantes en la oración.",c:["Oración","Esperanza","Fe activa"]},
  {r:"Mateo 6:6",t:"Mas tú, cuando ores, entra en tu aposento, y cerrada tu puerta, ora á tu Padre que está en secreto; y tu Padre que ve en secreto te recompensará.",c:["Oración","Dios"]},
  {r:"Efesios 6:18",t:"Orando en todo tiempo con toda oración y súplica en el Espíritu.",c:["Oración","Fe activa"]},
  {r:"Salmos 100:4",t:"Entrad por sus puertas con alabanza, por sus atrios con alabanza; alabadle, bendecid su nombre.",c:["Alabanza","Dios","Gloria"]},
  {r:"Efesios 5:20",t:"Dando siempre gracias por todo al Dios y Padre, en el nombre de nuestro Señor Jesucristo.",c:["Alabanza","Gracia divina"]},
  {r:"Salmos 9:1",t:"Te alabaré, oh Dios, con todo mi corazón; contaré todas tus maravillas.",c:["Alabanza","Dios"]},
  {r:"Nehemías 8:10",t:"El gozo de Dios es vuestra fortaleza.",c:["Alabanza","Fortaleza","Dios"]},
  {r:"Filipenses 4:4",t:"Alegraos en el Señor siempre: otra vez digo que os alegréis.",c:["Alabanza","Paz interior"]},
  {r:"Salmos 150:6",t:"Todo lo que respira alabe á Dios.",c:["Alabanza","Dios","Vida"]},
  {r:"Salmos 34:1",t:"Bendeciré á Dios en todo tiempo; su alabanza será siempre en mi boca.",c:["Alabanza","Dios","Bendición"]},
  {r:"Habacuc 3:18",t:"Con todo, yo me alegraré en Dios, y me gozaré en el Dios de mi salvación.",c:["Alabanza","Salvación","Fe activa"]},
  {r:"1 Tesalonicenses 5:18",t:"Dad gracias en todo: porque esta es la voluntad de Dios para con vosotros en Cristo Jesús.",c:["Alabanza","Obediencia","Dios"]},
  {r:"Salmos 103:8",t:"Misericordioso y clemente es Dios; lento para la ira y grande en misericordia.",c:["Misericordia","Dios","Amor"]},
  {r:"Salmos 107:1",t:"Alabad á Dios, porque él es bueno; porque para siempre es su misericordia.",c:["Misericordia","Alabanza","Eternidad"]},
  {r:"Efesios 2:4",t:"Pero Dios, que es rico en misericordia, por su grande amor con que nos amó.",c:["Misericordia","Amor incondicional","Dios","Gracia divina"]},
  {r:"Lucas 6:36",t:"Sed pues misericordiosos, como también vuestro Padre es misericordioso.",c:["Misericordia","Amor","Dios"]},
  {r:"Salmos 103:13",t:"Como el padre se compadece de los hijos, se compadece Dios de los que le temen.",c:["Misericordia","Amor incondicional","Dios"]},
  {r:"Lamentaciones 3:22",t:"Las misericordias de Dios no se han acabado; porque no faltaron sus bondades. Nuevas son cada mañana; grande es tu fidelidad.",c:["Misericordia","Amor incondicional","Gracia divina","Esperanza"]},
  {r:"Filipenses 4:13",t:"Todo lo puedo en Cristo que me fortalece.",c:["Fortaleza","Fe activa","Poder"]},
  {r:"Isaías 40:29",t:"Él da esfuerzo al cansado, y multiplica las fuerzas al que no tiene ningunas.",c:["Fortaleza","Dios"]},
  {r:"Salmos 28:7",t:"Dios es mi fortaleza y mi escudo; en él confió mi corazón, y fui ayudado.",c:["Fortaleza","Confianza","Dios"]},
  {r:"Efesios 6:10",t:"Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza.",c:["Fortaleza","Poder","Fe activa"]},
  {r:"Josué 1:9",t:"¿No te mandé que te esforzases y fueses valiente? No temas, ni desmayes; porque Dios tu Dios será contigo en dondequiera que fueres.",c:["Fortaleza","Confianza","Dios"]},
  {r:"Salmos 18:32",t:"Dios es el que me ciñe de fortaleza, y quien despeja mi camino.",c:["Fortaleza","Dios","Sabiduría"]},
  {r:"Proverbios 11:2",t:"Donde hay soberbia, allí hay también deshonra; mas con los humildes está la sabiduría.",c:["Humildad","Sabiduría"]},
  {r:"Mateo 23:12",t:"El que se ensalzare será humillado, y el que se humillare será ensalzado.",c:["Humildad"]},
  {r:"1 Pedro 5:6",t:"Humillaos pues bajo la poderosa mano de Dios, para que él os ensalce cuando fuere tiempo.",c:["Humildad","Confianza","Dios"]},
  {r:"Filipenses 2:3",t:"No hagáis nada por contienda ó por vanagloria; sino con humildad, estimando cada uno á los otros como superiores á él mismo.",c:["Humildad","Amor"]},
  {r:"Santiago 4:10",t:"Humillaos delante del Señor, y él os ensalzará.",c:["Humildad","Confianza","Dios"]},
  {r:"Isaías 57:15",t:"Habitaré con el quebrantado y humilde de espíritu, para hacer vivir el espíritu de los humildes.",c:["Humildad","Dios","Vida"]},
  {r:"Juan 14:15",t:"Si me amáis, guardad mis mandamientos.",c:["Obediencia","Amor","Fe activa"]},
  {r:"Josué 24:15",t:"Yo y mi casa serviremos á Dios.",c:["Obediencia","Fe activa"]},
  {r:"Hechos 5:29",t:"Es necesario obedecer á Dios antes que á los hombres.",c:["Obediencia","Fe activa","Dios"]},
  {r:"1 Samuel 15:22",t:"Ciertamente el obedecer es mejor que los sacrificios, y el prestar atención que la grosura de los carneros.",c:["Obediencia","Sacrificio","Dios"]},
  {r:"Salmos 119:9",t:"¿Con qué limpiará el joven su camino? Con guardar tu palabra.",c:["Obediencia","Santificación","Verdad"]},
  {r:"1 Pedro 1:15",t:"Como aquel que os ha llamado es santo, sed también vosotros santos en toda vuestra manera de vivir.",c:["Santificación","Dios","Obediencia"]},
  {r:"Hebreos 12:14",t:"Seguid la paz con todos, y la santidad, sin la cual nadie verá al Señor.",c:["Santificación","Paz"]},
  {r:"Romanos 6:22",t:"Librados del pecado, y hechos siervos para Dios, tenéis por vuestro fruto la santificación.",c:["Santificación","Salvación","Vida"]},
  {r:"1 Tesalonicenses 4:7",t:"No nos ha llamado Dios á impureza, sino á santificación.",c:["Santificación","Dios"]},
  {r:"Salmos 51:10",t:"Crea en mí, oh Dios, un corazón limpio; y renueva un espíritu recto dentro de mí.",c:["Santificación","Arrepentimiento","Oración"]},
  {r:"Efesios 4:24",t:"Vestíos del nuevo hombre, creado según Dios en la justicia y santidad de la verdad.",c:["Santificación","Verdad","Justicia"]},
  {r:"2 Corintios 5:17",t:"De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.",c:["Santificación","Salvación","Esperanza viva","Vida"]},
  {r:"Gálatas 3:13",t:"Cristo nos redimió de la maldición de la ley, hecho por nosotros maldición.",c:["Redención","Sacrificio","Salvación"]},
  {r:"1 Pedro 1:18",t:"Fuisteis rescatados, no con cosas corruptibles, sino con la sangre preciosa de Cristo.",c:["Redención","Sacrificio","Gracia divina"]},
  {r:"Romanos 3:24",t:"Siendo justificados gratuitamente por su gracia, por la redención que es en Cristo Jesús.",c:["Redención","Gracia divina","Salvación","Justicia"]},
  {r:"Salmos 130:7",t:"En Dios hay misericordia, y abundante redención con él.",c:["Redención","Misericordia","Dios"]},
  {r:"Isaías 43:1",t:"No temas, porque yo te redimí; te puse nombre, mío eres tú.",c:["Redención","Amor incondicional","Dios","Confianza"]},
  {r:"Colosenses 1:14",t:"En quien tenemos redención por su sangre, el perdón de los pecados.",c:["Redención","Perdón eterno","Sacrificio"]},
  {r:"Romanos 8:18",t:"Pues tengo por cierto que las aflicciones del tiempo presente no son comparables con la gloria venidera que en nosotros ha de manifestarse.",c:["Gloria","Esperanza viva","Eternidad"]},
  {r:"1 Corintios 10:31",t:"Si pues coméis ó bebéis, ó hacéis otra cosa, hacedlo todo á la gloria de Dios.",c:["Gloria","Obediencia","Dios"]},
  {r:"2 Corintios 4:17",t:"Porque esta leve tribulación momentánea produce en nosotros un cada vez más excelente y eterno peso de gloria.",c:["Gloria","Eternidad","Esperanza viva"]},
  {r:"Salmos 19:1",t:"Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos.",c:["Gloria","Dios","Alabanza"]},
  {r:"Apocalipsis 4:11",t:"Digno eres, Señor, de recibir la gloria y la honra y el poder.",c:["Gloria","Alabanza","Dios","Poder"]},
  {r:"Juan 17:22",t:"La gloria que me diste, yo les he dado, para que sean una cosa, como también nosotros somos una cosa.",c:["Gloria","Dios","Amor"]},
  {r:"Mateo 19:26",t:"Para Dios todo es posible.",c:["Poder","Dios","Fe activa","Milagros"]},
  {r:"Lucas 1:37",t:"Porque nada es imposible para Dios.",c:["Poder","Dios","Fe activa","Milagros"]},
  {r:"Jeremías 32:27",t:"He aquí que yo soy Dios de toda carne; ¿habrá alguna cosa que sea difícil para mí?",c:["Poder","Dios","Milagros"]},
  {r:"Efesios 3:20",t:"Y á aquel que es poderoso para hacer todas las cosas mucho más abundantemente de lo que pedimos ó entendemos, según el poder que actúa en nosotros.",c:["Poder","Dios","Oración"]},
  {r:"Romanos 1:16",t:"Porque no me avergüenzo del evangelio de Cristo; porque es potencia de Dios para salvación á todo aquel que creyere.",c:["Poder","Salvación","Fe"]},
  {r:"Salmos 62:11",t:"Una cosa dijo Dios; dos cosas he oído: Que el poder es de Dios.",c:["Poder","Dios"]},
  {r:"Isaías 40:28",t:"¿No has sabido, no has oído que el Dios eterno es Dios, el cual creó los términos de la tierra? El no se fatiga, ni se cansa.",c:["Poder","Dios","Eternidad"]},
  {r:"Juan 10:10",t:"Yo he venido para que tengan vida, y para que la tengan en abundancia.",c:["Vida","Dios","Esperanza viva"]},
  {r:"Juan 11:25",t:"Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá.",c:["Vida","Resurrección","Fe","Eternidad"]},
  {r:"Romanos 6:23",t:"Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro.",c:["Vida","Pecado","Salvación","Eternidad"]},
  {r:"Gálatas 2:20",t:"Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí.",c:["Vida","Fe activa","Santificación"]},
  {r:"Proverbios 4:23",t:"Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.",c:["Vida","Sabiduría"]},
  {r:"Juan 17:3",t:"Y esta es la vida eterna: que te conozcan á ti, el solo Dios verdadero, y á Jesucristo.",c:["Vida","Eternidad","Dios","Verdad"]},
  {r:"Deuteronomio 30:19",t:"Escoge la vida, para que vivas tú y tu simiente.",c:["Vida","Obediencia","Sabiduría"]},
  {r:"Juan 8:12",t:"Yo soy la luz del mundo; el que me sigue, no andará en tinieblas.",c:["Luz","Dios","Vida","Verdad"]},
  {r:"Mateo 5:14",t:"Vosotros sois la luz del mundo.",c:["Luz","Obediencia","Fe activa"]},
  {r:"1 Juan 1:7",t:"Si andamos en luz, como él está en luz, tenemos comunión entre nosotros.",c:["Luz","Santificación","Amor"]},
  {r:"Efesios 5:8",t:"Porque en otro tiempo erais tinieblas, mas ahora sois luz en el Señor; andad como hijos de luz.",c:["Luz","Santificación","Obediencia"]},
  {r:"Proverbios 4:18",t:"Mas la vereda de los justos es como la luz de la aurora, que va en aumento hasta que el día es perfecto.",c:["Luz","Justicia","Vida"]},
  {r:"Isaías 60:1",t:"Levántate, resplandece; porque ha venido tu luz, y la gloria de Dios ha nacido sobre ti.",c:["Luz","Gloria","Dios","Esperanza viva"]},
  {r:"Juan 8:32",t:"Y conoceréis la verdad, y la verdad os hará libres.",c:["Verdad","Salvación","Vida"]},
  {r:"Juan 17:17",t:"Santifícalos en tu verdad: tu palabra es verdad.",c:["Verdad","Santificación","Dios"]},
  {r:"Salmos 119:160",t:"El principio de tu palabra es verdad; y eterno es todo juicio de tu justicia.",c:["Verdad","Eternidad","Justicia"]},
  {r:"Salmos 86:11",t:"Enséñame, oh Dios, tu camino; caminaré en tu verdad.",c:["Verdad","Sabiduría","Oración","Dios"]},
  {r:"Efesios 4:15",t:"Mas siguiendo la verdad en amor, crezcamos en todo en aquel que es la cabeza, á saber, Cristo.",c:["Verdad","Amor","Vida"]},
  {r:"3 Juan 1:4",t:"No tengo yo mayor gozo que éste, el oír que mis hijos andan en verdad.",c:["Verdad","Fe activa"]},
  {r:"Eclesiastés 12:14",t:"Porque Dios traerá toda obra á juicio, juntamente con toda cosa encubierta, sea buena ó sea mala.",c:["Juicio","Dios","Verdad"]},
  {r:"Romanos 14:12",t:"Así que cada uno de nosotros dará á Dios cuenta de sí.",c:["Juicio","Obediencia"]},
  {r:"Salmos 9:8",t:"Y él juzgará al mundo con justicia; juzgará á los pueblos con rectitud.",c:["Juicio","Justicia","Dios"]},
  {r:"Hebreos 9:27",t:"Está establecido á los hombres que mueran una sola vez, y después el juicio.",c:["Juicio","Eternidad"]},
  {r:"Apocalipsis 20:12",t:"Y vi los muertos, grandes y pequeños, que estaban delante de Dios; y los libros fueron abiertos.",c:["Juicio","Eternidad","Dios"]},
  {r:"Romanos 3:23",t:"Por cuanto todos pecaron, y están destituídos de la gloria de Dios.",c:["Pecado","Gloria","Salvación"]},
  {r:"1 Juan 1:8",t:"Si dijéremos que no tenemos pecado, nos engañamos á nosotros mismos, y la verdad no está en nosotros.",c:["Pecado","Verdad"]},
  {r:"Isaías 59:2",t:"Pero vuestras iniquidades han hecho división entre vosotros y vuestro Dios, y vuestros pecados han hecho que esconda de vosotros su faz.",c:["Pecado","Dios"]},
  {r:"Proverbios 28:13",t:"El que encubre sus pecados no prosperará; mas el que los confiesa y se aparta de ellos alcanzará misericordia.",c:["Pecado","Arrepentimiento","Misericordia","Perdón"]},
  {r:"Lucas 13:3",t:"Si no os arrepentís, todos pereceréis igualmente.",c:["Arrepentimiento","Salvación"]},
  {r:"2 Pedro 3:9",t:"No queriendo que ninguno perezca, sino que todos procedan al arrepentimiento.",c:["Arrepentimiento","Amor incondicional","Dios"]},
  {r:"Ezequiel 18:30",t:"Convertíos, y apartaos de todas vuestras transgresiones.",c:["Arrepentimiento","Obediencia"]},
  {r:"Isaías 55:7",t:"Deje el impío su camino, y el hombre inicuo sus pensamientos, y vuélvase á Dios, el cual tendrá de él misericordia.",c:["Arrepentimiento","Misericordia","Perdón","Dios"]},
  {r:"Salmos 51:17",t:"Los sacrificios de Dios son el espíritu quebrantado: al corazón contrito y humillado no despreciarás tú, oh Dios.",c:["Arrepentimiento","Humildad","Dios","Oración"]},
  {r:"Números 6:24",t:"Dios te bendiga, y te guarde; Dios haga resplandecer su rostro sobre ti.",c:["Bendición","Dios"]},
  {r:"Efesios 1:3",t:"Bendito el Dios y Padre de nuestro Señor Jesucristo, que nos bendijo con toda bendición espiritual en los lugares celestiales en Cristo.",c:["Bendición","Dios","Gloria"]},
  {r:"Salmos 128:1",t:"Bienaventurado todo aquel que teme á Dios, que anda en sus caminos.",c:["Bendición","Obediencia","Dios"]},
  {r:"Lucas 6:38",t:"Dad, y se os dará; medida buena, apretada, remecida y rebosando darán en vuestro seno.",c:["Bendición","Amor","Obediencia"]},
  {r:"Gálatas 3:9",t:"De manera que los de la fe son bendecidos con el creyente Abraham.",c:["Bendición","Fe"]},
  {r:"Salmos 34:10",t:"Los leoncillos padecen pobreza y tienen hambre; pero los que buscan á Dios no tendrán falta de ningún bien.",c:["Bendición","Confianza","Dios"]},
  {r:"Amós 3:7",t:"Porque no hará nada el Señor Dios, sin que revele su secreto á sus siervos los profetas.",c:["Profecía","Dios","Verdad"]},
  {r:"2 Pedro 1:21",t:"Porque la profecía no fué en los tiempos pasados traída por voluntad humana, sino los santos hombres de Dios hablaron siendo inspirados del Espíritu Santo.",c:["Profecía","Dios","Verdad"]},
  {r:"Isaías 46:10",t:"Que anuncio lo por venir desde el principio, y desde la antigüedad lo que aun no era hecho.",c:["Profecía","Dios","Poder"]},
  {r:"Jeremías 1:5",t:"Antes que te formase en el vientre te conocí, y antes que nacieses te santifiqué.",c:["Profecía","Dios","Amor incondicional"]},
  {r:"1 Corintios 14:3",t:"Mas el que profetiza habla á los hombres para edificación, y exhortación y consolación.",c:["Profecía","Amor","Dios"]},
  {r:"Marcos 16:17",t:"Y estas señales seguirán á los que creyeren: En mi nombre echarán fuera demonios.",c:["Milagros","Fe activa","Poder"]},
  {r:"Juan 14:12",t:"El que en mí cree, las obras que yo hago, él las hará también; y aun mayores obras que éstas hará.",c:["Milagros","Fe activa","Poder"]},
  {r:"Hebreos 13:8",t:"Jesucristo es el mismo ayer, y hoy, y por los siglos.",c:["Milagros","Eternidad","Dios","Confianza"]},
  {r:"Salmos 77:14",t:"Tú eres el Dios que hace maravillas; hiciste notoria tu fortaleza entre los pueblos.",c:["Milagros","Dios","Poder","Gloria"]},
  {r:"Lucas 18:27",t:"Lo que es imposible para los hombres, es posible para Dios.",c:["Milagros","Poder","Dios","Fe activa"]},
  {r:"Salmos 107:20",t:"Envió su palabra, y los sanó, y los libró de su ruina.",c:["Milagros","Dios","Poder","Vida"]},
  {r:"Éxodo 15:26",t:"Yo soy Dios tu sanador.",c:["Milagros","Dios","Vida"]},
  {r:"Jeremías 30:17",t:"Mas yo haré venir sanidad para ti, y sanaré tus heridas, dice Dios.",c:["Milagros","Dios","Esperanza viva"]},
  {r:"Santiago 5:15",t:"Y la oración de fe salvará al enfermo, y el Señor lo levantará.",c:["Milagros","Oración","Fe activa"]},
  {r:"1 Corintios 15:20",t:"Mas ahora Cristo ha resucitado de los muertos; primicias de los que durmieron es hecho.",c:["Resurrección","Esperanza viva","Vida"]},
  {r:"Romanos 6:9",t:"Sabiendo que Cristo, habiendo resucitado de los muertos, ya no muere; la muerte no se enseñorea más de él.",c:["Resurrección","Vida","Eternidad","Poder"]},
  {r:"Romanos 8:11",t:"Y si el Espíritu del que levantó á Jesús de los muertos morare en vosotros, él también vivificará vuestros cuerpos mortales.",c:["Resurrección","Poder","Vida","Dios"]},
  {r:"Filipenses 3:10",t:"A fin de conocerle, y el poder de su resurrección.",c:["Resurrección","Poder","Fe activa"]},
  {r:"Salmos 90:2",t:"Desde el siglo y hasta el siglo, tú eres Dios.",c:["Eternidad","Dios"]},
  {r:"1 Juan 2:17",t:"El mundo pasa y sus deseos; pero el que hace la voluntad de Dios permanece para siempre.",c:["Eternidad","Obediencia","Dios"]},
  {r:"Mateo 6:33",t:"Buscad primero el reino de Dios y su justicia, y todas estas cosas os serán añadidas.",c:["Reino","Justicia","Dios","Confianza"]},
  {r:"Lucas 17:21",t:"El reino de Dios está entre vosotros.",c:["Reino","Dios"]},
  {r:"1 Corintios 4:20",t:"Porque el reino de Dios no consiste en palabras, sino en virtud.",c:["Reino","Poder","Dios","Fe activa"]},
  {r:"Mateo 5:3",t:"Bienaventurados los pobres en espíritu; porque de ellos es el reino de los cielos.",c:["Reino","Humildad","Bendición"]},
  {r:"Daniel 4:34",t:"El dominio de él es dominio eterno, y su reino por todas las generaciones.",c:["Reino","Eternidad","Dios","Gloria"]},
  {r:"Marcos 1:15",t:"Arrepentíos y creed en el evangelio.",c:["Reino","Arrepentimiento","Fe","Salvación"]},
  {r:"Romanos 12:1",t:"Os ruego, pues, hermanos, por las misericordias de Dios, que presentéis vuestros cuerpos por sacrificio vivo, santo, agradable á Dios.",c:["Sacrificio","Santificación","Obediencia","Dios"]},
  {r:"Hebreos 9:22",t:"Sin derramamiento de sangre no se hace remisión.",c:["Sacrificio","Redención","Perdón eterno"]},
  {r:"Isaías 53:5",t:"Él fue herido por nuestras rebeliones; y por su llaga fuimos nosotros curados.",c:["Sacrificio","Redención","Salvación","Gracia divina","Milagros"]},
  {r:"Hebreos 10:10",t:"En esa voluntad somos santificados por la ofrenda del cuerpo de Jesucristo, hecha una sola vez.",c:["Sacrificio","Santificación","Redención"]},
  {r:"Efesios 5:2",t:"Y andad en amor, como también Cristo nos amó, y se entregó á sí mismo por nosotros, ofrenda y sacrificio á Dios.",c:["Sacrificio","Amor incondicional","Obediencia"]},
  {r:"Salmos 34:18",t:"Cercano está Dios á los quebrantados de corazón; y salvará á los contritos de espíritu.",c:["Dios","Amor incondicional","Misericordia","Paz interior"]},
  {r:"Mateo 5:4",t:"Bienaventurados los que lloran; porque ellos recibirán consolación.",c:["Amor incondicional","Esperanza viva","Bendición"]},
  {r:"1 Pedro 5:7",t:"Echando toda vuestra solicitud en él, porque él tiene cuidado de vosotros.",c:["Confianza","Dios","Paz interior","Amor incondicional"]},
  {r:"Salmos 55:22",t:"Echa sobre Dios tu carga, y él te sustentará; no dejará para siempre caído al justo.",c:["Confianza","Dios","Paz interior"]},
  {r:"Mateo 6:34",t:"No os afanéis pues por el día de mañana; que el día de mañana traerá su afán. Basta al día su afán.",c:["Confianza","Paz interior","Fe"]},
  {r:"Salmos 147:3",t:"El sana á los quebrantados de corazón, y liga sus heridas.",c:["Dios","Amor incondicional","Milagros","Paz interior"]},
  {r:"Romanos 8:28",t:"Y sabemos que á los que aman á Dios, todas las cosas les ayudan á bien.",c:["Confianza","Fe","Dios","Esperanza viva"]},
  {r:"Isaías 61:3",t:"Para dar á los afligidos de Sión gloria en lugar de ceniza, óleo de gozo en lugar de luto, manto de alegría en lugar del espíritu angustiado.",c:["Esperanza viva","Dios","Paz interior","Gloria"]},
  {r:"Romanos 5:3",t:"Nos gloriamos en las tribulaciones; sabiendo que la tribulación obra la paciencia; y la paciencia, la prueba; y la prueba, la esperanza.",c:["Fe activa","Esperanza","Esperanza viva","Gloria"]},
  {r:"2 Corintios 4:8",t:"En todo somos atribulados, mas no angustiados; en apuros, mas no desesperados; perseguidos, mas no desamparados; derribados, mas no destruídos.",c:["Esperanza viva","Fortaleza","Fe activa"]},
  {r:"Salmos 126:5",t:"Los que sembraron con lágrimas, con regocijo segarán.",c:["Esperanza","Fe activa","Esperanza viva"]},
  {r:"Salmos 34:19",t:"Muchas son las aflicciones del justo; mas de todas ellas le librará Dios.",c:["Esperanza viva","Confianza","Dios"]},
  {r:"Efesios 4:23",t:"Y renovaos en el espíritu de vuestra mente.",c:["Santificación","Vida","Paz interior"]},
  {r:"Salmos 103:3",t:"Él es quien perdona todas tus iniquidades, el que sana todas tus dolencias.",c:["Perdón eterno","Milagros","Dios","Misericordia"]},
  {r:"Salmos 91:1",t:"El que habita al abrigo del Altísimo, morará bajo la sombra del Omnipotente.",c:["Confianza","Dios","Paz interior"]},
  {r:"Salmos 121:7",t:"Dios te guardará de todo mal; él guardará tu alma.",c:["Confianza","Dios","Paz"]},
  {r:"Isaías 54:17",t:"Ninguna arma forjada contra ti prosperará.",c:["Confianza","Dios","Fortaleza","Bendición"]},
  {r:"2 Corintios 5:18",t:"Dios nos reconcilió consigo mismo por Cristo, y nos dió el ministerio de la reconciliación.",c:["Perdón","Redención","Amor"]},
  {r:"Romanos 5:10",t:"Siendo enemigos, fuimos reconciliados con Dios por la muerte de su Hijo.",c:["Redención","Sacrificio","Amor incondicional"]},
];

const KEYWORDS:[string,string[]][]=[
  ["Paz interior",["ansio","angustia","estres","estrés","preocup","nervios","agobio","intranquil","afan","afán","agitad"]],
  ["Amor incondicional",["solo","sola","soledad","abandon","nadie","rechaz","desampar","olvid","incomprendid"]],
  ["Perdón eterno",["culpa","culpable","avergon","vergüenza","me siento mal por","liberado de culpa"]],
  ["Esperanza viva",["tribulacion","tribulación","prueba","crisis","oscuro","terrible","caos","angustio","desesper"]],
  ["Fe activa",["rendirme","rendirse","no puedo mas","desistir","persistir","seguir adelante","constancia"]],
  ["Gracia divina",["indigno","indigna","no lo merezco","don de dios","regalo de dios","gracia de dios"]],
  ["Confianza",["confian","confío","confio","seguridad","refugio","amparo","apoyo"]],
  ["Amor",["amor","amar","amado","amada","querer","caridad","cariño","ternura"]],
  ["Fe",["fe ","creer","creo","duda","incredulidad","creyendo"]],
  ["Esperanza",["esperanza","sin salida","futuro","porvenir"]],
  ["Perdón",["perdon","perdón","falle","fallé","ofensa","perdonar"]],
  ["Salvación",["salvacion","salvación","salvo","salva","perdido","perdida"]],
  ["Gracia",["gracia"]],
  ["Paz",["paz ","tranquil","quietud","reposo","calma","serenidad"]],
  ["Justicia",["justicia","injusto","injusta","desigual","oprimido","discriminad"]],
  ["Sabiduría",["sabiduria","sabiduría","decisión","decision","guía","qué hacer","dirección","camino correcto"]],
  ["Oración",["oracion","oración","orar","oré","rezar","clamar","pedir a dios"]],
  ["Alabanza",["alabanza","alabar","gracias a dios","agradec","bendigo a dios","celebrar a dios"]],
  ["Misericordia",["misericordia","piedad","compasion","compasión"]],
  ["Fortaleza",["debil","débil","cansado","cansada","agotado","agotada","batallar","sin fuerzas"]],
  ["Humildad",["humild","soberbia","orgullo","envanec","arrogant"]],
  ["Obediencia",["obedec","mandamiento","voluntad de dios","obedecer"]],
  ["Santificación",["santificacion","santidad","santo","puro","pureza","limpio","consagrado"]],
  ["Redención",["redencion","redención","redimido","rescatar"]],
  ["Gloria",["gloria","majestad","honor","magnificencia","glorificar"]],
  ["Poder",["imposible","todo lo puede","omnipotente","fuerza de dios","poder de dios"]],
  ["Vida",["vida","vivir","propósito","razón de ser","sentido de la vida"]],
  ["Luz",["luz","tinieblas","oscuridad","alumbrar","iluminar"]],
  ["Verdad",["verdad","mentira","engaño","certeza"]],
  ["Juicio",["juicio","condenado","condenada","rendir cuentas","juzgar"]],
  ["Pecado",["pecado","transgresion","iniquidad","caí en pecado"]],
  ["Arrepentimiento",["arrepent","convertir","volver a dios","cambio de vida"]],
  ["Bendición",["bendicion","bendición","prosperidad","bendito","bendita"]],
  ["Profecía",["profecia","profecía","profeta","revelación","palabra cumplida"]],
  ["Milagros",["milagro","señal","prodigio","maravilla","sanidad","enferm","curar","sano"]],
  ["Resurrección",["resurreccion","resurrección","resucitar","vencer la muerte"]],
  ["Eternidad",["eternidad","eterno","eterna","para siempre","vida eterna"]],
  ["Reino",["reino de dios","gobierno de dios","rey de reyes","soberanía"]],
  ["Sacrificio",["sacrificio","ofrenda","inmolación"]],
  ["Dios",["dios","señor","eterno","creador","omnipotente"]],
];

const MSGS:Record<string,string>={
  "Confianza":"Puedes confiar plenamente en Dios; Él nunca falla.",
  "Dios":"Dios es real, cercano y está obrando en tu vida.",
  "Amor":"El amor de Dios es la fuerza que mueve toda cosa buena.",
  "Fe":"La fe mueve montañas; confía en lo que Dios puede hacer.",
  "Esperanza":"Aun cuando parece que no hay salida, Dios sigue siendo fuente de esperanza.",
  "Perdón":"Hay perdón y restauración para quien se acerca a Dios con sinceridad.",
  "Salvación":"Dios desea que todos sean salvos y lleguen al conocimiento de la verdad.",
  "Gracia":"La gracia de Dios es suficiente para ti, sin importar tu pasado.",
  "Paz":"La paz de Dios supera todo entendimiento; pídela en oración.",
  "Justicia":"Dios es justo y defiende al oprimido; en Él hay rectitud.",
  "Sabiduría":"Dios puede dar dirección y sabiduría cuando no sabes qué hacer.",
  "Oración":"Dios escucha cada oración; ningún clamor suyo se pierde.",
  "Alabanza":"La gratitud y la alabanza abren el corazón a la plenitud de Dios.",
  "Misericordia":"La misericordia de Dios es nueva cada mañana; Él se compadece.",
  "Fortaleza":"Cuando tus fuerzas se acaban, Dios puede sostenerte y renovarte.",
  "Humildad":"Dios da gracia a los humildes; la mansedumbre es fortaleza verdadera.",
  "Obediencia":"Obedecer a Dios es el camino a la vida plena.",
  "Santificación":"Dios nos llama a ser santos; su Espíritu nos capacita para ello.",
  "Redención":"Fuiste redimido por la sangre de Cristo; eres de inmenso valor.",
  "Gloria":"Toda la gloria pertenece a Dios; vivir para su gloria da sentido.",
  "Poder":"Nada es imposible para Dios; su poder no tiene límites.",
  "Vida":"Cristo vino a darte vida en abundancia; no mera existencia.",
  "Luz":"Dios es luz; en Él no hay ninguna tiniebla.",
  "Verdad":"La verdad de Dios libera; su Palabra es lámpara y lumbrera.",
  "Juicio":"Dios juzga con justicia perfecta; nada queda oculto ante Él.",
  "Pecado":"El pecado separa, pero la gracia de Dios es más poderosa.",
  "Arrepentimiento":"Dios recibe con amor a todo el que se vuelve a Él.",
  "Bendición":"Dios desea bendecirte; caminar en obediencia abre sus bendiciones.",
  "Profecía":"La Palabra de Dios se cumple; Él anuncia el fin desde el principio.",
  "Milagros":"El mismo Dios de los milagros de la Biblia actúa hoy en tu vida.",
  "Resurrección":"La resurrección de Cristo es la garantía de nuestra victoria.",
  "Eternidad":"Esta vida es un instante; la eternidad con Dios es la meta.",
  "Reino":"El reino de Dios es justicia, paz y gozo en el Espíritu Santo.",
  "Sacrificio":"Cristo se entregó completamente por amor; tú tienes inmenso valor.",
  "Paz interior":"Dios invita a dejar la ansiedad en sus manos. Respira, ora y descansa.",
  "Esperanza viva":"En los momentos más oscuros, Dios está obrando para tu bien.",
  "Fe activa":"No te rindas; Dios recompensa a quienes perseveran con fe.",
  "Amor incondicional":"Aunque te sientas solo, Dios no abandona a quienes le buscan.",
  "Gracia divina":"La gracia de Dios alcanza donde nada más puede llegar.",
  "Perdón eterno":"Tus pecados han sido borrados para siempre; camina en libertad.",
};

const CAT_MAP=new Map<string,V[]>();
for(const v of VERSES)for(const c of v.c){if(!CAT_MAP.has(c))CAT_MAP.set(c,[]);CAT_MAP.get(c)!.push(v);}
const ALL_CATS=[...CAT_MAP.keys()];

function norm(t:string){return t.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();}

export function findVerse(text:string):VerseResult{
  const n=norm(text);
  let cat="Esperanza";
  for(const[c,kws]of KEYWORDS)if(kws.some(k=>n.includes(norm(k)))){cat=c;break;}
  const verses=CAT_MAP.get(cat)??CAT_MAP.get("Esperanza")!;
  const v=verses[Math.floor(Math.random()*verses.length)];
  return{detected_category:cat,message:MSGS[cat]??"",verse_reference:v.r,verse_text:v.t};
}

export function randomVerse():VerseResult{
  const cat=ALL_CATS[Math.floor(Math.random()*ALL_CATS.length)];
  const verses=CAT_MAP.get(cat)!;
  const v=verses[Math.floor(Math.random()*verses.length)];
  return{detected_category:cat,message:MSGS[cat]??"",verse_reference:v.r,verse_text:v.t};
}

export function getAllCategories(){
  return ALL_CATS.map(c=>({id:c.toLowerCase().replace(/\s+/g,"_"),label:c,count:CAT_MAP.get(c)!.length}));
}
