export interface VerseResult {
  detected_category: string;
  message: string;
  verse_reference: string;
  verse_text: string;
}

interface Category {
  id: string;
  label: string;
  keywords: string[];
  message: string;
  verses: [string, string][];
}

const CATEGORIES: Category[] = [
  {
    id: "ansiedad",
    label: "Ansiedad",
    keywords: ["ansiedad", "ansioso", "ansiosa", "angustia", "afan", "afán", "preocup", "nervios", "estres", "estrés", "agobio"],
    message: "Dios invita a dejar la ansiedad en sus manos. Respira, ora y descansa en su cuidado.",
    verses: [
      ["Filipenses 4:6", "Por nada estéis afanosos; sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con hacimiento de gracias."],
      ["Filipenses 4:7", "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús."],
      ["1 Pedro 5:7", "Echando toda vuestra solicitud en él, porque él tiene cuidado de vosotros."],
      ["Mateo 6:34", "No os afanéis pues por el día de mañana; que el día de mañana traerá su afán. Basta al día su afán."],
      ["Isaías 26:3", "Tú guardarás en completa paz á aquel cuyo pensamiento en ti persevera; porque en ti ha confiado."],
      ["Mateo 11:28", "Venid á mí todos los que estáis trabajados y cargados, y yo os haré descansar."],
      ["Salmos 55:22", "Echa sobre Jehová tu carga, y él te sustentará; no dejará para siempre caído al justo."],
      ["Juan 14:27", "La paz os dejo, mi paz os doy; no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo."],
      ["Salmos 46:1", "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones."],
      ["Salmos 4:8", "En paz me acostaré asimismo, y dormiré; porque solo tú, Jehová, me haces vivir confiado."],
    ],
  },
  {
    id: "miedo",
    label: "Miedo",
    keywords: ["miedo", "temo", "temor", "terror", "aterror", "asusta", "asustado", "asustada", "insegur", "atemori"],
    message: "Cuando hay miedo, la Biblia recuerda que Dios acompaña y fortalece.",
    verses: [
      ["Isaías 41:10", "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia."],
      ["2 Timoteo 1:7", "Porque no nos ha dado Dios el espíritu de cobardía, sino de poder, de amor y de templanza."],
      ["Salmos 23:4", "Aunque ande en valle de sombra de muerte, no temeré mal alguno; porque tú estarás conmigo."],
      ["Josué 1:9", "¿No te mandé que te esforzases y fueses valiente? No temas, ni desmayes; porque Jehová tu Dios será contigo en dondequiera que fueres."],
      ["Salmos 27:1", "Jehová es mi luz y mi salvación: ¿de quién temeré? Jehová es la fortaleza de mi vida: ¿de quién me receleré?"],
      ["Isaías 43:1", "No temas, porque yo te redimí; te puse nombre, mío eres tú."],
      ["Salmos 56:3", "El día que temo, yo en ti confío."],
      ["Deuteronomio 31:6", "Esforzaos y cobrad ánimo; no temáis, ni tengáis miedo de ellos; porque Jehová tu Dios, es el que va contigo."],
      ["Salmos 91:11", "Pues que á sus ángeles mandará acerca de ti, que te guarden en todos tus caminos."],
      ["Hebreos 13:6", "El Señor es mi ayudador; no temeré lo que me hará el hombre."],
    ],
  },
  {
    id: "tristeza",
    label: "Tristeza",
    keywords: ["triste", "tristeza", "dolor", "llant", "llor", "depres", "desanim", "pena", "angustia", "abatid"],
    message: "En medio de la tristeza, Dios permanece cerca del corazón quebrantado.",
    verses: [
      ["Salmos 34:18", "Cercano está Jehová á los quebrantados de corazón; y salvará á los contritos de espíritu."],
      ["Mateo 5:4", "Bienaventurados los que lloran; porque ellos recibirán consolación."],
      ["Apocalipsis 21:4", "Enjugará Dios toda lágrima de los ojos de ellos; y la muerte no será más, ni habrá más llanto, ni clamor, ni dolor."],
      ["Salmos 30:5", "Por un momento será su ira; mas su benevolencia dura toda la vida. Por la tarde durará el lloro, y á la mañana vendrá la alegría."],
      ["Salmos 126:5", "Los que sembraron con lágrimas, con regocijo segarán."],
      ["Isaías 41:10", "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo."],
      ["Lamentaciones 3:22", "Las misericordias de Jehová no se han acabado; porque no faltaron sus bondades. Nuevas son cada mañana; grande es tu fidelidad."],
      ["Salmos 147:3", "El sana á los quebrantados de corazón, y liga sus heridas."],
      ["Romanos 8:28", "Y sabemos que á los que aman á Dios, todas las cosas les ayudan á bien."],
      ["Isaías 61:3", "Á ordenar que á los afligidos de Sión se les dé gloria en lugar de ceniza, óleo de gozo en lugar de luto, manto de alegría en lugar del espíritu angustiado."],
    ],
  },
  {
    id: "soledad",
    label: "Soledad",
    keywords: ["solo", "sola", "soledad", "abandon", "rechazo", "nadie", "olvid", "desampar"],
    message: "Aunque te sientas solo o sola, Dios no abandona a quienes le buscan.",
    verses: [
      ["Hebreos 13:5", "No te desampararé, ni te dejaré."],
      ["Mateo 28:20", "He aquí, yo estoy con vosotros todos los días, hasta el fin del mundo."],
      ["Josué 1:9", "Jehová tu Dios será contigo en dondequiera que fueres."],
      ["Salmos 27:10", "Aunque mi padre y mi madre me dejaran, con todo, Jehová me recogerá."],
      ["Isaías 43:2", "Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán."],
      ["Isaías 49:15", "¿Olvidará la mujer su niño que mamanta? ¿dejará de compadecerse del hijo de su vientre? Aunque éstas olvidaran, yo nunca me olvidaré de ti."],
      ["Salmos 68:5", "Padre de los huérfanos y defensor de las viudas es Dios en su santa morada."],
      ["Deuteronomio 31:8", "Jehová es el que va delante de ti; él será contigo, no te dejará, ni te desamparará."],
      ["Salmos 139:7", "¿A dónde me iré de tu espíritu? ¿Y á dónde huiré de tu presencia?"],
      ["Romanos 8:38", "Por lo cual estoy seguro de que ni la muerte, ni la vida... ni ninguna otra cosa creada nos podrá separar del amor de Dios."],
    ],
  },
  {
    id: "perdon",
    label: "Perdón",
    keywords: ["perdon", "perdón", "culpa", "culpable", "pecado", "falle", "fallé", "arrepent", "verguenza", "vergüenza"],
    message: "Hay perdón y restauración para quien se acerca a Dios con sinceridad.",
    verses: [
      ["1 Juan 1:9", "Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad."],
      ["Salmos 103:12", "Cuanto está lejos el oriente del occidente, hizo alejar de nosotros nuestras rebeliones."],
      ["Isaías 43:25", "Yo, yo soy el que borro tus rebeliones por amor de mí mismo; y no me acordaré de tus pecados."],
      ["Efesios 4:32", "Sed pues benignos unos con otros, misericordiosos, perdonándoos unos á otros, como también Dios os perdonó á vosotros en Cristo."],
      ["Miqueas 7:18", "¿Qué Dios como tú, que perdona la maldad, y olvida el pecado del remanente de su heredad?"],
      ["Salmos 32:5", "Mi pecado te declaré, y no encubrí mi iniquidad. Dije: Confesaré mis rebeliones á Jehová; y tú perdonaste la maldad de mi pecado."],
      ["Isaías 44:22", "Yo desvanecí como nube tus transgresiones, y como niebla tus pecados: vuélvete á mí, porque yo te redimí."],
      ["Hechos 3:19", "Arrepentíos y convertíos, para que sean borrados vuestros pecados."],
    ],
  },
  {
    id: "esperanza",
    label: "Esperanza",
    keywords: ["esperanza", "desesper", "sin salida", "futuro", "rendirme", "rendirse", "no puedo mas", "no puedo más"],
    message: "Aun cuando parece que no hay salida, Dios sigue siendo fuente de esperanza.",
    verses: [
      ["Jeremías 29:11", "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz y no de mal, para daros el fin que esperáis."],
      ["Romanos 15:13", "Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por la virtud del Espíritu Santo."],
      ["Salmos 71:5", "Porque tú, oh Señor Jehová, eres mi esperanza, seguridad mía desde mi juventud."],
      ["Isaías 40:31", "Pero los que esperan á Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán."],
      ["Lamentaciones 3:25", "Bueno es Jehová á los que en él esperan, al alma que le busca."],
      ["Romanos 5:5", "Y la esperanza no avergüenza; porque el amor de Dios está derramado en nuestros corazones por el Espíritu Santo que nos fue dado."],
      ["Salmos 31:24", "Esforzaos, y aliente vuestro corazón, todos los que esperáis en Jehová."],
      ["Salmos 42:11", "¿Por qué te abates, oh alma mía, y por qué te conturbas en mí? Espera en Dios; porque aún le tengo que alabar."],
    ],
  },
  {
    id: "fortaleza",
    label: "Fortaleza",
    keywords: ["debil", "débil", "cansado", "cansada", "fuerza", "fortaleza", "agotado", "agotada", "cansancio", "batalla"],
    message: "Cuando tus fuerzas se acaban, Dios puede sostenerte y renovarte.",
    verses: [
      ["Filipenses 4:13", "Todo lo puedo en Cristo que me fortalece."],
      ["Salmos 46:1", "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones."],
      ["Isaías 40:29", "Él da esfuerzo al cansado, y multiplica las fuerzas al que no tiene ningunas."],
      ["Isaías 40:31", "Los que esperan á Jehová tendrán nuevas fuerzas; levantarán alas como las águilas."],
      ["2 Corintios 12:9", "Bástate mi gracia; porque mi potencia en la flaqueza se perfecciona."],
      ["Salmos 28:7", "Jehová es mi fortaleza y mi escudo; en él confió mi corazón, y fui ayudado."],
      ["Efesios 6:10", "Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza."],
      ["Josué 1:9", "Esfuérzate y sé valiente; no temas, ni desmayes; porque Jehová tu Dios será contigo."],
    ],
  },
  {
    id: "sabiduria",
    label: "Sabiduría",
    keywords: ["sabiduria", "sabiduría", "decision", "decisión", "guia", "guía", "camino", "que hacer", "qué hacer", "direccion", "dirección"],
    message: "Dios puede dar dirección y sabiduría cuando no sabes qué hacer.",
    verses: [
      ["Santiago 1:5", "Y si alguno de vosotros tiene falta de sabiduría, demándela á Dios, el cual da á todos abundantemente y sin reproche; y le será dada."],
      ["Proverbios 3:5", "Confía en Jehová de todo tu corazón, y no te apoyes en tu propia prudencia."],
      ["Proverbios 2:6", "Porque Jehová da la sabiduría; y de su boca viene el conocimiento y la inteligencia."],
      ["Salmos 32:8", "Te haré entender, y te enseñaré el camino en que debes andar; sobre ti fijaré mis ojos."],
      ["Proverbios 16:3", "Encomienda á Jehová tus obras, y tus pensamientos serán afirmados."],
      ["Isaías 30:21", "Entonces tus oídos oirán á tus espaldas palabra que diga: Este es el camino, andad por él."],
      ["Salmos 119:105", "Lámpara es á mis pies tu palabra, y lumbrera á mi camino."],
      ["Proverbios 3:6", "Reconócelo en todos tus caminos, y él enderezará tus veredas."],
    ],
  },
  {
    id: "amor",
    label: "Amor",
    keywords: ["amor", "amar", "amado", "amada", "querer", "caridad", "carino", "cariño"],
    message: "El amor de Dios es eterno e incondicional, nada puede separarte de él.",
    verses: [
      ["Juan 3:16", "Porque de tal manera amó Dios al mundo, que ha dado á su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna."],
      ["1 Juan 4:8", "El que no ama, no conoce á Dios; porque Dios es amor."],
      ["Romanos 8:39", "Ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios, que es en Cristo Jesús Señor nuestro."],
      ["1 Corintios 13:4", "La caridad es sufrida, es benigna; la caridad no tiene envidia, la caridad no es jactanciosa, no se ensoberbece."],
      ["1 Corintios 13:13", "Y ahora permanecen la fe, la esperanza, el amor, estos tres; pero el mayor de ellos es el amor."],
      ["Juan 15:13", "Nadie tiene mayor amor que éste, que ponga alguno su vida por sus amigos."],
      ["1 Pedro 4:8", "Y ante todo, tened entre vosotros fervorosa caridad; porque la caridad cubrirá multitud de pecados."],
      ["1 Juan 4:16", "Dios es amor; y el que está en amor, está en Dios, y Dios en él."],
    ],
  },
  {
    id: "fe",
    label: "Fe",
    keywords: ["fe", "creer", "creo", "duda", "incredulidad", "fidelidad", "confianza"],
    message: "La fe mueve montañas; confía en lo que Dios puede hacer aunque no lo veas.",
    verses: [
      ["Hebreos 11:1", "Es pues la fe la certeza de lo que se espera, la demostración de lo que no se ve."],
      ["Marcos 9:23", "Si puedes creer, al que cree todo le es posible."],
      ["Efesios 2:8", "Porque por gracia sois salvos por la fe; y esto no de vosotros, pues es don de Dios."],
      ["Hebreos 11:6", "Pero sin fe es imposible agradar á Dios; porque es necesario que el que se allega á Dios, crea que le hay."],
      ["Romanos 10:17", "Así que la fe es por el oír, y el oír, por la palabra de Dios."],
      ["Mateo 17:20", "Si tuviéreis fe como un grano de mostaza, diréis á este monte: Pásate de aquí allá, y se pasará; y nada os será imposible."],
      ["Santiago 2:17", "Así también la fe, si no tuviere obras, es muerta en sí misma."],
      ["Marcos 11:22", "Tened fe en Dios."],
    ],
  },
  {
    id: "paciencia",
    label: "Paciencia",
    keywords: ["paciencia", "esperar", "demorar", "tardar", "pronto", "urgente", "impacient"],
    message: "En la espera, Dios está obrando. Su tiempo es perfecto.",
    verses: [
      ["Isaías 40:31", "Los que esperan á Jehová tendrán nuevas fuerzas; levantarán alas como las águilas."],
      ["Romanos 5:3", "Nos gloriamos en las tribulaciones; sabiendo que la tribulación obra la paciencia."],
      ["Santiago 1:3", "Sabiendo que la prueba de vuestra fe obra la paciencia."],
      ["Hebreos 10:36", "Porque os es necesaria la paciencia; para que, habiendo hecho la voluntad de Dios, obtengáis la promesa."],
      ["Salmos 37:7", "Guarda silencio ante Jehová, y espérale."],
      ["Santiago 5:11", "He aquí, tenemos por bienaventurados á los que sufren. El Señor es muy misericordioso y piadoso."],
      ["Lamentaciones 3:26", "Bueno es esperar en silencio la salud de Jehová."],
      ["Romanos 12:12", "Gozosos en la esperanza; pacientes en la tribulación; constantes en la oración."],
    ],
  },
  {
    id: "gratitud",
    label: "Gratitud",
    keywords: ["gratitud", "gracias", "agradec", "alabar", "alabanza", "bendecir"],
    message: "La gratitud abre el corazón a la plenitud de Dios.",
    verses: [
      ["1 Tesalonicenses 5:18", "Dad gracias en todo: porque esta es la voluntad de Dios para con vosotros en Cristo Jesús."],
      ["Salmos 100:4", "Entrad por sus puertas con alabanza, por sus atrios con alabanza; alabadle, bendecid su nombre."],
      ["Efesios 5:20", "Dando siempre gracias por todo al Dios y Padre, en el nombre de nuestro Señor Jesucristo."],
      ["Salmos 107:1", "Alabad á Jehová, porque él es bueno; porque para siempre es su misericordia."],
      ["Colosenses 3:17", "Todo lo que hacéis, hacedlo todo en el nombre del Señor Jesús, dando gracias á Dios y Padre por él."],
      ["Salmos 136:1", "Alabad á Jehová, porque él es bueno: Porque para siempre es su misericordia."],
      ["Salmos 50:23", "El que sacrifica alabanza me honrará; y al que ordenare su camino, le mostraré la salvación de Dios."],
      ["Salmos 9:1", "Te alabaré, oh Jehová, con todo mi corazón; contaré todas tus maravillas."],
    ],
  },
  {
    id: "alegria",
    label: "Alegría",
    keywords: ["alegria", "alegría", "gozo", "regocijo", "contento", "feliz", "felicidad"],
    message: "El gozo del Señor es tu fortaleza; Él es fuente de alegría verdadera.",
    verses: [
      ["Nehemías 8:10", "El gozo de Jehová es vuestra fortaleza."],
      ["Salmos 16:11", "En tu presencia hay hartura de gozos; á tu diestra hay deleites para siempre."],
      ["Filipenses 4:4", "Alegraos en el Señor siempre: otra vez digo que os alegréis."],
      ["Salmos 126:3", "Grandes cosas ha hecho Jehová con nosotros; estaremos alegres."],
      ["Juan 15:11", "Estas cosas os he hablado, para que mi gozo esté en vosotros, y vuestro gozo sea cumplido."],
      ["Salmos 30:5", "Por la tarde durará el lloro, y á la mañana vendrá la alegría."],
      ["Salmos 32:11", "Alegraos en Jehová y gozaos, justos; y cantad con júbilo todos vosotros los rectos de corazón."],
      ["Romanos 15:13", "El Dios de esperanza os llene de todo gozo y paz en el creer."],
    ],
  },
  {
    id: "confianza",
    label: "Confianza",
    keywords: ["confianza", "confiar", "seguridad", "apoyo", "refugio", "amparo"],
    message: "Puedes confiar plenamente en Dios; Él nunca falla a los que le buscan.",
    verses: [
      ["Proverbios 3:5", "Confía en Jehová de todo tu corazón, y no te apoyes en tu propia prudencia."],
      ["Jeremías 17:7", "Bendito el varón que confía en Jehová, y cuya confianza es Jehová."],
      ["Isaías 26:3", "Tú guardarás en completa paz á aquel cuyo pensamiento en ti persevera; porque en ti ha confiado."],
      ["Salmos 56:4", "En Dios alabaré su palabra; en Dios he confiado, no temeré."],
      ["Salmos 27:1", "Jehová es mi luz y mi salvación: ¿de quién temeré?"],
      ["Salmos 62:8", "Esperad en él en todo tiempo, oh pueblos: derramad delante de él vuestro corazón: Dios es nuestro refugio."],
      ["Salmos 9:10", "Y en ti confiarán los que conocen tu nombre; por cuanto no desamparaste á los que te buscaron."],
      ["Salmos 46:1", "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones."],
    ],
  },
  {
    id: "perseverancia",
    label: "Perseverancia",
    keywords: ["perseverancia", "rendirse", "rendirme", "desistir", "continuar", "seguir", "constancia", "persistir"],
    message: "No te rindas; Dios recompensa a quienes perseveran con fe.",
    verses: [
      ["Gálatas 6:9", "Y no nos cansemos de hacer bien; porque á su tiempo segaremos, si no desmayáremos."],
      ["Hebreos 12:1", "Corramos con paciencia la carrera que tenemos por delante."],
      ["Santiago 1:12", "Bienaventurado el varón que soporta la prueba; porque cuando fuere probado, recibirá la corona de vida."],
      ["2 Timoteo 4:7", "He peleado la buena batalla, he acabado la carrera, he guardado la fe."],
      ["Apocalipsis 2:10", "Sé fiel hasta la muerte, y yo te daré la corona de la vida."],
      ["1 Corintios 15:58", "Estad firmes y constantes, creciendo en la obra del Señor siempre."],
      ["Josué 1:7", "Solamente esfuérzate y sé muy valiente, para cuidar de hacer conforme á toda la ley."],
      ["Salmos 37:24", "Cuando cayere, no quedará postrado; porque Jehová sostiene su mano."],
    ],
  },
  {
    id: "salud",
    label: "Salud",
    keywords: ["salud", "enfermo", "enferma", "enfermedad", "sanidad", "sano", "curar", "curacion", "curación", "herida"],
    message: "Dios es el sanador; entrega tu salud en sus manos con fe.",
    verses: [
      ["Éxodo 15:26", "Yo soy Jehová tu sanador."],
      ["Salmos 103:3", "Él es quien perdona todas tus iniquidades, el que sana todas tus dolencias."],
      ["Jeremías 30:17", "Mas yo haré venir sanidad para ti, y sanaré tus heridas, dice Jehová."],
      ["3 Juan 1:2", "Amado, yo deseo que tú seas prosperado en todas las cosas, y que tengas salud, así como prospera tu alma."],
      ["Isaías 53:5", "Él fue herido por nuestras rebeliones; y por su llaga fuimos nosotros curados."],
      ["Santiago 5:15", "Y la oración de fe salvará al enfermo, y el Señor lo levantará."],
      ["Salmos 107:20", "Envió su palabra, y los sanó, y los libró de su ruina."],
      ["Proverbios 4:22", "Porque vida son á los que las hallaren, y medicina á todo su cuerpo."],
    ],
  },
  {
    id: "proteccion",
    label: "Protección",
    keywords: ["proteccion", "protección", "proteger", "peligro", "amenaza", "seguridad", "guardian", "guardián", "escudo", "defensa"],
    message: "Dios es tu escudo y refugio; bajo su amparo estás seguro.",
    verses: [
      ["Salmos 91:1", "El que habita al abrigo del Altísimo, morará bajo la sombra del Omnipotente."],
      ["Salmos 91:11", "Pues que á sus ángeles mandará acerca de ti, que te guarden en todos tus caminos."],
      ["Salmos 34:7", "El ángel de Jehová acampa alrededor de los que le temen, y los defiende."],
      ["Salmos 121:7", "Jehová te guardará de todo mal; él guardará tu alma."],
      ["Isaías 54:17", "Ninguna arma forjada contra ti prosperará."],
      ["Salmos 27:5", "Porque él me esconderá en su tabernáculo en el día del mal."],
      ["2 Tesalonicenses 3:3", "Mas fiel es el Señor, que os afirmará y guardará del mal."],
      ["Salmos 46:2", "No temeremos, aunque la tierra se cambie, y aunque los montes se traspasen al corazón de la mar."],
    ],
  },
  {
    id: "paz",
    label: "Paz",
    keywords: ["paz", "tranquilidad", "quietud", "reposo", "descanso", "calma", "sereno", "serenidad"],
    message: "La paz de Dios supera todo entendimiento; pídela en oración.",
    verses: [
      ["Juan 14:27", "La paz os dejo, mi paz os doy; no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo."],
      ["Filipenses 4:7", "Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús."],
      ["Salmos 4:8", "En paz me acostaré asimismo, y dormiré; porque solo tú, Jehová, me haces vivir confiado."],
      ["Isaías 26:3", "Tú guardarás en completa paz á aquel cuyo pensamiento en ti persevera."],
      ["Números 6:26", "Jehová alce sobre ti su rostro, y ponga en ti paz."],
      ["Romanos 8:6", "El ocuparse del espíritu es vida y paz."],
      ["Salmos 29:11", "Jehová dará fortaleza á su pueblo; Jehová bendecirá á su pueblo con paz."],
      ["Isaías 32:17", "Y el trabajo de la justicia será paz; y la labor de la justicia, reposo y seguridad para siempre."],
    ],
  },
  {
    id: "humildad",
    label: "Humildad",
    keywords: ["humildad", "humilde", "orgullo", "soberbia", "arrogancia", "vanidad"],
    message: "Dios resiste al orgulloso pero da gracia al humilde.",
    verses: [
      ["Santiago 4:6", "Dios resiste á los soberbios, y da gracia á los humildes."],
      ["Miqueas 6:8", "Solamente hacer juicio, y amar misericordia, y humillarte ante tu Dios."],
      ["Mateo 23:12", "Porque cualquiera que se ensalzare, será humillado; y el que se humillare, será ensalzado."],
      ["1 Pedro 5:6", "Humillaos pues bajo la poderosa mano de Dios, para que él os ensalce á su tiempo."],
      ["Filipenses 2:3", "En humildad, estimando cada uno á los otros como superiores á él mismo."],
      ["Proverbios 22:4", "Riquezas y honra y vida son el galardón de la humildad y del temor de Jehová."],
      ["Salmos 138:6", "Jehová es excelso, y atiende al humilde; mas al soberbio conoce de lejos."],
      ["Proverbios 11:2", "Con los humildes está la sabiduría."],
    ],
  },
  {
    id: "obediencia",
    label: "Obediencia",
    keywords: ["obediencia", "obedecer", "mandamiento", "ley", "voluntad de dios", "mandato"],
    message: "Obedecer a Dios es el camino a la bendición y la vida plena.",
    verses: [
      ["Juan 14:15", "Si me amáis, guardad mis mandamientos."],
      ["1 Samuel 15:22", "El obedecer es mejor que los sacrificios; el prestar atención, que el gordo de los carneros."],
      ["Salmos 119:11", "En mi corazón he guardado tus dichos, para no pecar contra ti."],
      ["Hechos 5:29", "Es menester obedecer á Dios antes que á los hombres."],
      ["Lucas 11:28", "Bienaventurados los que oyen la palabra de Dios, y la guardan."],
      ["Deuteronomio 11:1", "Amarás pues á Jehová tu Dios, y guardarás sus ordenanzas y sus estatutos y sus mandamientos."],
      ["Romanos 6:17", "Habéis obedecido de corazón á aquella forma de doctrina á que fuisteis entregados."],
      ["Josué 22:5", "Que améis á Jehová vuestro Dios, y andéis en todos sus caminos."],
    ],
  },
  {
    id: "justicia",
    label: "Justicia",
    keywords: ["justicia", "injusticia", "injusto", "justo", "rectitud", "equidad", "opresion", "opresión"],
    message: "Dios es juez justo; confía en Él cuando la injusticia te rodea.",
    verses: [
      ["Amós 5:24", "Antes corra el juicio como las aguas, y la justicia como impetuoso arroyo."],
      ["Proverbios 21:3", "El hacer justicia y juicio es á Jehová más agradable que el sacrificio."],
      ["Salmos 37:28", "Jehová ama el juicio, y no desampara á sus santos."],
      ["Isaías 61:8", "Porque yo Jehová amo el juicio; aborrezco el robo con iniquidad."],
      ["Romanos 12:19", "Mía es la venganza, yo pagaré, dice el Señor."],
      ["Salmos 89:14", "Justicia y juicio son el asiento de tu trono: misericordia y verdad van delante de tu rostro."],
      ["Proverbios 29:7", "El justo entiende la causa de los pobres."],
      ["Miqueas 6:8", "¿Qué pide Jehová de ti: solamente hacer juicio, y amar misericordia, y humillarte ante tu Dios?"],
    ],
  },
  {
    id: "salvacion",
    label: "Salvación",
    keywords: ["salvacion", "salvación", "salvo", "salvar", "redimir", "eterno", "eternity", "vida eterna"],
    message: "La salvación es don gratuito de Dios; solo recibirla con fe.",
    verses: [
      ["Hechos 4:12", "Y en ningún otro hay salvación; porque no hay otro nombre bajo el cielo, dado á los hombres, en que podamos ser salvos."],
      ["Romanos 10:9", "Si confesares con tu boca al Señor Jesús, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo."],
      ["Efesios 2:8", "Porque por gracia sois salvos por la fe; y esto no de vosotros, pues es don de Dios."],
      ["Isaías 12:2", "He aquí que Dios es mi salvación; me aseguraré y no temeré."],
      ["Juan 10:9", "Yo soy la puerta: el que por mí entrare, será salvo."],
      ["Tito 3:5", "No por obras de justicia que nosotros hayamos hecho, sino por su misericordia, nos salvó."],
      ["2 Timoteo 1:9", "El cual nos salvó y llamó con vocación santa, conforme á la gracia que nos fue dada en Cristo Jesús."],
      ["Romanos 6:23", "Porque la paga del pecado es muerte: mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro."],
    ],
  },
  {
    id: "oracion",
    label: "Oración",
    keywords: ["oracion", "oración", "orar", "clamar", "rogar", "pedir", "interceder"],
    message: "La oración te conecta con Dios; Él oye y responde a sus hijos.",
    verses: [
      ["Mateo 7:7", "Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá."],
      ["1 Tesalonicenses 5:17", "Orad sin cesar."],
      ["Santiago 5:16", "La oración eficaz del justo puede mucho."],
      ["Jeremías 33:3", "Clama á mí, y yo te responderé, y te enseñaré cosas grandes y dificultosas que tú no sabes."],
      ["Lucas 18:1", "Era necesario orar siempre, y no desmayar."],
      ["1 Juan 5:14", "Si demandáremos alguna cosa conforme á su voluntad, él nos oye."],
      ["Filipenses 4:6", "Sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con hacimiento de gracias."],
      ["Salmos 55:17", "Tarde y mañana y á mediodía oraré y clamaré; y él oirá mi voz."],
    ],
  },
  {
    id: "disciplina",
    label: "Disciplina",
    keywords: ["disciplina", "correccion", "corrección", "castigo", "reprension", "reprensión", "aprender", "ensenanza", "enseñanza"],
    message: "La corrección de Dios es señal de amor; produce fruto de vida.",
    verses: [
      ["Hebreos 12:11", "Ninguna disciplina parece por el presente ser de gozo sino de tristeza; mas después da fruto apacible de justicia."],
      ["Proverbios 3:11", "No desprecies la corrección de Jehová, ni te fatigues de su reprensión: Porque Jehová al que ama castiga."],
      ["2 Timoteo 1:7", "Porque no nos ha dado Dios el espíritu de cobardía, sino de poder, y de amor y de templanza."],
      ["Proverbios 10:17", "El que guarda la enseñanza, está en la carrera de la vida."],
      ["Tito 2:12", "Enseñándonos que, renunciando á la impiedad y á los deseos mundanos, vivamos sobria, justa, y piadosamente."],
      ["1 Corintios 9:27", "Golpeo mi cuerpo y lo pongo en servidumbre; no sea que habiendo predicado á otros, yo mismo venga á ser reprobado."],
      ["Proverbios 12:1", "El que ama la doctrina, ama la sabiduría."],
      ["Hebreos 12:6", "Porque el Señor al que ama, disciplina."],
    ],
  },
  {
    id: "bondad",
    label: "Bondad",
    keywords: ["bondad", "bueno", "benignidad", "bien", "generoso", "generosidad"],
    message: "Dios es bueno; su bondad se derrama sobre quienes le buscan.",
    verses: [
      ["Salmos 34:8", "Gustad, y ved que es bueno Jehová: bienaventurado el hombre que en él confia."],
      ["Gálatas 5:22", "El fruto del Espíritu es: amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza."],
      ["Salmos 145:9", "Bueno es Jehová para todos, y sus misericordias sobre todas sus obras."],
      ["Tito 3:4", "Mas cuando la bondad de Dios nuestro Salvador y su amor para con los hombres se manifestó, nos salvó."],
      ["Romanos 15:14", "Estáis llenos de bondad, llenos de todo conocimiento."],
      ["Salmos 107:8", "Alaben la misericordia de Jehová, y sus maravillas para con los hijos de los hombres."],
      ["Proverbios 19:22", "Lo que hace al hombre de estimar es su misericordia."],
      ["Salmos 23:6", "Ciertamente el bien y la misericordia me seguirán todos los días de mi vida."],
    ],
  },
  {
    id: "misericordia",
    label: "Misericordia",
    keywords: ["misericordia", "compasion", "compasión", "piedad", "clemente", "clemencia"],
    message: "La misericordia de Dios es nueva cada mañana; su fidelidad no tiene fin.",
    verses: [
      ["Lamentaciones 3:22", "Las misericordias de Jehová no se han acabado; porque no faltaron sus bondades. Nuevas son cada mañana; grande es tu fidelidad."],
      ["Salmos 103:8", "Misericordioso y clemente es Jehová; lento para la ira, y grande en misericordia."],
      ["Efesios 2:4", "Mas Dios, que es rico en misericordia, por su mucho amor con que nos amó, nos dio vida juntamente con Cristo."],
      ["Lucas 6:36", "Sed pues misericordiosos, como también vuestro Padre es misericordioso."],
      ["Miqueas 7:18", "¿Qué Dios como tú, que perdona la maldad y olvida el pecado? se deleita en misericordia."],
      ["1 Pedro 1:3", "Según su grande misericordia nos regeneró para una esperanza viva."],
      ["Salmos 136:26", "Alabad al Dios de los cielos: Porque para siempre es su misericordia."],
      ["Hebreos 4:16", "Acerquémonos pues confiadamente al trono de la gracia, para alcanzar misericordia."],
    ],
  },
  {
    id: "renovacion",
    label: "Renovación",
    keywords: ["renovacion", "renovación", "nuevo", "nueva", "transformar", "cambiar", "cambio", "comienzo", "empezar"],
    message: "En Cristo todo es nuevo; Él puede renovar tu corazón y tu vida.",
    verses: [
      ["2 Corintios 5:17", "De modo que si alguno está en Cristo, nueva criatura es: las cosas viejas pasaron; he aquí, todas son hechas nuevas."],
      ["Romanos 12:2", "Transformaos por la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios."],
      ["2 Corintios 4:16", "Aunque este nuestro hombre exterior se va corrompiendo, el interior no obstante se renueva de día en día."],
      ["Isaías 43:19", "He aquí que yo hago nuevas cosas; y antes que salgan á luz, yo os las haré notorias."],
      ["Ezequiel 36:26", "Os daré un corazón nuevo, y pondré dentro de vosotros un espíritu nuevo."],
      ["Salmos 51:10", "Crea en mí, oh Dios, un corazón limpio; y renueva un espíritu recto dentro de mí."],
      ["Tito 3:5", "Nos salvó, por el lavamiento de la regeneración y de la renovación del Espíritu Santo."],
      ["Isaías 40:31", "Los que esperan á Jehová tendrán nuevas fuerzas; levantarán alas como las águilas."],
    ],
  },
  {
    id: "fortaleza_espiritual",
    label: "Fortaleza espiritual",
    keywords: ["espiritu", "espíritu", "espiritual", "oracion", "ayuno", "vida espiritual", "animo espiritual"],
    message: "La fortaleza espiritual viene de la comunión con Dios, no del esfuerzo propio.",
    verses: [
      ["Efesios 6:10", "Fortaleceos en el Señor, y en el poder de su fuerza."],
      ["Efesios 3:16", "Para que os dé, conforme á las riquezas de su gloria, el ser fortalecidos con poder en el hombre interior por su Espíritu."],
      ["Filipenses 4:13", "Todo lo puedo en Cristo que me fortalece."],
      ["2 Corintios 12:9", "Mi potencia en la flaqueza se perfecciona. De buena gana me gloriaré en mis flaquezas, para que repose sobre mí la potencia de Cristo."],
      ["Josué 1:9", "Esfuérzate y sé valiente; no temas, ni desmayes; porque Jehová tu Dios será contigo."],
      ["Salmos 73:26", "Mi carne y mi corazón desfallecen: mas la roca de mi corazón y mi porción es Dios para siempre."],
      ["Zacarías 4:6", "No con ejército, ni con fuerza, sino con mi Espíritu, dice Jehová de los ejércitos."],
      ["Isaías 30:15", "En quietud y en confianza será vuestra fortaleza."],
    ],
  },
  {
    id: "luz",
    label: "Luz",
    keywords: ["luz", "tinieblas", "oscuridad", "brillar", "iluminar", "guiar", "camino"],
    message: "Dios es luz; en Él no hay tinieblas. Él ilumina tu camino.",
    verses: [
      ["Juan 8:12", "Yo soy la luz del mundo; el que me sigue no andará en tinieblas, sino que tendrá la lumbre de la vida."],
      ["Salmos 27:1", "Jehová es mi luz y mi salvación: ¿de quién temeré?"],
      ["Salmos 119:105", "Lámpara es á mis pies tu palabra, y lumbrera á mi camino."],
      ["Proverbios 4:18", "La senda de los justos es como la luz de la aurora, que va en aumento hasta que el día es perfecto."],
      ["Isaías 9:2", "El pueblo que andaba en tinieblas vio grande luz."],
      ["1 Juan 1:7", "Si anduviéremos en luz, como él está en luz, tenemos comunión entre nosotros."],
      ["2 Corintios 4:6", "Dios mandó que de las tinieblas resplandeciese la luz, y resplandeció en nuestros corazones."],
      ["Mateo 5:14", "Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no puede esconderse."],
    ],
  },
  {
    id: "verdad",
    label: "Verdad",
    keywords: ["verdad", "mentira", "engano", "engaño", "confusion", "confusión", "certeza"],
    message: "La verdad de Dios libera; su Palabra es lámpara y guía.",
    verses: [
      ["Juan 8:32", "Y conoceréis la verdad, y la verdad os hará libres."],
      ["Juan 14:6", "Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí."],
      ["Juan 17:17", "Santifícalos en tu verdad; tu palabra es verdad."],
      ["Salmos 119:160", "El principio de tu palabra es verdad; y cada uno de los juicios de tu justicia es para siempre."],
      ["Efesios 4:15", "Siguiendo la verdad en amor, crezcamos en todo en aquel que es la cabeza, Cristo."],
      ["3 Juan 1:4", "No tengo yo mayor gozo que éste, que oiga que mis hijos andan en la verdad."],
      ["Proverbios 12:17", "El que habla verdad declara justicia."],
      ["Salmos 43:3", "Envía tu luz y tu verdad; éstas me guiarán."],
    ],
  },
  {
    id: "libertad",
    label: "Libertad",
    keywords: ["libertad", "libre", "atado", "atada", "prision", "prisión", "opresion", "opresión", "adicion", "adicción"],
    message: "Cristo vino a liberar al cautivo; en Él hay libertad verdadera.",
    verses: [
      ["Juan 8:36", "Si el Hijo os libertare, seréis verdaderamente libres."],
      ["Gálatas 5:1", "Estad pues firmes en la libertad con que Cristo nos hizo libres."],
      ["Romanos 8:2", "La ley del Espíritu de vida en Cristo Jesús me ha librado de la ley del pecado y de la muerte."],
      ["2 Corintios 3:17", "Donde está el Espíritu del Señor, allí hay libertad."],
      ["Isaías 61:1", "Me ungió Jehová: hame enviado á predicar buenas nuevas á los abatidos, á publicar libertad á los cautivos."],
      ["Salmos 119:45", "Y andaré en libertad, porque busqué tus mandamientos."],
      ["Gálatas 5:13", "Á libertad fuisteis llamados; sino servíos por el amor los unos á los otros."],
      ["Lucas 4:18", "El Espíritu del Señor está sobre mí; á publicar libertad á los cautivos."],
    ],
  },
  {
    id: "gozo",
    label: "Gozo",
    keywords: ["gozo", "gozar", "gozoso", "deleite", "jubilo", "júbilo", "contentamiento"],
    message: "El gozo del Señor es tu fortaleza; no depende de circunstancias sino de su presencia.",
    verses: [
      ["Salmos 16:11", "En tu presencia hay hartura de gozos; á tu diestra hay deleites para siempre."],
      ["Habacuc 3:18", "Con todo, yo me alegraré en Jehová, y me gozaré en el Dios de mi salvación."],
      ["Juan 16:24", "Pedid, y recibiréis, para que vuestro gozo sea cumplido."],
      ["Romanos 15:13", "El Dios de esperanza os llene de todo gozo y paz en el creer."],
      ["Salmos 126:5", "Los que sembraron con lágrimas, con regocijo segarán."],
      ["Nehemías 8:10", "El gozo de Jehová es vuestra fortaleza."],
      ["Salmos 30:5", "Por la tarde durará el lloro, y á la mañana vendrá la alegría."],
      ["Filipenses 4:4", "Alegraos en el Señor siempre: otra vez digo que os alegréis."],
    ],
  },
  {
    id: "compasion",
    label: "Compasión",
    keywords: ["compasion", "compasión", "lastima", "lástima", "ternura", "empatia", "empatía", "sentir por"],
    message: "Dios se compadece de sus hijos como un padre de sus pequeños.",
    verses: [
      ["Salmos 103:13", "Como el padre se compadece de los hijos, se compadece Jehová de los que le temen."],
      ["Isaías 49:15", "¿Olvidará la mujer su hijo que amamanta? Aunque éstas olvidaran, yo nunca me olvidaré de ti."],
      ["Colosenses 3:12", "Vestíos de entrañas de misericordia, de benignidad, de humildad, de mansedumbre, de longanimidad."],
      ["Zacarías 7:9", "Juzgad conforme á la verdad, y haced misericordia y compasión cada cual con su hermano."],
      ["1 Pedro 3:8", "Sed todos de un mismo ánimo, compasivos, amándoos fraternalmente, misericordiosos, amigables."],
      ["Mateo 9:36", "Y viendo las gentes, tuvo compasión de ellas; porque estaban cansadas y tendidas como ovejas que no tienen pastor."],
      ["Lucas 6:36", "Sed pues misericordiosos, como también vuestro Padre es misericordioso."],
      ["Efesios 4:32", "Sed benignos unos con otros, misericordiosos, perdonándoos unos á otros."],
    ],
  },
  {
    id: "esperanza_dificil",
    label: "Esperanza en tiempos difíciles",
    keywords: ["tribulacion", "tribulación", "prueba", "dificil", "difícil", "crisis", "problema grave", "situacion dificil"],
    message: "En los momentos más oscuros, Dios está obrando para tu bien.",
    verses: [
      ["Romanos 8:28", "Y sabemos que á los que aman á Dios, todas las cosas les ayudan á bien."],
      ["Jeremías 29:11", "Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz y no de mal."],
      ["2 Corintios 4:8", "En todo somos atribulados, mas no angustiados; en apuros, mas no desesperados; perseguidos, mas no desamparados; derribados, mas no destruídos."],
      ["Nahum 1:7", "Jehová es bueno, fortaleza en el día de la angustia; y conoce á los que en él esperan."],
      ["Salmos 34:19", "Muchas son las aflicciones del justo; mas de todas ellas le librará Jehová."],
      ["Romanos 5:3", "Nos gloriamos en las tribulaciones; sabiendo que la tribulación obra la paciencia; y la paciencia, la prueba; y la prueba, la esperanza."],
      ["Santiago 1:2", "Tened por sumo gozo cuando cayereis en diversas tentaciones; sabiendo que la prueba de vuestra fe obra paciencia."],
      ["Salmos 46:1", "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones."],
    ],
  },
  {
    id: "redencion",
    label: "Redención",
    keywords: ["redencion", "redención", "redimido", "rescatar", "comprado", "precio"],
    message: "Fuiste redimido por la sangre de Cristo; eres de inmenso valor para Dios.",
    verses: [
      ["Colosenses 1:14", "En quien tenemos redención por su sangre, el perdón de los pecados."],
      ["Efesios 1:7", "En quien tenemos redención por su sangre, el perdón de los pecados según las riquezas de su gracia."],
      ["Isaías 44:22", "Yo desvanecí como nube tus transgresiones, y como niebla tus pecados: vuélvete á mí, porque yo te redimí."],
      ["Isaías 43:1", "No temas, porque yo te redimí; te puse nombre, mío eres tú."],
      ["Salmos 130:7", "En Jehová hay misericordia, y abundante redención con él."],
      ["Romanos 3:24", "Siendo justificados gratuitamente por su gracia, por la redención que es en Cristo Jesús."],
      ["Gálatas 3:13", "Cristo nos redimió de la maldición de la ley, hecho por nosotros maldición."],
      ["1 Pedro 1:18", "Fuisteis rescatados, no con cosas corruptibles, sino con la sangre preciosa de Cristo."],
    ],
  },
  {
    id: "santidad",
    label: "Santidad",
    keywords: ["santidad", "santo", "consagrado", "puro", "pureza", "santificar", "limpio", "limpieza"],
    message: "Dios nos llama a ser santos; su Espíritu nos capacita para ello.",
    verses: [
      ["1 Pedro 1:15", "Como aquel que os ha llamado es santo, sed también vosotros santos en toda vuestra manera de vivir."],
      ["Levítico 11:44", "Yo soy Jehová vuestro Dios: vosotros pues os santificaréis, y seréis santos, porque yo soy santo."],
      ["Hebreos 12:14", "Seguid la paz con todos, y la santidad, sin la cual nadie verá al Señor."],
      ["Romanos 6:22", "Librados del pecado, y hechos siervos para Dios, tenéis por vuestro fruto la santificación."],
      ["1 Tesalonicenses 4:7", "No nos ha llamado Dios á impureza, sino á santificación."],
      ["2 Corintios 7:1", "Limpiémonos de toda inmundicia de carne y de espíritu, perfeccionando la santificación en el temor de Dios."],
      ["Salmos 51:10", "Crea en mí, oh Dios, un corazón limpio; y renueva un espíritu recto dentro de mí."],
      ["Efesios 4:24", "Vestíos del nuevo hombre, creado según Dios en la justicia y santidad de la verdad."],
    ],
  },
  {
    id: "servicio",
    label: "Servicio",
    keywords: ["servicio", "servir", "ayudar", "ministerio", "dar", "generoso", "prójimo"],
    message: "Servir a otros es servir a Cristo; en el dar se encuentra la mayor riqueza.",
    verses: [
      ["Marcos 10:45", "El Hijo del hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos."],
      ["Gálatas 5:13", "Servíos por el amor los unos á los otros."],
      ["1 Pedro 4:10", "Cada uno según el don que ha recibido, minístrelo á los otros, como buenos dispensadores de las diferentes gracias de Dios."],
      ["Mateo 25:40", "En cuanto lo hicisteis á uno de estos mis hermanos pequeños, á mí lo hicisteis."],
      ["Josué 24:15", "Yo y mi casa serviremos á Jehová."],
      ["Lucas 22:27", "Yo estoy entre vosotros como el que sirve."],
      ["Efesios 6:7", "Con benevolencia sirviendo, como al Señor y no á los hombres."],
      ["Romanos 12:11", "En lo que requiere diligencia, no perezosos; fervientes en espíritu, sirviendo al Señor."],
    ],
  },
  {
    id: "unidad",
    label: "Unidad",
    keywords: ["unidad", "division", "división", "discordia", "pelea", "conflicto", "hermano", "reconciliar"],
    message: "Dios ama la unidad entre hermanos; es reflejo del amor de Cristo.",
    verses: [
      ["Salmos 133:1", "¡Mirad cuán bueno y cuán delicioso es habitar los hermanos en unión!"],
      ["Efesios 4:3", "Solícitos en guardar la unidad del Espíritu en el vínculo de la paz."],
      ["Juan 17:21", "Para que todos sean una cosa; como tú, oh Padre, en mí, y yo en ti."],
      ["1 Corintios 1:10", "Habléis todos una misma cosa, y no haya entre vosotros disensiones."],
      ["Colosenses 3:14", "Y sobre todas estas cosas, el amor, que es el vínculo de la perfección."],
      ["Filipenses 2:2", "Que tengáis un mismo sentir, teniendo un mismo amor, unidos de alma."],
      ["Romanos 15:5", "El Dios de la paciencia y de la consolación os dé que seáis de un mismo sentir los unos con los otros."],
      ["Romanos 12:16", "Unánimes entre vosotros; no altivos, sino acomodándoos á los humildes."],
    ],
  },
  {
    id: "perdon_reconciliacion",
    label: "Perdón y reconciliación",
    keywords: ["reconciliar", "reconciliacion", "reconciliación", "restaurar", "relacion rota", "relación", "enemistad"],
    message: "Dios reconcilió al mundo consigo en Cristo; Él puede restaurar toda relación.",
    verses: [
      ["Efesios 4:32", "Sed benignos unos con otros, misericordiosos, perdonándoos unos á otros, como también Dios os perdonó á vosotros en Cristo."],
      ["Colosenses 3:13", "Sufriéndoos los unos á los otros, y perdonándoos unos á otros: de la manera que Cristo os perdonó, así también hacedlo vosotros."],
      ["Mateo 5:24", "Deja allí tu presente delante del altar, y ve, reconcíliate primero con tu hermano."],
      ["2 Corintios 5:18", "Dios nos reconcilió consigo mismo por Cristo, y nos dió el ministerio de la reconciliación."],
      ["Mateo 18:22", "Jesús le dijo: No te digo hasta siete, sino hasta setenta veces siete."],
      ["Marcos 11:25", "Cuando estéis orando, perdonad, si tuviéreis algo contra alguno."],
      ["Romanos 5:10", "Siendo enemigos, fuimos reconciliados con Dios por la muerte de su Hijo."],
      ["Lucas 15:20", "Y levantándose, vino á su padre. Y cuando aún estaba lejos, le vió su padre, y fué movido á misericordia."],
    ],
  },
  {
    id: "confianza_dios",
    label: "Confianza en Dios",
    keywords: ["confiar en dios", "confío en dios", "fiar", "fidelidad de dios", "no entiendo", "no comprendo", "plan de dios"],
    message: "Aunque no entiendas el camino, puedes confiar en quien te guía.",
    verses: [
      ["Proverbios 3:5", "Confía en Jehová de todo tu corazón, y no te apoyes en tu propia prudencia."],
      ["Salmos 37:5", "Encomienda á Jehová tu camino, y espera en él; y él hará."],
      ["Jeremías 17:7", "Bendito el varón que confía en Jehová, y cuya confianza es Jehová."],
      ["Isaías 26:4", "Confiad en Jehová para siempre; porque en Jehová el Señor está la fortaleza de los siglos."],
      ["Salmos 9:10", "En ti confiarán los que conocen tu nombre; por cuanto no desamparaste á los que te buscaron."],
      ["Nahum 1:7", "Jehová es bueno, fortaleza en el día de la angustia; y conoce á los que en él esperan."],
      ["Salmos 56:3", "El día que temo, yo en ti confío."],
      ["Salmos 62:8", "Esperad en él en todo tiempo, oh pueblos: Dios es nuestro refugio."],
    ],
  },
];

function norm(t: string): string {
  return t.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
}

export function detectCategory(text: string): string {
  const n = norm(text);
  for (const cat of CATEGORIES) {
    for (const kw of cat.keywords) {
      if (n.includes(norm(kw))) return cat.id;
    }
  }
  return "esperanza";
}

export function findVerse(text: string): VerseResult {
  const catId = detectCategory(text);
  const cat = CATEGORIES.find((c) => c.id === catId)!;
  const n = norm(text);
  const words = n.split(/\s+/).filter((w) => w.length > 3);
  let best = cat.verses[Math.floor(Math.random() * cat.verses.length)];
  let bestScore = -1;
  for (const v of cat.verses) {
    const vn = norm(v[1]);
    const score = words.reduce((s, w) => s + (vn.includes(w) ? 1 : 0), 0);
    if (score > bestScore) {
      bestScore = score;
      best = v;
    }
  }
  return {
    detected_category: cat.label,
    message: cat.message,
    verse_reference: best[0],
    verse_text: best[1],
  };
}

export function randomVerse(): VerseResult {
  const cat = CATEGORIES[Math.floor(Math.random() * CATEGORIES.length)];
  const v = cat.verses[Math.floor(Math.random() * cat.verses.length)];
  return {
    detected_category: cat.label,
    message: cat.message,
    verse_reference: v[0],
    verse_text: v[1],
  };
}

export function getAllCategories(): { id: string; label: string; count: number }[] {
  return CATEGORIES.map((c) => ({ id: c.id, label: c.label, count: c.verses.length }));
}
