import json, sys

categorias = ["Confianza","Dios","Amor","Fe","Esperanza","Perdón","Salvación","Gracia","Paz","Justicia","Sabiduría","Oración","Alabanza","Misericordia","Fortaleza","Humildad","Obediencia","Santificación","Redención","Gloria","Poder","Vida","Luz","Verdad","Juicio","Pecado","Arrepentimiento","Bendición","Profecía","Milagros","Resurrección","Eternidad","Reino","Sacrificio","Paz interior","Esperanza viva","Fe activa","Amor incondicional","Gracia divina","Perdón eterno"]

kw = {
    "Confianza":["confia","segur","refugi","amparo","escud","espero en","esperad"],
    "Dios":["dios","señor","jehová","jehova","padre","creador","altísimo","todopoderoso"],
    "Amor":["amor","ama","caridad","benignidad","afecto","amad"],
    "Fe":["fe ","creer","creyen","fiel","fidelidad","creed","cre"],
    "Esperanza":["esperan","espera","aguarda","aguardad"],
    "Perdón":["perdó","perdon","perdonad","remisión","remision","perdonar"],
    "Salvación":["salva","salvo","redimi","liberación","liberacion","rescata"],
    "Gracia":["gracia","don de","dádiva","dadiva"],
    "Paz":["paz ","paz.","pazcos","pacifico"],
    "Justicia":["justicia","justo","rectitud","equidad","recto"],
    "Sabiduría":["sabiduría","sabio","entendimiento","prudencia","conocimiento","inteligencia"],
    "Oración":["oración","orar","orad","rogad","súplica","suplica","clama","pedid","orar","intercede"],
    "Alabanza":["alabanza","alaba","glorifica","bendecid","gracias","gozo","cántico","cantico","cantad","exalt"],
    "Misericordia":["misericordia","compasión","compasion","piadoso","bondad","compasiv"],
    "Fortaleza":["fortaleza","fuerza","esfuerzo","fortalec","potencia","vigor","valiente","esforzaos"],
    "Humildad":["humildad","humilla","manso","humilde","mansedumbre","quebrantado"],
    "Obediencia":["obede","mandamiento","guardar","cumplir","precept","guardan","guardaréis"],
    "Santificación":["santi","puro","limpio","santo","consagra","apartad"],
    "Redención":["redención","redencion","rescata","comprado","redimido"],
    "Gloria":["gloria","glorificad","honra","magnificencia","majestad","glorioso"],
    "Poder":["poder","poderoso","omnipotente","todopoderoso","potestad","potente"],
    "Vida":["vida","vivir","vivo","vivificar","vivirá"],
    "Luz":["luz ","luz,","luz.","lumbre","alumbra","resplande","ilumina"],
    "Verdad":["verdad","verdadero","certeza","veraz"],
    "Juicio":["juicio","juzgar","tribunal","condenación","sentencia","juzgará"],
    "Pecado":["pecado","maldad","transgresión","iniquidad","rebeld","mal ","maldades"],
    "Arrepentimiento":["arrepent","convertíos","convertios","vuélvete","vuelvete","volveos","volvéos"],
    "Bendición":["bendición","bendicion","bienaventurado","bendito","prospera"],
    "Profecía":["profec","profeta","anuncia","vendrá","vendra","acontecer","predicció"],
    "Milagros":["milagro","maravilla","portento","señal","prodigio"],
    "Resurrección":["resurrecc","resucit","levantó","levanto de los muertos"],
    "Eternidad":["eterno","eterna","para siempre","perpetuo","jamás","jamas","sempiterno"],
    "Reino":["reino","rey ","rey,","trono","dominio","reinar","reinará"],
    "Sacrificio":["sacrificio","ofrenda","holocausto","entregó su vida","sangre"],
    "Paz interior":["reposa","consuela","no temas","no se turbe","tranquila","quieto","descanso"],
    "Esperanza viva":["esperanza viva","nueva criatura","nueva vida","renovar","restaura","renovados"],
    "Fe activa":["obras","frutos","hacer bien","actuar","actúa","actua","no nos cansemos"],
    "Amor incondicional":["nunca te dejará","nunca me olvidar","siempre te amaré","amor eterno","cuanto está"],
    "Gracia divina":["gracia divina","don inmereci","gracia de dios","libre gracia"],
    "Perdón eterno":["perdonará","perdonara","borrado","olvidado","nunca más recordar","nunca mas"]
}

versos = [
{"r":"Génesis 1:1","t":"En el principio crió Dios los cielos y la tierra."},
{"r":"Génesis 1:3","t":"Y dijo Dios: Sea la luz; y fué la luz."},
{"r":"Génesis 1:26","t":"Y dijo Dios: Hagamos al hombre á nuestra imagen, conforme á nuestra semejanza."},
{"r":"Génesis 1:31","t":"Y vió Dios todo lo que había hecho, y he aquí que era bueno en gran manera."},
{"r":"Génesis 2:7","t":"Entonces Jehová Dios formó al hombre del polvo de la tierra, y sopló en su nariz aliento de vida; y fué el hombre en alma viviente."},
{"r":"Génesis 2:18","t":"Y dijo Jehová Dios: No es bueno que el hombre esté solo; le haré ayuda idónea para él."},
{"r":"Génesis 3:15","t":"Y pondré enemistad entre ti y la mujer, y entre tu simiente y la simiente suya; ésta te herirá en la cabeza, y tú le herirás en el calcañar."},
{"r":"Génesis 6:8","t":"Pero Noé halló gracia en los ojos de Jehová."},
{"r":"Génesis 12:2","t":"Y haré de ti una nación grande, y te bendeciré, y engrandeceré tu nombre; y serás bendición."},
{"r":"Génesis 15:6","t":"Y creyó á Dios, y le fué contado por justicia."},
{"r":"Génesis 17:1","t":"Yo soy el Dios Todopoderoso; anda delante de mí, y sé perfecto."},
{"r":"Génesis 18:14","t":"¿Hay alguna cosa difícil para Dios?"},
{"r":"Génesis 22:8","t":"Dios se proveerá de cordero para el holocausto, hijo mío."},
{"r":"Génesis 22:14","t":"Y llamó Abraham el nombre de aquel lugar, Jehová-jireh. Por tanto se dice hoy: En el monte de Jehová será provisto."},
{"r":"Génesis 28:15","t":"He aquí, yo estoy contigo, y te guardaré por dondequiera que fueres."},
{"r":"Génesis 50:20","t":"Vosotros pensasteis mal contra mí, mas Dios lo encaminó á bien."},
{"r":"Éxodo 3:14","t":"Y respondió Dios á Moisés: YO SOY EL QUE SOY."},
{"r":"Éxodo 14:14","t":"Jehová peleará por vosotros, y vosotros estaréis tranquilos."},
{"r":"Éxodo 15:2","t":"Jehová es mi fortaleza y mi cántico, y ha sido mi salvación."},
{"r":"Éxodo 15:11","t":"¿Quién como tú, oh Jehová, entre los dioses? ¿Quién como tú, magnífico en santidad, terrible en maravillosas hazañas, hacedor de prodigios?"},
{"r":"Éxodo 20:2","t":"Yo soy Jehová tu Dios, que te saqué de la tierra de Egipto, de casa de servidumbre."},
{"r":"Éxodo 20:3","t":"No tendrás dioses ajenos delante de mí."},
{"r":"Éxodo 33:14","t":"Mi presencia irá contigo, y te daré descanso."},
{"r":"Éxodo 34:6","t":"¡Jehová! ¡Jehová! fuerte, misericordioso y piadoso; tardo para la ira, y grande en misericordia y verdad."},
{"r":"Levítico 19:18","t":"Amarás á tu prójimo como á ti mismo."},
{"r":"Levítico 20:26","t":"Habéis de serme santos, porque yo Jehová soy santo, y os he apartado de los pueblos para que seáis míos."},
{"r":"Números 6:24","t":"Jehová te bendiga, y te guarde."},
{"r":"Números 6:25","t":"Jehová haga resplandecer su rostro sobre ti, y tenga de ti misericordia."},
{"r":"Números 6:26","t":"Jehová alce á ti su rostro, y ponga en ti paz."},
{"r":"Números 23:19","t":"Dios no es hombre para que mienta, ni hijo de hombre para que se arrepienta."},
{"r":"Deuteronomio 4:7","t":"¿Qué gente hay tan grande, que tenga los dioses tan cercanos á él, como lo está Jehová nuestro Dios en todo cuanto le pedimos?"},
{"r":"Deuteronomio 4:29","t":"Mas si desde allí buscareis á Jehová tu Dios, lo hallarás, si lo buscares de todo tu corazón y de toda tu alma."},
{"r":"Deuteronomio 6:4","t":"Oye, Israel: Jehová nuestro Dios, Jehová uno es."},
{"r":"Deuteronomio 6:5","t":"Y amarás á Jehová tu Dios de todo tu corazón, y de toda tu alma, y con toda tu fuerza."},
{"r":"Deuteronomio 7:9","t":"Conoce pues que Jehová tu Dios es Dios fiel, que guarda el pacto y la misericordia á los que le aman y guardan sus mandamientos, hasta mil generaciones."},
{"r":"Deuteronomio 8:3","t":"No sólo de pan vivirá el hombre, mas de todo lo que sale de la boca de Jehová vivirá el hombre."},
{"r":"Deuteronomio 28:2","t":"Y vendrán sobre ti todas estas bendiciones, y te alcanzarán, si oyeres la voz de Jehová tu Dios."},
{"r":"Deuteronomio 29:29","t":"Las cosas secretas pertenecen á Jehová nuestro Dios; mas las reveladas son para nosotros y para nuestros hijos."},
{"r":"Deuteronomio 30:19","t":"Os pongo hoy por testigos al cielo y á la tierra, que os he puesto delante la vida y la muerte, la bendición y la maldición: escoge pues la vida."},
{"r":"Deuteronomio 31:6","t":"Esforzaos y animaos: no temáis, ni tengáis miedo de ellos; que Jehová tu Dios es el que va contigo: no te dejará, ni te desamparará."},
{"r":"Josué 1:8","t":"Nunca se apartará de tu boca este libro de la ley, sino que de día y de noche meditarás en él."},
{"r":"Josué 1:9","t":"¿No te mandé yo que te esforzases y fueses valiente? No temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que fueres."},
{"r":"Josué 24:15","t":"Yo y mi casa serviremos á Jehová."},
{"r":"Jueces 6:12","t":"Jehová está contigo, varón esforzado y valiente."},
{"r":"Rut 1:16","t":"Donde tú murieres, moriré yo, y allí seré sepultada. Así me haga Jehová, y así me añada, que sólo la muerte hará separación entre nosotras."},
{"r":"1 Samuel 2:2","t":"No hay santo como Jehová; porque no hay ninguno fuera de ti, y no hay refugio como el Dios nuestro."},
{"r":"1 Samuel 15:22","t":"Ciertamente el obedecer es mejor que los sacrificios, y el prestar atención que la grosura de los carneros."},
{"r":"1 Samuel 16:7","t":"Jehová no mira lo que mira el hombre: que el hombre mira lo que está delante de sus ojos, pero Jehová mira el corazón."},
{"r":"2 Samuel 7:22","t":"Por tanto tú te has engrandecido, Jehová Dios: por cuanto no hay como tú, ni hay Dios fuera de ti."},
{"r":"2 Samuel 22:2","t":"Jehová es mi roca, y mi fortaleza, y mi libertador."},
{"r":"2 Samuel 22:47","t":"Jehová vive, y bendita sea mi roca, y engrandecida sea la roca de mi salud."},
{"r":"1 Reyes 8:23","t":"Jehová Dios de Israel, no hay Dios como tú, ni arriba en los cielos, ni abajo en la tierra."},
{"r":"1 Reyes 8:56","t":"Bendito sea Jehová, que ha dado paz á su pueblo Israel."},
{"r":"1 Reyes 18:21","t":"¿Hasta cuándo claudicaréis vosotros entre dos pensamientos? Si Jehová es Dios, seguid á Jehová."},
{"r":"2 Reyes 6:16","t":"No tengas miedo; porque más son los que están con nosotros que los que están con ellos."},
{"r":"1 Crónicas 16:8","t":"Glorificad á Jehová, invocad su nombre: dad á conocer sus obras en los pueblos."},
{"r":"1 Crónicas 16:34","t":"Alabad á Jehová, porque él es bueno; porque su misericordia es para siempre."},
{"r":"1 Crónicas 29:11","t":"Tuya es, oh Jehová, la magnificencia y el poder, la gloria, la victoria y el honor; porque todas las cosas que están en los cielos y en la tierra son tuyas."},
{"r":"2 Crónicas 7:14","t":"Si se humillare mi pueblo, sobre el cual mi nombre es invocado, y oraren, y buscaren mi rostro, y se convirtieren de sus malos caminos; entonces yo oiré desde los cielos, y perdonaré sus pecados."},
{"r":"2 Crónicas 20:15","t":"No temáis ni os amedrentéis delante de esta multitud tan grande; porque la batalla no es vuestra, sino de Dios."},
{"r":"2 Crónicas 32:8","t":"Con aquél está el brazo de carne, mas con nosotros está Jehová nuestro Dios para ayudarnos."},
{"r":"Esdras 8:22","t":"La mano de nuestro Dios es para bien sobre todos los que le buscan."},
{"r":"Nehemías 8:10","t":"El gozo de Jehová es vuestra fortaleza."},
{"r":"Nehemías 9:17","t":"Pero tú eres Dios que perdonas, clemente y piadoso, tardo en airarte, y grande en misericordia."},
{"r":"Ester 4:14","t":"¿Y quién sabe si para esta hora has llegado al reino?"},
{"r":"Job 1:21","t":"Jehová dió, y Jehová quitó; sea el nombre de Jehová bendito."},
{"r":"Job 5:17","t":"He aquí, bienaventurado el hombre á quien Dios castiga: por tanto, no menosprecies la corrección del Todopoderoso."},
{"r":"Job 11:7","t":"¿Descubrirás tú los secretos de Dios? ¿Llegarás tú á la perfección del Todopoderoso?"},
{"r":"Job 12:13","t":"Con Dios está la sabiduría y el poder; suyo es el consejo y la inteligencia."},
{"r":"Job 14:14","t":"Si el hombre muriere, ¿volverá á vivir? Todos los días de mi milicia esperaré, hasta que venga mi mudanza."},
{"r":"Job 19:25","t":"Yo sé que mi Redentor vive, y al fin se levantará sobre el polvo."},
{"r":"Job 23:10","t":"Mas él conoce mi camino; me probará, y saldré como el oro."},
{"r":"Job 33:4","t":"El espíritu de Dios me hizo, y el soplo del Omnipotente me dió vida."},
{"r":"Job 38:4","t":"¿Dónde estabas tú cuando yo fundaba la tierra? Házmelo saber, si tienes inteligencia."},
{"r":"Job 42:2","t":"Yo conozco que todo lo puedes, y que no hay pensamiento que se esconda de ti."},
{"r":"Salmos 1:1","t":"Bienaventurado el varón que no anduvo en consejo de malos, ni estuvo en camino de pecadores, ni en silla de escarnecedores se ha sentado."},
{"r":"Salmos 1:2","t":"Sino que en la ley de Jehová está su delicia, y en su ley medita de día y de noche."},
{"r":"Salmos 1:3","t":"Será como el árbol plantado junto á riberas de aguas, que dará su fruto en su tiempo."},
{"r":"Salmos 2:8","t":"Pídeme, y daréte las gentes por heredad, y por posesión tuya los términos de la tierra."},
{"r":"Salmos 3:3","t":"Mas tú, Jehová, eres escudo alrededor de mí; mi gloria, y el que levanta mi cabeza."},
{"r":"Salmos 4:8","t":"En paz me acostaré asimismo, y dormiré; porque solo tú, Jehová, me haces vivir confiado."},
{"r":"Salmos 5:3","t":"Jehová, de mañana oirás mi voz; de mañana me presentaré delante de ti, y esperaré."},
{"r":"Salmos 8:1","t":"¡Oh Jehová, Señor nuestro, cuán grande es tu nombre en toda la tierra!"},
{"r":"Salmos 9:1","t":"Te alabaré, oh Jehová, con todo mi corazón; contaré todas tus maravillas."},
{"r":"Salmos 9:9","t":"Y Jehová será refugio del pobre, refugio para el tiempo de angustia."},
{"r":"Salmos 9:10","t":"En ti confiarán los que conocen tu nombre; por cuanto no desamparaste á los que te buscaron."},
{"r":"Salmos 14:1","t":"Dice el necio en su corazón: No hay Dios."},
{"r":"Salmos 16:11","t":"Me mostrarás la senda de la vida; en tu presencia hay hartura de alegrías; delicias á tu diestra para siempre."},
{"r":"Salmos 17:8","t":"Guárdame como la niña del ojo; escóndeme bajo la sombra de tus alas."},
{"r":"Salmos 18:2","t":"Jehová, roca mía y fortaleza mía, y mi libertador; Dios mío, fortaleza mía, en él confiaré; mi escudo, y el fuerte de mi salud, mi alto refugio."},
{"r":"Salmos 18:30","t":"En cuanto á Dios, perfecto es su camino, y acrisolada la palabra de Jehová; escudo es á todos los que en él esperan."},
{"r":"Salmos 18:32","t":"Dios es el que me ciñe de fortaleza, y quien despeja mi camino."},
{"r":"Salmos 19:1","t":"Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos."},
{"r":"Salmos 19:7","t":"La ley de Jehová es perfecta, que vuelve el alma: el testimonio de Jehová es fiel, que hace sabio al simple."},
{"r":"Salmos 19:14","t":"Sean gratos los dichos de mi boca y la meditación de mi corazón delante de ti, oh Jehová, roca mía, y redentor mío."},
{"r":"Salmos 22:1","t":"Dios mío, Dios mío, ¿por qué me has desamparado?"},
{"r":"Salmos 22:24","t":"Porque no menospreció ni abominó la aflicción del pobre, ni de él escondió su rostro; sino que cuando clamó á él, oyóle."},
{"r":"Salmos 23:1","t":"Jehová es mi pastor; nada me faltará."},
{"r":"Salmos 23:2","t":"En lugares de delicados pastos me hará yacer: junto á aguas de reposo me pastoreará."},
{"r":"Salmos 23:3","t":"Confortará mi alma; guiaráme por sendas de justicia por amor de su nombre."},
{"r":"Salmos 23:4","t":"Aunque ande en valle de sombra de muerte, no temeré mal alguno; porque tú estarás conmigo: tu vara y tu cayado me infundirán aliento."},
{"r":"Salmos 23:5","t":"Aderezarás mesa delante de mí en presencia de mis enemigos: ungiste mi cabeza con aceite; mi copa está rebosando."},
{"r":"Salmos 23:6","t":"Ciertamente el bien y la misericordia me seguirán todos los días de mi vida; y en la casa de Jehová moraré por largos días."},
{"r":"Salmos 24:1","t":"De Jehová es la tierra y su plenitud; el mundo, y los que en él habitan."},
{"r":"Salmos 25:4","t":"Muéstrame, oh Jehová, tus caminos; enséñame tus sendas."},
{"r":"Salmos 25:5","t":"Encamíname en tu verdad, y enséñame; porque tú eres el Dios de mi salud: en ti he esperado todo el día."},
{"r":"Salmos 27:1","t":"Jehová es mi luz y mi salvación: ¿de quién temeré? Jehová es la fortaleza de mi vida: ¿de quién me receleré?"},
{"r":"Salmos 27:4","t":"Una cosa demandé á Jehová, ésta buscaré; que esté yo en la casa de Jehová todos los días de mi vida."},
{"r":"Salmos 27:10","t":"Aunque mi padre y mi madre me dejaran, con todo, Jehová me recogerá."},
{"r":"Salmos 27:14","t":"Aguarda á Jehová; esfuérzate, y él esforzará tu corazón: aguarda pues á Jehová."},
{"r":"Salmos 28:7","t":"Jehová es mi fortaleza y mi escudo; en él confió mi corazón, y fui ayudado."},
{"r":"Salmos 29:11","t":"Jehová dará fortaleza á su pueblo; Jehová bendecirá á su pueblo con paz."},
{"r":"Salmos 30:2","t":"Jehová Dios mío, á ti clamé, y me sanaste."},
{"r":"Salmos 30:5","t":"Por la tarde durará el lloro, y á la mañana vendrá la alegría."},
{"r":"Salmos 31:3","t":"Porque tú eres mi roca y mi castillo; por tu nombre me guiarás y me encaminarás."},
{"r":"Salmos 31:24","t":"Esforzaos, y aliente vuestro corazón, todos los que esperáis en Jehová."},
{"r":"Salmos 32:5","t":"Mi pecado te declaré, y no encubrí mi iniquidad. Dije: Confesaré mis rebeliones á Jehová; y tú perdonaste la maldad de mi pecado."},
{"r":"Salmos 32:7","t":"Tú eres mi refugio; me guardarás de la angustia; con cánticos de liberación me rodearás."},
{"r":"Salmos 32:8","t":"Te haré entender, y te enseñaré el camino en que debes andar; sobre ti fijaré mis ojos."},
{"r":"Salmos 33:4","t":"Porque recta es la palabra de Jehová, y toda su obra es hecha con fidelidad."},
{"r":"Salmos 33:11","t":"El consejo de Jehová permanecerá para siempre; los pensamientos de su corazón por todas las generaciones."},
{"r":"Salmos 33:18","t":"He aquí el ojo de Jehová sobre los que le temen, sobre los que esperan en su misericordia."},
{"r":"Salmos 34:1","t":"Bendeciré á Jehová en todo tiempo; su alabanza será siempre en mi boca."},
{"r":"Salmos 34:4","t":"Busqué á Jehová, y él me oyó, y libróme de todos mis temores."},
{"r":"Salmos 34:7","t":"El ángel de Jehová acampa alrededor de los que le temen, y los defiende."},
{"r":"Salmos 34:8","t":"Gustad, y ved que Jehová es bueno; bienaventurado el hombre que en él confía."},
{"r":"Salmos 34:17","t":"Claman los justos, y Jehová oye, y los libra de todas sus angustias."},
{"r":"Salmos 34:18","t":"Cercano está Jehová á los quebrantados de corazón; y salvará á los contritos de espíritu."},
{"r":"Salmos 36:7","t":"¡Cuán preciosa, oh Dios, es tu misericordia! Por eso los hijos de los hombres se amparan bajo la sombra de tus alas."},
{"r":"Salmos 37:4","t":"Pon asimismo tu delicia en Jehová, y él te dará las peticiones de tu corazón."},
{"r":"Salmos 37:5","t":"Encomienda á Jehová tu camino, y confía en él; y él hará."},
{"r":"Salmos 37:7","t":"Guarda silencio ante Jehová, y espera en él."},
{"r":"Salmos 37:23","t":"Por Jehová son ordenados los pasos del hombre; y él aprueba su camino."},
{"r":"Salmos 37:25","t":"Fui joven, y he envejecido, y no he visto justo desamparado, ni su simiente que mendigue pan."},
{"r":"Salmos 37:28","t":"Porque Jehová ama la rectitud, y no desampara á sus santos."},
{"r":"Salmos 40:1","t":"Esperando esperé á Jehová; inclinóse á mí, y oyó mi clamor."},
{"r":"Salmos 40:3","t":"Y puso en mi boca cántico nuevo, alabanza á nuestro Dios."},
{"r":"Salmos 42:1","t":"Como el ciervo brama por las corrientes de las aguas, así clama por ti, oh Dios, el alma mía."},
{"r":"Salmos 42:5","t":"¿Por qué te abates, oh alma mía, y te turbas dentro de mí? Espera en Dios; porque aún le tengo que alabar."},
{"r":"Salmos 42:11","t":"¿Por qué te abates, oh alma mía? Espera en Dios; porque aún le tengo que alabar."},
{"r":"Salmos 43:5","t":"¿Por qué te abates, oh alma mía, y por qué te conturbas dentro de mí? Espera en Dios; porque aún le tengo que alabar."},
{"r":"Salmos 46:1","t":"Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones."},
{"r":"Salmos 46:2","t":"Por tanto, no temeremos aunque la tierra sea removida."},
{"r":"Salmos 46:10","t":"Estad quietos, y conoced que yo soy Dios."},
{"r":"Salmos 47:7","t":"Porque Dios es el Rey de toda la tierra; cantad con inteligencia."},
{"r":"Salmos 48:14","t":"Porque este Dios es Dios nuestro eternamente y para siempre; él nos guiará aun hasta la muerte."},
{"r":"Salmos 50:15","t":"E invócame en el día de la angustia: libraréte, y tú me honrarás."},
{"r":"Salmos 51:1","t":"Ten piedad de mí, oh Dios, conforme á tu misericordia; conforme á la multitud de tus piedades borra mis rebeliones."},
{"r":"Salmos 51:2","t":"Lávame más y más de mi maldad, y límpiame de mi pecado."},
{"r":"Salmos 51:7","t":"Purifícame con hisopo, y seré limpio; lávame, y seré emblanquecido más que la nieve."},
{"r":"Salmos 51:10","t":"Crea en mí, oh Dios, un corazón limpio; y renueva un espíritu recto dentro de mí."},
{"r":"Salmos 51:12","t":"Vuélveme el gozo de tu salud, y espíritu noble me sustente."},
{"r":"Salmos 51:17","t":"Los sacrificios de Dios son el espíritu quebrantado; al corazón contrito y humillado no despreciarás tú, oh Dios."},
{"r":"Salmos 55:22","t":"Echa sobre Jehová tu carga, y él te sustentará; no dejará para siempre caído al justo."},
{"r":"Salmos 56:3","t":"El día que temo, yo en ti confío."},
{"r":"Salmos 56:4","t":"En Dios alabaré su palabra; en Dios he confiado; no temeré lo que me pueda hacer el hombre."},
{"r":"Salmos 57:1","t":"Ten misericordia de mí, oh Dios, ten misericordia de mí; porque en ti ha confiado mi alma."},
{"r":"Salmos 62:5","t":"Alma mía, en Dios solamente reposa; porque de él es mi esperanza."},
{"r":"Salmos 62:7","t":"En Dios está mi salvación y mi gloria; en Dios está mi roca fuerte, y mi refugio."},
{"r":"Salmos 62:8","t":"Esperad en él en todo tiempo, oh pueblos; derramad delante de él vuestro corazón: Dios es nuestro refugio."},
{"r":"Salmos 63:1","t":"Dios, Dios mío eres tú; de madrugada te buscaré: mi alma tiene sed de ti."},
{"r":"Salmos 63:3","t":"Porque tu misericordia es mejor que la vida; mis labios te alabarán."},
{"r":"Salmos 66:20","t":"Bendito sea Dios, que no echó de sí mi oración, ni de mí su misericordia."},
{"r":"Salmos 68:5","t":"Padre de los huérfanos y defensor de las viudas es Dios en su santa morada."},
{"r":"Salmos 71:5","t":"Porque tú, oh Señor Jehová, eres mi esperanza, seguridad mía desde mi juventud."},
{"r":"Salmos 72:19","t":"Bendito su nombre glorioso para siempre, y toda la tierra sea llena de su gloria."},
{"r":"Salmos 73:26","t":"Mi carne y mi corazón desfallecen; mas la roca de mi corazón y mi porción es Dios para siempre."},
{"r":"Salmos 84:2","t":"Anhela mi alma y aun ardientemente desea los atrios de Jehová; mi corazón y mi carne cantan al Dios vivo."},
{"r":"Salmos 84:11","t":"Porque sol y escudo es Jehová Dios; gracia y gloria dará Jehová."},
{"r":"Salmos 85:10","t":"La misericordia y la verdad se encontraron; la justicia y la paz se besaron."},
{"r":"Salmos 86:5","t":"Porque tú, Señor, eres bueno y perdonador, y grande en misericordia á todos los que te invocan."},
{"r":"Salmos 86:15","t":"Mas tú, Señor Dios, eres misericordioso y clemente, tardo para la ira, y grande en misericordia y verdad."},
{"r":"Salmos 89:1","t":"Las misericordias de Jehová cantaré perpetuamente; de generación en generación haré notoria tu fidelidad con mi boca."},
{"r":"Salmos 90:1","t":"Señor, tú nos has sido refugio de generación en generación."},
{"r":"Salmos 90:2","t":"Antes que los montes fuesen engendrados, y criases la tierra y el mundo, desde el siglo y hasta el siglo eres tú Dios."},
{"r":"Salmos 91:1","t":"El que habita al abrigo del Altísimo, morará bajo la sombra del Omnipotente."},
{"r":"Salmos 91:2","t":"Diré yo á Jehová: Esperanza mía, y castillo mío; mi Dios, en quien confiaré."},
{"r":"Salmos 91:4","t":"Con sus plumas te cubrirá, y debajo de sus alas estarás seguro; escudo y adarga es su verdad."},
{"r":"Salmos 91:11","t":"Pues que á sus ángeles mandará acerca de ti, que te guarden en todos tus caminos."},
{"r":"Salmos 91:14","t":"Por cuanto en mí ha puesto su voluntad, yo también lo libraré: pondréle en alto, por cuanto ha conocido mi nombre."},
{"r":"Salmos 91:15","t":"Me invocará, y yo le responderé: con él estaré yo en la angustia; lo libraré, y le glorificaré."},
{"r":"Salmos 92:1","t":"Bueno es alabar á Jehová, y cantar salmos á tu nombre, oh Altísimo."},
{"r":"Salmos 94:22","t":"Mas Jehová me ha sido por alto refugio, y mi Dios por roca de mi esperanza."},
{"r":"Salmos 95:6","t":"Venid, adoremos y postrémonos; arrodillémonos delante de Jehová nuestro hacedor."},
{"r":"Salmos 96:3","t":"Proclamad entre las gentes su gloria, en todos los pueblos sus maravillas."},
{"r":"Salmos 100:1","t":"Cantad á Jehová con alegría toda la tierra."},
{"r":"Salmos 100:2","t":"Servid á Jehová con alegría; venid ante su presencia con regocijo."},
{"r":"Salmos 100:3","t":"Reconoced que Jehová es Dios: él nos hizo, y no nosotros á él."},
{"r":"Salmos 100:4","t":"Entrad por sus puertas con alabanza, por sus atrios con alabanza; alabadle, bendecid su nombre."},
{"r":"Salmos 100:5","t":"Porque Jehová es bueno; para siempre es su misericordia, y su verdad por todas las generaciones."},
{"r":"Salmos 102:25","t":"Desde el principio tú fundaste la tierra, y los cielos son obra de tus manos."},
{"r":"Salmos 103:1","t":"Bendice, alma mía, á Jehová, y bendiga todo mi ser su santo nombre."},
{"r":"Salmos 103:2","t":"Bendice, alma mía, á Jehová, y no olvides ninguno de sus beneficios."},
{"r":"Salmos 103:3","t":"El que perdona todas tus iniquidades, el que sana todas tus dolencias."},
{"r":"Salmos 103:8","t":"Misericordioso y clemente es Jehová; lento para la ira, y grande en misericordia."},
{"r":"Salmos 103:10","t":"No ha hecho con nosotros conforme á nuestras iniquidades, ni nos ha pagado conforme á nuestros pecados."},
{"r":"Salmos 103:11","t":"Porque como la altura de los cielos sobre la tierra, engrandeció su misericordia sobre los que le temen."},
{"r":"Salmos 103:12","t":"Cuanto está lejos el oriente del occidente, hizo alejar de nosotros nuestras rebeliones."},
{"r":"Salmos 103:13","t":"Como el padre se compadece de los hijos, se compadece Jehová de los que le temen."},
{"r":"Salmos 104:33","t":"Cantaré á Jehová en mi vida; cantaré salmos á mi Dios mientras viviere."},
{"r":"Salmos 105:1","t":"Alabad á Jehová, invocad su nombre; dad á conocer sus obras en los pueblos."},
{"r":"Salmos 107:1","t":"Alabad á Jehová, porque él es bueno; porque para siempre es su misericordia."},
{"r":"Salmos 107:8","t":"Alaben la misericordia de Jehová, y sus maravillas para con los hijos de los hombres."},
{"r":"Salmos 107:9","t":"Porque sació el alma menesterosa, y llenó de bien el alma hambrienta."},
{"r":"Salmos 112:1","t":"Bienaventurado el hombre que teme á Jehová, y en sus mandamientos se deleita en gran manera."},
{"r":"Salmos 112:7","t":"No tendrá temor de malas nuevas; su corazón está firme, confiado en Jehová."},
{"r":"Salmos 113:3","t":"Desde el nacimiento del sol hasta donde se pone, sea alabado el nombre de Jehová."},
{"r":"Salmos 115:1","t":"No á nosotros, oh Jehová, no á nosotros, sino á tu nombre da gloria."},
{"r":"Salmos 116:1","t":"Amo á Jehová, pues ha oído mi voz y mis súplicas."},
{"r":"Salmos 116:2","t":"Porque ha inclinado á mí su oído; por tanto, le invocaré en todos mis días."},
{"r":"Salmos 117:1","t":"Alabad á Jehová, naciones todas; pueblos todos, alabadle."},
{"r":"Salmos 117:2","t":"Porque ha engrandecido sobre nosotros su misericordia, y la verdad de Jehová es para siempre. Aleluya."},
{"r":"Salmos 118:1","t":"Alabad á Jehová, porque él es bueno; porque para siempre es su misericordia."},
{"r":"Salmos 118:6","t":"Jehová está por mí; no temeré lo que me pueda hacer el hombre."},
{"r":"Salmos 118:8","t":"Mejor es confiar en Jehová que confiar en el hombre."},
{"r":"Salmos 118:14","t":"Mi fortaleza y mi cántico es Jah, y él me ha sido por salud."},
{"r":"Salmos 118:24","t":"Este es el día que hizo Jehová; regocijémonos y alegrémonos en él."},
{"r":"Salmos 118:29","t":"Alabad á Jehová, porque él es bueno; porque para siempre es su misericordia."},
{"r":"Salmos 119:1","t":"Bienaventurados los perfectos de camino, los que andan en la ley de Jehová."},
{"r":"Salmos 119:9","t":"¿Con qué limpiará el joven su camino? Con guardar tu palabra."},
{"r":"Salmos 119:11","t":"En mi corazón he guardado tus dichos, para no pecar contra ti."},
{"r":"Salmos 119:18","t":"Abre mis ojos, y miraré las maravillas de tu ley."},
{"r":"Salmos 119:30","t":"Escogí el camino de la verdad; tus juicios he puesto delante de mí."},
{"r":"Salmos 119:50","t":"Ella es mi consolación en mi aflicción; porque tu dicho me ha vivificado."},
{"r":"Salmos 119:105","t":"Lámpara es á mis pies tu palabra, y lumbrera á mi camino."},
{"r":"Salmos 119:114","t":"Mi escondedero y mi escudo eres tú; en tu palabra he esperado."},
{"r":"Salmos 119:130","t":"El principio de tus palabras alumbra; hace entender á los simples."},
{"r":"Salmos 119:160","t":"El principio de tu palabra es verdad, y eterno es todo juicio de tu justicia."},
{"r":"Salmos 119:165","t":"Mucha paz tienen los que aman tu ley, y no hay para ellos tropiezo."},
{"r":"Salmos 121:1","t":"Alzaré mis ojos á los montes: ¿de dónde vendrá mi socorro?"},
{"r":"Salmos 121:2","t":"Mi socorro viene de Jehová, que hizo los cielos y la tierra."},
{"r":"Salmos 121:3","t":"No dará tu pie al resbaladero, ni se dormirá el que te guarda."},
{"r":"Salmos 121:7","t":"Jehová te guardará de todo mal; él guardará tu alma."},
{"r":"Salmos 121:8","t":"Jehová guardará tu salida y tu entrada, desde ahora y para siempre."},
{"r":"Salmos 122:1","t":"Yo me alegré con los que me decían: A la casa de Jehová iremos."},
{"r":"Salmos 126:5","t":"Los que sembraron con lágrimas, con regocijo segarán."},
{"r":"Salmos 126:6","t":"Irá andando y llorando el que lleva la preciosa simiente; mas volverá á venir con regocijo, trayendo sus manojos."},
{"r":"Salmos 127:1","t":"Si Jehová no edificare la casa, en vano trabajan los que la edifican."},
{"r":"Salmos 127:3","t":"He aquí, herencia de Jehová son los hijos; cosa de estima el fruto del vientre."},
{"r":"Salmos 128:1","t":"Bienaventurado todo aquel que teme á Jehová, que anda en sus caminos."},
{"r":"Salmos 130:3","t":"Jah, si mirares á los pecados, ¿quién, oh Señor, podrá mantenerse?"},
{"r":"Salmos 130:4","t":"Pero en ti hay perdón, para que seas reverenciado."},
{"r":"Salmos 130:7","t":"En Jehová hay misericordia, y abundante redención con él."},
{"r":"Salmos 131:3","t":"Espera, oh Israel, en Jehová, desde ahora y para siempre."},
{"r":"Salmos 133:1","t":"¡Mirad cuán bueno y cuán delicioso es habitar los hermanos juntos en armonía!"},
{"r":"Salmos 136:1","t":"Alabad á Jehová, porque él es bueno; porque para siempre es su misericordia."},
{"r":"Salmos 138:3","t":"El día que clamé, me respondiste; esforzásteme con fortaleza en mi alma."},
{"r":"Salmos 138:7","t":"Si anduviere yo en medio de la angustia, tú me vivificarás; contra la ira de mis enemigos extenderás tu mano."},
{"r":"Salmos 139:1","t":"Jehová, tú me has escudriñado y conocido."},
{"r":"Salmos 139:7","t":"¿Á dónde me iré de tu espíritu? ¿Y á dónde huiré de tu presencia?"},
{"r":"Salmos 139:14","t":"Te alabaré, porque formidables y maravillosas son tus obras; estoy maravillado, y mi alma lo sabe muy bien."},
{"r":"Salmos 139:16","t":"Mi embrión vieron tus ojos, y en tu libro estaban escritas todas aquellas cosas que luego fueron formadas."},
{"r":"Salmos 139:23","t":"Escudríñame, oh Dios, y conoce mi corazón; pruébame y conoce mis pensamientos."},
{"r":"Salmos 141:3","t":"Pon guarda á mi boca, oh Jehová; guarda la puerta de mis labios."},
{"r":"Salmos 143:8","t":"Hazme oir de mañana tu misericordia, porque en ti he confiado."},
{"r":"Salmos 143:10","t":"Enséñame á hacer tu voluntad, porque tú eres mi Dios."},
{"r":"Salmos 145:3","t":"Grande es Jehová, y digno de suprema alabanza; y su grandeza es inescrutable."},
{"r":"Salmos 145:8","t":"Clemente y misericordioso es Jehová, lento para la ira y grande en misericordia."},
{"r":"Salmos 145:9","t":"Bueno es Jehová para con todos, y sus misericordias sobre todas sus obras."},
{"r":"Salmos 145:13","t":"Tu reino es reino de todos los siglos, y tu señorío en todas las generaciones."},
{"r":"Salmos 145:14","t":"Sostiene Jehová á todos los que caen, y levanta á todos los oprimidos."},
{"r":"Salmos 145:18","t":"Cercano está Jehová á todos los que le invocan, á todos los que le invocan de veras."},
{"r":"Salmos 145:19","t":"Cumplirá el deseo de los que le temen; oirá asimismo el clamor de ellos, y los salvará."},
{"r":"Salmos 147:3","t":"El sana á los quebrantados de corazón, y venda sus heridas."},
{"r":"Salmos 147:5","t":"Grande es el Señor nuestro, y de mucho poder; y su entendimiento es infinito."},
{"r":"Salmos 148:13","t":"Alaben el nombre de Jehová; porque sólo su nombre es enaltecido: su gloria es sobre tierra y cielos."},
{"r":"Salmos 149:4","t":"Porque Jehová tiene contentamiento en su pueblo; hermoseará á los mansos con salud."},
{"r":"Salmos 150:6","t":"Todo lo que respira alabe á Jehová. Aleluya."},
{"r":"Proverbios 1:7","t":"El principio de la sabiduría es el temor de Jehová; los insensatos desprecian la sabiduría y la enseñanza."},
{"r":"Proverbios 2:6","t":"Porque Jehová da la sabiduría; y de su boca viene el conocimiento y la inteligencia."},
{"r":"Proverbios 3:1","t":"Hijo mío, no te olvides de mi ley, y tu corazón guarde mis mandamientos."},
{"r":"Proverbios 3:5","t":"Confía en Jehová con todo tu corazón, y no te apoyes en tu propia prudencia."},
{"r":"Proverbios 3:6","t":"Reconócelo en todos tus caminos, y él enderezará tus veredas."},
{"r":"Proverbios 3:7","t":"No seas sabio en tu propia opinión; teme á Jehová, y apártate del mal."},
{"r":"Proverbios 3:9","t":"Honra á Jehová con tus bienes, y con las primicias de todos tus frutos."},
{"r":"Proverbios 3:12","t":"Porque Jehová al que ama castiga, como el padre al hijo á quien quiere."},
{"r":"Proverbios 3:24","t":"Cuando te acostares, no tendrás temor; sino que te acostarás, y tu sueño será suave."},
{"r":"Proverbios 4:7","t":"Sabiduría ante todo; adquiere sabiduría; y ante toda tu adquisición adquiere inteligencia."},
{"r":"Proverbios 4:23","t":"Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida."},
{"r":"Proverbios 6:23","t":"Porque el mandamiento es lámpara, y la enseñanza es luz."},
{"r":"Proverbios 9:10","t":"El principio de la sabiduría es el temor de Jehová; y el conocimiento del Santísimo es la inteligencia."},
{"r":"Proverbios 10:12","t":"El odio despierta rencillas; pero el amor cubrirá todas las faltas."},
{"r":"Proverbios 11:2","t":"Donde hay soberbia, allí habrá también ignominia; mas con los humildes está la sabiduría."},
{"r":"Proverbios 11:14","t":"Donde no hay buen consejo, el pueblo cae; mas en la multitud de consejeros hay seguridad."},
{"r":"Proverbios 12:17","t":"El testigo verdadero dice la verdad; mas el testigo mentiroso dice mentiras."},
{"r":"Proverbios 13:20","t":"El que anda con sabios, sabio será; mas el que se junta con necios, será quebrantado."},
{"r":"Proverbios 14:12","t":"Hay camino que parece derecho al hombre, pero su fin es camino de muerte."},
{"r":"Proverbios 15:1","t":"La blanda respuesta quita la ira; mas la palabra áspera hace subir el furor."},
{"r":"Proverbios 15:3","t":"Los ojos de Jehová están en todo lugar, mirando los malos y los buenos."},
{"r":"Proverbios 16:3","t":"Encomienda á Jehová tus obras, y tus pensamientos serán afirmados."},
{"r":"Proverbios 16:9","t":"El corazón del hombre piensa su camino; mas Jehová endereza sus pasos."},
{"r":"Proverbios 16:18","t":"Antes del quebrantamiento es la soberbia, y antes de la caída la altivez de espíritu."},
{"r":"Proverbios 17:17","t":"En todo tiempo ama el amigo, y es como un hermano en tiempo de angustia."},
{"r":"Proverbios 18:10","t":"Torre fuerte es el nombre de Jehová; á ella correrá el justo, y será levantado."},
{"r":"Proverbios 19:21","t":"Muchos pensamientos hay en el corazón del hombre; mas el consejo de Jehová permanecerá."},
{"r":"Proverbios 20:7","t":"Camina en su integridad el justo; sus hijos son dichosos después de él."},
{"r":"Proverbios 21:3","t":"El hacer justicia y juicio es más acepto á Jehová que el sacrificio."},
{"r":"Proverbios 22:4","t":"Riquezas, honra y vida son la remuneración de la humildad y del temor de Jehová."},
{"r":"Proverbios 22:6","t":"Instruye al niño en su camino; y aun cuando fuere viejo no se apartará de él."},
{"r":"Proverbios 23:17","t":"No tenga tu corazón envidia de los pecadores; antes persevera en el temor de Jehová todo el día."},
{"r":"Proverbios 24:16","t":"Porque siete veces caerá el justo, y volverá á levantarse; mas los impíos caerán en el mal."},
{"r":"Proverbios 27:1","t":"No te jactes del día de mañana; porque no sabes qué dará de sí el día."},
{"r":"Proverbios 28:13","t":"El que encubre sus pecados no prosperará; mas el que los confiesa y se aparta alcanzará misericordia."},
{"r":"Proverbios 29:25","t":"El temor del hombre pondrá lazo; mas el que confía en Jehová será levantado."},
{"r":"Proverbios 30:5","t":"Toda palabra de Dios es limpia; él es escudo á los que esperan en él."},
{"r":"Proverbios 31:30","t":"Engañosa es la gracia, y vana la hermosura; la mujer que teme á Jehová, ésa será alabada."},
{"r":"Eclesiastés 3:1","t":"Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora."},
{"r":"Eclesiastés 3:11","t":"Todo lo hizo hermoso en su tiempo; y ha puesto el mundo en el corazón de ellos."},
{"r":"Eclesiastés 4:9","t":"Mejores son dos que uno; porque tienen mejor paga de su trabajo."},
{"r":"Eclesiastés 12:13","t":"El fin de todo el discurso oído es este: Teme á Dios, y guarda sus mandamientos; porque esto es el todo del hombre."},
{"r":"Cantares 2:4","t":"Me llevó á la casa del banquete, y su bandera sobre mí fué amor."},
{"r":"Cantares 8:6","t":"Ponme como un sello sobre tu corazón, como una marca sobre tu brazo; porque fuerte es como la muerte el amor."},
{"r":"Cantares 8:7","t":"Las muchas aguas no podrán apagar el amor, ni los ríos lo anegarán."},
{"r":"Isaías 1:17","t":"Aprended á hacer bien; buscad el juicio, restituid al agraviado, haced justicia al huérfano, amparad á la viuda."},
{"r":"Isaías 1:18","t":"Venid luego, dice Jehová, y estemos á cuenta: si vuestros pecados fueren como la grana, como la nieve serán emblanquecidos."},
{"r":"Isaías 6:3","t":"Santo, santo, santo, Jehová de los ejércitos; toda la tierra está llena de su gloria."},
{"r":"Isaías 7:14","t":"Por tanto el Señor mismo os dará señal: He aquí que la virgen concebirá, y parirá un hijo, y llamará su nombre Emmanuel."},
{"r":"Isaías 9:6","t":"Porque un niño nos es nacido, hijo nos es dado; y el principado sobre su hombro; y llamaráse su nombre Admirable, Consejero, Dios fuerte, Padre eterno, Príncipe de paz."},
{"r":"Isaías 12:2","t":"He aquí Dios es salvación mía; me aseguraré y no temeré; porque mi fortaleza y mi canción es Jah Jehová, y fué á mí por salvación."},
{"r":"Isaías 26:3","t":"Tú guardarás en completa paz á aquel cuyo pensamiento en ti persevera; porque en ti ha confiado."},
{"r":"Isaías 26:4","t":"Confiad en Jehová para siempre; porque en Jehová el Señor está la fortaleza de los siglos."},
{"r":"Isaías 28:16","t":"He aquí que yo he puesto en Sión por fundamento una piedra, piedra probada, angular, preciosa, de fundamento estable; el que creyere, no se apresure."},
{"r":"Isaías 30:21","t":"Entonces tus oídos oirán á tus espaldas palabra que diga: Este es el camino, andad por él."},
{"r":"Isaías 33:2","t":"Oh Jehová, ten misericordia de nosotros; á ti hemos esperado: sé tú el brazo de ellos en las mañanas, nuestra salvación también en tiempo de tribulación."},
{"r":"Isaías 40:1","t":"Consolaos, consolaos, pueblo mío, dice vuestro Dios."},
{"r":"Isaías 40:8","t":"Sécase la hierba, marchítase la flor; mas la palabra de nuestro Dios permanecerá para siempre."},
{"r":"Isaías 40:11","t":"Como pastor apacentará su rebaño; en su brazo llevará los corderos, y en su seno los llevará; pastoreará suavemente las paridas."},
{"r":"Isaías 40:28","t":"¿No has sabido, no has oído que el Dios eterno es Jehová, el cual crió los términos de la tierra? No se fatiga, ni se cansa con fatiga."},
{"r":"Isaías 40:29","t":"Él da esfuerzo al cansado, y multiplica las fuerzas al que no tiene ningunas."},
{"r":"Isaías 40:30","t":"Los mancebos se fatigan y se cansan, los jóvenes flaquean y caen."},
{"r":"Isaías 40:31","t":"Pero los que esperan á Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán."},
{"r":"Isaías 41:10","t":"No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia."},
{"r":"Isaías 41:13","t":"Porque yo Jehová soy tu Dios, quien te tiene por la diestra, y te dice: No temas, yo te ayudo."},
{"r":"Isaías 43:1","t":"Ahora, así dice Jehová, Creador tuyo, oh Jacob, y Formador tuyo, oh Israel: No temas, porque yo te redimí; te puse nombre, mío eres tú."},
{"r":"Isaías 43:2","t":"Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán."},
{"r":"Isaías 43:10","t":"Vosotros sois mis testigos, dice Jehová, y mi siervo que yo escogí."},
{"r":"Isaías 43:25","t":"Yo, yo soy el que borro tus rebeliones por amor de mí mismo, y no me acordaré de tus pecados."},
{"r":"Isaías 44:22","t":"Yo desvanecí como nube tus transgresiones, y como niebla tus pecados: vuélvete á mí, porque yo te redimí."},
{"r":"Isaías 45:22","t":"Mirad á mí, y sed salvos, todos los términos de la tierra; porque yo soy Dios, y no hay más."},
{"r":"Isaías 46:4","t":"Y hasta la vejez yo mismo, y hasta las canas os soportaré yo; yo hice, yo llevaré, yo soportaré y guardaré."},
{"r":"Isaías 49:13","t":"Cantad loores, oh cielos, y alégrate tú, tierra; y prorrumpid en alabanzas, oh montes; porque Jehová ha consolado á su pueblo."},
{"r":"Isaías 49:15","t":"¿Olvidará la mujer su niño que mamanta? Aunque éstas olvidaran, yo nunca me olvidaré de ti."},
{"r":"Isaías 49:16","t":"He aquí que en las palmas de mis manos te tengo esculpida; delante de mí están siempre tus muros."},
{"r":"Isaías 53:3","t":"Despreciado y desechado entre los hombres, varón de dolores, experimentado en quebranto."},
{"r":"Isaías 53:4","t":"Ciertamente llevó él nuestras enfermedades, y sufrió nuestros dolores."},
{"r":"Isaías 53:5","t":"Mas él herido fué por nuestras rebeliones, molido por nuestros pecados; el castigo de nuestra paz sobre él; y por su llaga fuimos nosotros curados."},
{"r":"Isaías 53:6","t":"Todos nosotros nos descarriamos como ovejas, cada cual se apartó por su camino; mas Jehová cargó en él el pecado de todos nosotros."},
{"r":"Isaías 54:10","t":"Porque los montes se moverán, y los collados temblarán; pero no se apartará de ti mi misericordia, ni el pacto de mi paz se quebrantará."},
{"r":"Isaías 55:1","t":"A todos los sedientos: Venid á las aguas; y los que no tienen dinero, venid, comprad y comed."},
{"r":"Isaías 55:6","t":"Buscad á Jehová mientras puede ser hallado, llamadle en tanto que está cercano."},
{"r":"Isaías 55:7","t":"Deje el impío su camino, y el hombre inicuo sus pensamientos, y vuélvase á Jehová, el cual tendrá de él misericordia."},
{"r":"Isaías 55:8","t":"Porque mis pensamientos no son vuestros pensamientos, ni vuestros caminos mis caminos, dijo Jehová."},
{"r":"Isaías 55:11","t":"Así será mi palabra que sale de mi boca: no volverá á mí vacía, sino que hará lo que yo quiero."},
{"r":"Isaías 57:15","t":"Porque así dijo el Alto y Sublime, el que habita la eternidad, y cuyo nombre es el Santo: Yo habito en la altura y la santidad, y también con el quebrantado y humilde de espíritu."},
{"r":"Isaías 58:6","t":"¿No es más bien el ayuno que yo escogí: desatar las ligaduras de impiedad, soltar las cargas de opresión?"},
{"r":"Isaías 60:1","t":"Levántate, resplandece; porque ha venido tu luz, y la gloria de Jehová ha nacido sobre ti."},
{"r":"Isaías 60:19","t":"No te será el sol por luz del día, ni el resplandor de la luna te alumbrará; sino que Jehová te será por luz eterna."},
{"r":"Isaías 61:1","t":"El Espíritu de Jehová el Señor es sobre mí; porque ungióme Jehová; me ha enviado á predicar buenas nuevas á los abatidos."},
{"r":"Isaías 65:24","t":"Y antes que clamen, responderé yo; mientras aún hablan, yo habré oído."},
{"r":"Isaías 66:13","t":"Como aquel á quien consuela su madre, así os consolaré yo á vosotros."},
{"r":"Jeremías 1:5","t":"Antes que te formase en el vientre te conocí, y antes que nacieses te santifiqué."},
{"r":"Jeremías 17:7","t":"Bendito el varón que confía en Jehová, y cuya confianza es Jehová."},
{"r":"Jeremías 17:8","t":"Porque será como el árbol plantado junto á las aguas, que junto á la corriente echará sus raíces."},
{"r":"Jeremías 23:23","t":"¿Soy yo Dios de cerca, dice Jehová, y no Dios de lejos?"},
{"r":"Jeremías 29:11","t":"Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis."},
{"r":"Jeremías 29:12","t":"Entonces me invocaréis, y vendréis y oraréis á mí, y yo os oiré."},
{"r":"Jeremías 29:13","t":"Y me buscaréis y me hallaréis, porque me buscaréis de todo vuestro corazón."},
{"r":"Jeremías 31:3","t":"Jehová se manifestó á mí hace ya mucho tiempo, diciendo: Con amor eterno te he amado; por tanto, te prolongué mi misericordia."},
{"r":"Jeremías 31:33","t":"Daré mi ley en su mente, y la escribiré en su corazón; y yo seré á ellos por Dios, y ellos me serán por pueblo."},
{"r":"Jeremías 31:34","t":"Y perdonaré la maldad de ellos, y no me acordaré más de su pecado."},
{"r":"Jeremías 32:17","t":"Oh Señor Jehová, he aquí que tú hiciste el cielo y la tierra con tu gran poder y con tu brazo extendido, y no hay nada que sea difícil para ti."},
{"r":"Jeremías 32:27","t":"He aquí que yo soy Jehová, Dios de toda carne; ¿habrá alguna cosa que sea difícil para mí?"},
{"r":"Jeremías 33:3","t":"Clama á mí, y yo te responderé, y te enseñaré cosas grandes y dificultosas que tú no conoces."},
{"r":"Lamentaciones 3:22","t":"Las misericordias de Jehová no se han acabado; porque no faltaron sus bondades. Nuevas son cada mañana; grande es tu fidelidad."},
{"r":"Lamentaciones 3:23","t":"Grande es tu fidelidad."},
{"r":"Lamentaciones 3:24","t":"Mi porción es Jehová, dijo mi alma; por tanto en él esperaré."},
{"r":"Lamentaciones 3:25","t":"Bueno es Jehová á los que en él esperan, al alma que le busca."},
{"r":"Lamentaciones 3:26","t":"Bueno es esperar en silencio la salvación de Jehová."},
{"r":"Lamentaciones 3:32","t":"Si bien causa tristeza, también se compadecerá según la multitud de sus misericordias."},
{"r":"Ezequiel 11:19","t":"Y les daré un corazón, y un espíritu nuevo pondré dentro de ellos."},
{"r":"Ezequiel 18:4","t":"He aquí que todas las almas son mías; como el alma del padre, así el alma del hijo es mía."},
{"r":"Ezequiel 18:32","t":"Porque no quiero la muerte del que muere, dice Jehová el Señor: convertíos pues, y viviréis."},
{"r":"Ezequiel 36:26","t":"Os daré corazón nuevo, y pondré espíritu nuevo dentro de vosotros."},
{"r":"Daniel 2:20","t":"Sea bendito el nombre de Dios, de siglos en siglos; porque suya es la sabiduría y la fortaleza."},
{"r":"Daniel 2:21","t":"Y él es el que muda los tiempos y las edades; quita reyes, y pone reyes; da la sabiduría á los sabios."},
{"r":"Daniel 3:17","t":"He aquí nuestro Dios á quien servimos puede librarnos del horno de fuego ardiendo; y de tu mano, oh rey, nos librará."},
{"r":"Daniel 6:22","t":"Mi Dios envió su ángel, el cual cerró la boca de los leones."},
{"r":"Daniel 7:14","t":"Y le fué dado señorío, y gloria, y reino; y todos los pueblos, naciones y lenguas le sirvieron."},
{"r":"Oseas 6:3","t":"Y conoceremos, y proseguiremos en conocer á Jehová: como el alba está aparejada su salida."},
{"r":"Oseas 14:4","t":"Yo sanaré su rebelión, los amaré de pura gracia; porque mi ira se apartó de ellos."},
{"r":"Joel 2:13","t":"Rasgad vuestro corazón, y no vuestros vestidos, y convertíos á Jehová vuestro Dios; porque misericordioso es y clemente."},
{"r":"Joel 2:25","t":"Y os restituiré los años que comió la oruga."},
{"r":"Joel 2:28","t":"Y después de esto, derramaré mi espíritu sobre toda carne."},
{"r":"Amós 5:14","t":"Buscad lo bueno, y no lo malo, para que viváis."},
{"r":"Amós 5:24","t":"Corra empero el juicio como las aguas, y la justicia como impetuoso arroyo."},
{"r":"Abdías 1:3","t":"La soberbia de tu corazón te ha engañado."},
{"r":"Jonás 2:2","t":"Clamé en mi angustia á Jehová, y él me oyó."},
{"r":"Jonás 2:9","t":"Mas yo con voz de alabanza te ofreceré sacrificios; pagaré lo que prometí. La salvación es de Jehová."},
{"r":"Miqueas 6:8","t":"Qué pide Jehová de ti: solamente hacer juicio, y amar misericordia, y humillarte ante tu Dios."},
{"r":"Miqueas 7:18","t":"¿Qué Dios como tú, que perdona la maldad, y olvida el pecado del remanente de su heredad?"},
{"r":"Miqueas 7:19","t":"Volverá á tener misericordia de nosotros; sepultará nuestras iniquidades, y echará en lo profundo del mar todos nuestros pecados."},
{"r":"Nahúm 1:7","t":"Bueno es Jehová, es fortaleza en el día de la angustia; y conoce á los que en él esperan."},
{"r":"Habacuc 2:4","t":"He aquí que aquel cuya alma no es recta se ensoberbece; mas el justo por su fe vivirá."},
{"r":"Habacuc 3:17","t":"Aunque la higuera no florezca, ni en las vides haya frutos, aunque falte el producto del olivo, y los labrados no den mantenimiento."},
{"r":"Habacuc 3:18","t":"Con todo, yo me alegraré en Jehová, y me gozaré en el Dios de mi salud."},
{"r":"Habacuc 3:19","t":"Jehová el Señor es mi fortaleza, el cual pondrá mis pies como de ciervas, y en mis alturas me hará andar."},
{"r":"Sofonías 3:17","t":"Jehová está en medio de ti, poderoso, él salvará; se gozará sobre ti con alegría, callará de amor, se regocijará sobre ti con cánticos."},
{"r":"Hageo 2:9","t":"La gloria de esta última casa será mayor que la de la primera, dice Jehová de los ejércitos."},
{"r":"Zacarías 4:6","t":"No con ejército, ni con fuerza, sino con mi Espíritu, ha dicho Jehová de los ejércitos."},
{"r":"Zacarías 8:8","t":"Y los traeré, y habitarán en medio de Jerusalem; y me serán por pueblo, y yo seré á ellos por Dios en verdad y en justicia."},
{"r":"Malaquías 3:6","t":"Porque yo Jehová no me mudo; por esto, hijos de Jacob, no habéis sido consumidos."},
{"r":"Malaquías 3:10","t":"Traed todos los diezmos al alfolí, y haya alimento en mi casa; y probadme ahora en esto, dice Jehová de los ejércitos, si no os abriré las ventanas de los cielos, y vaciaré sobre vosotros bendición hasta que sobreabunde."},
{"r":"Malaquías 4:2","t":"Mas á vosotros los que teméis mi nombre, nacerá el Sol de justicia, y en sus alas traerá salvación."},
{"r":"Mateo 1:21","t":"Y parirá un hijo, y llamarás su nombre JESÚS; porque él salvará á su pueblo de sus pecados."},
{"r":"Mateo 1:23","t":"He aquí, una virgen concebirá y parirá un hijo, y llamarás su nombre Emmanuel, que interpretado es: Dios con nosotros."},
{"r":"Mateo 3:17","t":"Y hubo una voz de los cielos que decía: Este es mi Hijo amado, en quien tengo contentamiento."},
{"r":"Mateo 4:4","t":"No sólo de pan vivirá el hombre, sino de toda palabra que sale de la boca de Dios."},
{"r":"Mateo 5:3","t":"Bienaventurados los pobres en espíritu; porque de ellos es el reino de los cielos."},
{"r":"Mateo 5:4","t":"Bienaventurados los que lloran; porque ellos recibirán consolación."},
{"r":"Mateo 5:5","t":"Bienaventurados los mansos; porque ellos recibirán la tierra por heredad."},
{"r":"Mateo 5:6","t":"Bienaventurados los que tienen hambre y sed de justicia; porque ellos serán hartos."},
{"r":"Mateo 5:7","t":"Bienaventurados los misericordiosos; porque ellos alcanzarán misericordia."},
{"r":"Mateo 5:8","t":"Bienaventurados los de limpio corazón; porque ellos verán á Dios."},
{"r":"Mateo 5:9","t":"Bienaventurados los pacificadores; porque ellos serán llamados hijos de Dios."},
{"r":"Mateo 5:10","t":"Bienaventurados los que padecen persecución por causa de la justicia; porque de ellos es el reino de los cielos."},
{"r":"Mateo 5:14","t":"Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder."},
{"r":"Mateo 5:16","t":"Así alumbre vuestra luz delante de los hombres, para que vean vuestras obras buenas, y glorifiquen á vuestro Padre que está en los cielos."},
{"r":"Mateo 5:44","t":"Amad á vuestros enemigos, bendecid á los que os maldicen, haced bien á los que os aborrecen."},
{"r":"Mateo 5:48","t":"Sed pues vosotros perfectos, como vuestro Padre que está en los cielos es perfecto."},
{"r":"Mateo 6:6","t":"Mas tú, cuando ores, entra en tu aposento, y cerrada tu puerta, ora á tu Padre que está en secreto."},
{"r":"Mateo 6:9","t":"Padre nuestro que estás en los cielos, santificado sea tu nombre."},
{"r":"Mateo 6:10","t":"Venga tu reino. Hágase tu voluntad, como en el cielo, así también en la tierra."},
{"r":"Mateo 6:11","t":"El pan nuestro de cada día, dánosle hoy."},
{"r":"Mateo 6:12","t":"Y perdónanos nuestras deudas, como también nosotros perdonamos á nuestros deudores."},
{"r":"Mateo 6:13","t":"Y no nos metas en tentación, mas líbranos del mal; porque tuyo es el reino, y el poder, y la gloria, por todos los siglos. Amén."},
{"r":"Mateo 6:14","t":"Porque si perdonáis á los hombres sus ofensas, os perdonará también á vosotros vuestro Padre celestial."},
{"r":"Mateo 6:25","t":"Por tanto os digo: No os afanéis por vuestra vida, qué habéis de comer ó qué habéis de beber; ni por vuestro cuerpo, qué habéis de vestir."},
{"r":"Mateo 6:26","t":"Mirad las aves del cielo, que no siembran, ni siegan, ni allegan en alfolíes; y vuestro Padre celestial las alimenta."},
{"r":"Mateo 6:33","t":"Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas."},
{"r":"Mateo 7:7","t":"Pedid, y se os dará; buscad, y hallaréis; llamad, y os será abierto."},
{"r":"Mateo 7:8","t":"Porque todo aquel que pide, recibe; y el que busca, halla; y al que llama, se le abrirá."},
{"r":"Mateo 7:12","t":"Así que todas las cosas que queráis que los hombres hagan con vosotros, así también haced vosotros con ellos."},
{"r":"Mateo 10:30","t":"Pues aun vuestros cabellos están todos contados."},
{"r":"Mateo 10:31","t":"Así que no temáis; de más valor sois vosotros que muchos pajarillos."},
{"r":"Mateo 11:28","t":"Venid á mí todos los que estáis trabajados y cargados, y yo os haré descansar."},
{"r":"Mateo 11:29","t":"Llevad mi yugo sobre vosotros, y aprended de mí, que soy manso y humilde de corazón; y hallaréis descanso para vuestras almas."},
{"r":"Mateo 11:30","t":"Porque mi yugo es fácil, y mi carga ligera."},
{"r":"Mateo 16:16","t":"Tú eres el Cristo, el Hijo del Dios viviente."},
{"r":"Mateo 16:18","t":"Sobre esta roca edificaré mi iglesia; y las puertas del infierno no prevalecerán contra ella."},
{"r":"Mateo 17:20","t":"Si tuviéreis fe como un grano de mostaza, diréis á este monte: Pásate de aquí allá, y se pasará; y nada os será imposible."},
{"r":"Mateo 18:20","t":"Porque donde están dos ó tres congregados en mi nombre, allí estoy yo en medio de ellos."},
{"r":"Mateo 19:26","t":"Para Dios todo es posible."},
{"r":"Mateo 22:37","t":"Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente."},
{"r":"Mateo 22:39","t":"Y el segundo es semejante á éste: Amarás á tu prójimo como á ti mismo."},
{"r":"Mateo 24:35","t":"El cielo y la tierra pasarán; mas mis palabras no pasarán."},
{"r":"Mateo 25:40","t":"En cuanto lo hicisteis á uno de estos mis hermanos pequeñitos, á mí lo hicisteis."},
{"r":"Mateo 28:19","t":"Id, y haced discípulos á todas las naciones, bautizándolos en el nombre del Padre, y del Hijo, y del Espíritu Santo."},
{"r":"Mateo 28:20","t":"Enseñándoles que guarden todas las cosas que os he mandado; y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo."},
{"r":"Marcos 1:15","t":"El tiempo se ha cumplido, y el reino de Dios está cerca; arrepentíos, y creed en el evangelio."},
{"r":"Marcos 4:39","t":"Y levantándose, increpó al viento, y dijo á la mar: Calla, enmudece. Y cesó el viento, y se hizo gran bonanza."},
{"r":"Marcos 5:36","t":"No temas, cree solamente."},
{"r":"Marcos 9:23","t":"Si puedes creer, al que cree todo le es posible."},
{"r":"Marcos 10:27","t":"Para Dios todas las cosas son posibles."},
{"r":"Marcos 10:45","t":"Porque el Hijo del hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos."},
{"r":"Marcos 11:22","t":"Tened fe en Dios."},
{"r":"Marcos 11:24","t":"Por tanto os digo, que todo lo que pidiereis orando, creed que lo recibiréis, y os vendrá."},
{"r":"Marcos 12:30","t":"Y amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente y con todas tus fuerzas."},
{"r":"Marcos 16:15","t":"Id por todo el mundo y predicad el evangelio á toda criatura."},
{"r":"Marcos 16:16","t":"El que creyere y fuere bautizado, será salvo."},
{"r":"Lucas 1:37","t":"Porque ninguna cosa es imposible para Dios."},
{"r":"Lucas 1:45","t":"Bienaventurada la que creyó; porque se cumplirán las cosas que le fueron dichas de parte del Señor."},
{"r":"Lucas 1:79","t":"Para dar luz á los que están sentados en tinieblas y en sombra de muerte; para encaminar nuestros pies en camino de paz."},
{"r":"Lucas 4:18","t":"El Espíritu del Señor está sobre mí, por cuanto me ha ungido para dar buenas nuevas á los pobres."},
{"r":"Lucas 6:27","t":"Mas á vosotros los que oís, digo: Amad á vuestros enemigos, haced bien á los que os aborrecen."},
{"r":"Lucas 6:35","t":"Amad á vuestros enemigos, y haced bien, y prestad, no esperando de ello nada."},
{"r":"Lucas 6:36","t":"Sed pues misericordiosos, como también vuestro Padre es misericordioso."},
{"r":"Lucas 6:38","t":"Dad, y se os dará; medida buena, apretada, remecida y rebosando darán en vuestro seno."},
{"r":"Lucas 11:13","t":"Pues si vosotros siendo malos sabéis dar buenas dádivas á vuestros hijos, ¿cuánto más vuestro Padre celestial dará el Espíritu Santo á los que le pidieren?"},
{"r":"Lucas 12:15","t":"Guardaos y apartaos de toda avaricia; porque la vida del hombre no consiste en la abundancia de las cosas que posee."},
{"r":"Lucas 15:7","t":"Os digo que así habrá mayor gozo en el cielo por un pecador que se arrepiente."},
{"r":"Lucas 15:20","t":"Y levantándose, vino á su padre. Y cuando aún estaba lejos, le vió su padre, y fué movido á misericordia, y corrió, y se echó sobre su cuello, y le besó."},
{"r":"Lucas 15:24","t":"Porque este mi hijo muerto era, y ha revivido; habíase perdido, y es hallado."},
{"r":"Lucas 18:27","t":"Lo que es imposible para los hombres, es posible para Dios."},
{"r":"Lucas 19:10","t":"Porque el Hijo del hombre vino á buscar y á salvar lo que se había perdido."},
{"r":"Lucas 21:33","t":"El cielo y la tierra pasarán, mas mis palabras no pasarán."},
{"r":"Lucas 23:34","t":"Padre, perdónalos, porque no saben lo que hacen."},
{"r":"Lucas 24:6","t":"No está aquí, sino que ha resucitado."},
{"r":"Juan 1:1","t":"En el principio era el Verbo, y el Verbo era con Dios, y el Verbo era Dios."},
{"r":"Juan 1:4","t":"En él estaba la vida, y la vida era la luz de los hombres."},
{"r":"Juan 1:5","t":"La luz en las tinieblas resplandece; y las tinieblas no la comprendieron."},
{"r":"Juan 1:12","t":"Mas á todos los que le recibieron, dióles potestad de ser hechos hijos de Dios."},
{"r":"Juan 1:14","t":"Y el Verbo fué hecho carne, y habitó entre nosotros (y vimos su gloria, gloria como del unigénito del Padre), lleno de gracia y de verdad."},
{"r":"Juan 1:16","t":"Porque de su plenitud tomamos todos, y gracia sobre gracia."},
{"r":"Juan 3:3","t":"El que no naciere de nuevo, no puede ver el reino de Dios."},
{"r":"Juan 3:16","t":"Porque de tal manera amó Dios al mundo, que ha dado á su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna."},
{"r":"Juan 3:17","t":"Porque no envió Dios á su Hijo al mundo para que condene al mundo, sino para que el mundo sea salvo por él."},
{"r":"Juan 3:36","t":"El que cree en el Hijo tiene vida eterna; pero el que es incrédulo al Hijo no verá la vida."},
{"r":"Juan 4:14","t":"Mas el que bebiere del agua que yo le daré, no tendrá sed jamás; sino que el agua que yo le daré será en él una fuente de agua que salte para vida eterna."},
{"r":"Juan 4:24","t":"Dios es Espíritu; y los que le adoran, en espíritu y en verdad es necesario que le adoren."},
{"r":"Juan 5:24","t":"El que oye mi palabra, y cree al que me envió, tiene vida eterna; y no vendrá á condenación, mas pasó de muerte á vida."},
{"r":"Juan 6:35","t":"Yo soy el pan de vida; el que á mí viene, nunca tendrá hambre; y el que en mí cree, no tendrá sed jamás."},
{"r":"Juan 6:37","t":"Todo lo que el Padre me da, vendrá á mí; y al que á mí viene, no le echaré fuera."},
{"r":"Juan 6:47","t":"De cierto, de cierto os digo: El que cree en mí, tiene vida eterna."},
{"r":"Juan 7:37","t":"Si alguno tiene sed, venga á mí y beba."},
{"r":"Juan 8:12","t":"Yo soy la luz del mundo; el que me sigue, no andará en tinieblas, sino que tendrá la luz de la vida."},
{"r":"Juan 8:31","t":"Si vosotros permaneciereis en mi palabra, seréis verdaderamente mis discípulos."},
{"r":"Juan 8:32","t":"Y conoceréis la verdad, y la verdad os hará libres."},
{"r":"Juan 8:36","t":"Si el Hijo os libertare, seréis verdaderamente libres."},
{"r":"Juan 9:5","t":"Entre tanto que estoy en el mundo, luz soy del mundo."},
{"r":"Juan 10:9","t":"Yo soy la puerta; el que por mí entrare, será salvo."},
{"r":"Juan 10:10","t":"Yo he venido para que tengan vida, y para que la tengan en abundancia."},
{"r":"Juan 10:11","t":"Yo soy el buen pastor; el buen pastor su vida da por las ovejas."},
{"r":"Juan 10:14","t":"Yo soy el buen pastor; y conozco mis ovejas, y las mías me conocen."},
{"r":"Juan 10:28","t":"Y yo les doy vida eterna; y no perecerán jamás, ni nadie las arrebatará de mi mano."},
{"r":"Juan 10:29","t":"Mi Padre que me las dió, mayor es que todos; y nadie puede arrebatar del mano de mi Padre."},
{"r":"Juan 11:25","t":"Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá."},
{"r":"Juan 11:26","t":"Y todo aquel que vive y cree en mí, no morirá eternamente."},
{"r":"Juan 13:34","t":"Un mandamiento nuevo os doy: Que os améis unos á otros: como yo os he amado, que también os améis unos á otros."},
{"r":"Juan 13:35","t":"En esto conocerán todos que sois mis discípulos, si tuviéreis amor los unos con los otros."},
{"r":"Juan 14:1","t":"No se turbe vuestro corazón: creéis en Dios, creed también en mí."},
{"r":"Juan 14:2","t":"En la casa de mi Padre muchas moradas hay; si así no fuera, yo os lo hubiera dicho; voy, pues, á preparar lugar para vosotros."},
{"r":"Juan 14:3","t":"Y si me fuere y os preparare lugar, vendré otra vez, y os tomaré á mí mismo, para que donde yo estoy, vosotros también estéis."},
{"r":"Juan 14:6","t":"Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí."},
{"r":"Juan 14:13","t":"Y todo lo que pidiereis al Padre en mi nombre, lo haré, para que el Padre sea glorificado en el Hijo."},
{"r":"Juan 14:15","t":"Si me amáis, guardad mis mandamientos."},
{"r":"Juan 14:16","t":"Y yo rogaré al Padre, y os dará otro Consolador, para que esté con vosotros para siempre."},
{"r":"Juan 14:17","t":"El Espíritu de verdad, al cual el mundo no puede recibir."},
{"r":"Juan 14:26","t":"Mas el Consolador, el Espíritu Santo, al cual el Padre enviará en mi nombre, él os enseñará todas las cosas."},
{"r":"Juan 14:27","t":"La paz os dejo, mi paz os doy; no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo."},
{"r":"Juan 15:5","t":"Yo soy la vid, vosotros los pámpanos: el que está en mí, y yo en él, éste lleva mucho fruto."},
{"r":"Juan 15:7","t":"Si permaneciereis en mí, y mis palabras permanecieren en vosotros, pedid todo lo que quisiereis, y os será hecho."},
{"r":"Juan 15:12","t":"Este es mi mandamiento: Que os améis unos á otros, como yo os he amado."},
{"r":"Juan 15:13","t":"Nadie tiene mayor amor que éste, que ponga alguno su vida por sus amigos."},
{"r":"Juan 15:16","t":"No me elegisteis vosotros á mí, sino yo os elegí á vosotros."},
{"r":"Juan 16:13","t":"Pero cuando viniere el Espíritu de verdad, él os guiará á toda verdad."},
{"r":"Juan 16:33","t":"En el mundo tendréis aflicción; pero confiad, yo he vencido al mundo."},
{"r":"Juan 17:3","t":"Y esta es la vida eterna: que te conozcan á ti, el solo Dios verdadero, y á Jesucristo, al cual has enviado."},
{"r":"Juan 17:17","t":"Santifícalos en tu verdad: tu palabra es verdad."},
{"r":"Juan 20:21","t":"Paz á vosotros; como me envió el Padre, así también yo os envío."},
{"r":"Juan 20:31","t":"Mas estas cosas son escritas para que creáis que Jesús es el Cristo, el Hijo de Dios; y para que creyendo, tengáis vida en su nombre."},
{"r":"Hechos 1:8","t":"Mas recibiréis la virtud del Espíritu Santo que vendrá sobre vosotros; y me seréis testigos."},
{"r":"Hechos 2:21","t":"Todo aquel que invocare el nombre del Señor, será salvo."},
{"r":"Hechos 2:38","t":"Arrepentíos, y bautícese cada uno de vosotros en el nombre de Jesucristo para remisión de los pecados."},
{"r":"Hechos 3:19","t":"Arrepentíos y convertíos, para que sean borrados vuestros pecados."},
{"r":"Hechos 4:12","t":"Y en ningún otro hay salvación; porque no hay otro nombre debajo del cielo, dado á los hombres, en que podamos ser salvos."},
{"r":"Hechos 5:29","t":"Es necesario obedecer á Dios antes que á los hombres."},
{"r":"Hechos 13:38","t":"Sabed pues esto, varones hermanos: Que por éste os es anunciado remisión de pecados."},
{"r":"Hechos 16:31","t":"Cree en el Señor Jesucristo, y serás salvo tú y tu casa."},
{"r":"Hechos 17:27","t":"Para que busquen á Dios, si en alguna manera, palpando, puedan hallarle, aunque ciertamente no está lejos de cada uno de nosotros."},
{"r":"Hechos 17:28","t":"Porque en él vivimos, y nos movemos, y somos."},
{"r":"Romanos 1:16","t":"Porque no me avergüenzo del evangelio de Cristo; porque es potencia de Dios para salvación á todo aquel que creyere."},
{"r":"Romanos 1:17","t":"El justo por la fe vivirá."},
{"r":"Romanos 2:4","t":"¿O menosprecias las riquezas de su benignidad, paciencia y longanimidad, ignorando que su benignidad te guía al arrepentimiento?"},
{"r":"Romanos 3:23","t":"Por cuanto todos pecaron, y están destituídos de la gloria de Dios."},
{"r":"Romanos 3:24","t":"Siendo justificados gratuitamente por su gracia, por la redención que es en Cristo Jesús."},
{"r":"Romanos 5:1","t":"Justificados pues por la fe, tenemos paz para con Dios por medio del Señor nuestro Jesucristo."},
{"r":"Romanos 5:5","t":"Y la esperanza no avergüenza; porque el amor de Dios está derramado en nuestros corazones por el Espíritu Santo que nos fué dado."},
{"r":"Romanos 5:8","t":"Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros."},
{"r":"Romanos 5:20","t":"Mas donde el pecado abundó, sobreabundó la gracia."},
{"r":"Romanos 6:23","t":"Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro."},
{"r":"Romanos 7:24","t":"¡Miserable hombre de mí! ¿Quién me librará de este cuerpo de muerte?"},
{"r":"Romanos 7:25","t":"Gracias doy á Dios, por Jesucristo Señor nuestro."},
{"r":"Romanos 8:1","t":"Ahora pues, ninguna condenación hay para los que están en Cristo Jesús."},
{"r":"Romanos 8:6","t":"Porque el ocuparse del espíritu es vida y paz."},
{"r":"Romanos 8:11","t":"Y si el Espíritu de aquel que levantó de los muertos á Jesús mora en vosotros, el que levantó de los muertos á Cristo Jesús vivificará también vuestros cuerpos mortales."},
{"r":"Romanos 8:14","t":"Porque todos los que son guiados por el Espíritu de Dios, éstos son hijos de Dios."},
{"r":"Romanos 8:18","t":"Pues tengo por cierto que las aflicciones del tiempo presente no son comparables con la gloria venidera que en nosotros ha de manifestarse."},
{"r":"Romanos 8:24","t":"Porque en esperanza fuimos salvos; pero la esperanza que se ve, no es esperanza."},
{"r":"Romanos 8:26","t":"Y de la misma manera el Espíritu nos ayuda en nuestra debilidad; pues qué hemos de pedir como conviene, no lo sabemos, pero el Espíritu mismo intercede por nosotros."},
{"r":"Romanos 8:28","t":"Y sabemos que á los que aman á Dios, todas las cosas les ayudan á bien."},
{"r":"Romanos 8:31","t":"¿Qué pues diremos á esto? Si Dios por nosotros, ¿quién contra nosotros?"},
{"r":"Romanos 8:32","t":"El que aun á su propio Hijo no perdonó, sino que le entregó por todos nosotros, ¿cómo no nos dará también con él todas las cosas?"},
{"r":"Romanos 8:35","t":"¿Quién nos separará del amor de Cristo?"},
{"r":"Romanos 8:37","t":"Antes en todas estas cosas somos más que vencedores por medio de aquel que nos amó."},
{"r":"Romanos 8:38","t":"Por lo cual estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir, ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios."},
{"r":"Romanos 8:39","t":"Ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios, que es en Cristo Jesús Señor nuestro."},
{"r":"Romanos 10:9","t":"Que si confesares con tu boca que Jesús es el Señor, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo."},
{"r":"Romanos 10:10","t":"Porque con el corazón se cree para justicia, pero con la boca se hace confesión para salvación."},
{"r":"Romanos 10:13","t":"Porque todo aquel que invocare el nombre del Señor, será salvo."},
{"r":"Romanos 10:17","t":"Así que la fe es por el oír, y el oír, por la palabra de Dios."},
{"r":"Romanos 12:1","t":"Así que, hermanos, os ruego por las misericordias de Dios, que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable á Dios, que es vuestro culto racional."},
{"r":"Romanos 12:2","t":"No os conforméis á este siglo; sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta."},
{"r":"Romanos 12:9","t":"El amor sea sin fingimiento. Aborreced lo malo, seguid lo bueno."},
{"r":"Romanos 12:10","t":"Amaos los unos á los otros con amor fraternal; en cuanto á honra, prefiriéndoos los unos á los otros."},
{"r":"Romanos 12:12","t":"Gozosos en la esperanza; pacientes en la tribulación; constantes en la oración."},
{"r":"Romanos 12:21","t":"No seas vencido de lo malo, sino vence con el bien el mal."},
{"r":"Romanos 13:8","t":"No debáis á nadie nada, sino el amaros unos á otros."},
{"r":"Romanos 15:4","t":"Porque las cosas que se escribieron antes, para nuestra enseñanza se escribieron; para que por la paciencia y la consolación de las Escrituras, tengamos esperanza."},
{"r":"Romanos 15:13","t":"Y el Dios de esperanza os llene de todo gozo y paz en el creer, para que abundéis en esperanza por la virtud del Espíritu Santo."},
{"r":"1 Corintios 1:18","t":"Porque la palabra de la cruz es locura á los que se pierden; mas á los que se salvan, esto es, á nosotros, es potencia de Dios."},
{"r":"1 Corintios 2:9","t":"Antes bien, como está escrito: Cosas que ojo no vió, ni oído oyó, ni han subido en corazón de hombre, son las que Dios ha preparado para los que le aman."},
{"r":"1 Corintios 6:19","t":"¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros?"},
{"r":"1 Corintios 6:20","t":"Pues habéis sido comprados por precio: glorificad pues á Dios en vuestro cuerpo y en vuestro espíritu."},
{"r":"1 Corintios 10:13","t":"No os ha tomado tentación, sino humana; mas fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida."},
{"r":"1 Corintios 10:31","t":"Si pues coméis ó bebéis, ó hacéis otra cosa, hacedlo todo á la gloria de Dios."},
{"r":"1 Corintios 13:1","t":"Si yo hablase lenguas humanas y angélicas, y no tengo amor, vengo á ser como metal que resuena, ó címbalo que retiñe."},
{"r":"1 Corintios 13:4","t":"El amor es sufrido, es benigno; el amor no tiene envidia; el amor no es jactancioso, no se ensoberbece."},
{"r":"1 Corintios 13:5","t":"No hace nada indecoroso, no busca lo suyo, no se irrita, no guarda rencor."},
{"r":"1 Corintios 13:6","t":"No se goza de la injusticia, mas se goza de la verdad."},
{"r":"1 Corintios 13:7","t":"Todo lo sufre, todo lo cree, todo lo espera, todo lo soporta."},
{"r":"1 Corintios 13:8","t":"El amor nunca deja de ser."},
{"r":"1 Corintios 13:13","t":"Y ahora permanecen la fe, la esperanza, el amor, estos tres; pero el mayor de ellos es el amor."},
{"r":"1 Corintios 15:22","t":"Porque así como en Adán todos mueren, también en Cristo todos serán vivificados."},
{"r":"1 Corintios 15:55","t":"¿Dónde está, oh muerte, tu aguijón? ¿Dónde, oh sepulcro, tu victoria?"},
{"r":"1 Corintios 15:57","t":"Mas gracias sean dadas á Dios, que nos da la victoria por medio del Señor nuestro Jesucristo."},
{"r":"1 Corintios 15:58","t":"Así que, hermanos míos amados, estad firmes y constantes, creciendo en la obra del Señor siempre."},
{"r":"1 Corintios 16:13","t":"Velad, estad firmes en la fe; portaos varonilmente, y esforzaos."},
{"r":"2 Corintios 1:3","t":"Bendito sea el Dios y Padre de nuestro Señor Jesucristo, Padre de misericordias y Dios de toda consolación."},
{"r":"2 Corintios 1:4","t":"El cual nos consuela en toda nuestra tribulación, para que podamos también nosotros consolar á los que están en cualquier tribulación."},
{"r":"2 Corintios 4:8","t":"En todo somos atribulados, mas no angustiados; en apuros, mas no desesperados."},
{"r":"2 Corintios 4:16","t":"Por tanto no desmayamos; antes aunque este nuestro hombre exterior se va corrompiendo, el interior no obstante se renueva de día en día."},
{"r":"2 Corintios 4:17","t":"Porque esta leve tribulación momentánea produce en nosotros un cada vez más excelente y eterno peso de gloria."},
{"r":"2 Corintios 5:7","t":"Porque por fe andamos, no por vista."},
{"r":"2 Corintios 5:17","t":"De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas."},
{"r":"2 Corintios 5:21","t":"Al que no conoció pecado, por nosotros le hizo pecado, para que nosotros fuésemos hechos justicia de Dios en él."},
{"r":"2 Corintios 6:2","t":"He aquí ahora el tiempo aceptable; he aquí ahora el día de salvación."},
{"r":"2 Corintios 9:8","t":"Y poderoso es Dios para hacer que abunde en vosotros toda gracia, á fin de que teniendo siempre en todas las cosas todo lo necesario, abundéis para toda buena obra."},
{"r":"2 Corintios 12:9","t":"Bástate mi gracia; porque mi potencia en la flaqueza se perfecciona."},
{"r":"2 Corintios 12:10","t":"Por lo cual me gozo en las flaquezas, en afrentas, en necesidades, en persecuciones, en angustias por amor á Cristo; porque cuando soy flaco, entonces soy poderoso."},
{"r":"Gálatas 2:20","t":"Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí."},
{"r":"Gálatas 3:13","t":"Cristo nos redimió de la maldición de la ley."},
{"r":"Gálatas 5:1","t":"Estad pues firmes en la libertad con que Cristo nos hizo libres, y no estéis otra vez sujetos al yugo de servidumbre."},
{"r":"Gálatas 5:13","t":"Mas servíos los unos á los otros por amor."},
{"r":"Gálatas 5:22","t":"Mas el fruto del Espíritu es: amor, gozo, paz, paciencia, benignidad, bondad, fe."},
{"r":"Gálatas 5:23","t":"Mansedumbre, templanza: contra tales cosas no hay ley."},
{"r":"Gálatas 6:2","t":"Sobrellevad los unos las cargas de los otros, y cumplid así la ley de Cristo."},
{"r":"Gálatas 6:9","t":"Y no nos cansemos de hacer bien; porque á su tiempo segaremos, si no desmayáremos."},
{"r":"Efesios 1:4","t":"Según nos escogió en él antes de la fundación del mundo, para que fuésemos santos y sin mancha delante de él."},
{"r":"Efesios 1:7","t":"En quien tenemos redención por su sangre, el perdón de los pecados según las riquezas de su gracia."},
{"r":"Efesios 2:4","t":"Pero Dios, que es rico en misericordia, por su grande amor con que nos amó."},
{"r":"Efesios 2:8","t":"Porque por gracia sois salvos por la fe; y esto no de vosotros, pues es don de Dios."},
{"r":"Efesios 2:9","t":"No por obras, para que nadie se gloríe."},
{"r":"Efesios 2:10","t":"Porque somos hechura suya, criados en Cristo Jesús para buenas obras."},
{"r":"Efesios 3:16","t":"Para que os dé, conforme á las riquezas de su gloria, el ser fortalecidos con poder en el hombre interior por su Espíritu."},
{"r":"Efesios 3:17","t":"Para que habite Cristo por la fe en vuestros corazones; á fin de que, arraigados y cimentados en amor."},
{"r":"Efesios 3:20","t":"Y á aquel que es poderoso para hacer todas las cosas mucho más abundantemente de lo que pedimos ó entendemos, según el poder que actúa en nosotros."},
{"r":"Efesios 4:2","t":"Con toda humildad y mansedumbre, soportándoos los unos á los otros en amor."},
{"r":"Efesios 4:24","t":"Vestíos del nuevo hombre, creado según Dios en la justicia y santidad de la verdad."},
{"r":"Efesios 4:32","t":"Sed pues benignos unos con otros, misericordiosos, perdonándoos unos á otros, como también Dios os perdonó á vosotros en Cristo."},
{"r":"Efesios 5:2","t":"Y andad en amor, como también Cristo nos amó, y se entregó á sí mismo por nosotros."},
{"r":"Efesios 5:20","t":"Dando siempre gracias por todo al Dios y Padre, en el nombre de nuestro Señor Jesucristo."},
{"r":"Efesios 6:10","t":"Por lo demás, hermanos míos, fortaleceos en el Señor, y en el poder de su fuerza."},
{"r":"Efesios 6:11","t":"Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo."},
{"r":"Efesios 6:18","t":"Orando en todo tiempo con toda oración y súplica en el Espíritu."},
{"r":"Filipenses 1:6","t":"Estando confiado en esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo."},
{"r":"Filipenses 1:21","t":"Porque para mí el vivir es Cristo, y el morir es ganancia."},
{"r":"Filipenses 2:3","t":"No hagáis nada por contienda ó por vanagloria; sino con humildad, estimando cada uno á los otros como superiores á él mismo."},
{"r":"Filipenses 2:5","t":"Haya pues en vosotros este sentir que hubo también en Cristo Jesús."},
{"r":"Filipenses 2:10","t":"Para que en el nombre de Jesús se doble toda rodilla de los que están en los cielos, y en la tierra, y debajo de la tierra."},
{"r":"Filipenses 2:13","t":"Porque Dios es el que en vosotros obra así el querer como el hacer, por su buena voluntad."},
{"r":"Filipenses 3:14","t":"Prosigo al blanco, al premio de la soberana vocación de Dios en Cristo Jesús."},
{"r":"Filipenses 4:4","t":"Alegraos en el Señor siempre; otra vez digo, que os alegréis."},
{"r":"Filipenses 4:6","t":"Por nada estéis afanosos; sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con hacimiento de gracias."},
{"r":"Filipenses 4:7","t":"Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús."},
{"r":"Filipenses 4:8","t":"Todo lo que es verdadero, todo lo honesto, todo lo justo, todo lo puro, todo lo amable, todo lo que es de buen nombre; en esto pensad."},
{"r":"Filipenses 4:11","t":"He aprendido á contentarme, cualquiera que sea mi estado."},
{"r":"Filipenses 4:13","t":"Todo lo puedo en Cristo que me fortalece."},
{"r":"Filipenses 4:19","t":"Mi Dios pues suplirá todo lo que os falta conforme á sus riquezas en gloria en Cristo Jesús."},
{"r":"Colosenses 1:13","t":"El cual nos ha librado de la potestad de las tinieblas, y trasladado al reino de su amado Hijo."},
{"r":"Colosenses 1:14","t":"En quien tenemos redención por su sangre, el perdón de los pecados."},
{"r":"Colosenses 1:17","t":"Y él es antes de todas las cosas, y por él todas las cosas subsisten."},
{"r":"Colosenses 2:6","t":"Por tanto, de la manera que recibisteis al Señor Jesucristo, andad en él."},
{"r":"Colosenses 3:2","t":"Poned la mira en las cosas de arriba, no en las de la tierra."},
{"r":"Colosenses 3:13","t":"Soportándoos los unos á los otros, y perdonándoos los unos á los otros si alguno tuviere queja de otro. De la manera que Cristo os perdonó, así también hacedlo vosotros."},
{"r":"Colosenses 3:15","t":"Y la paz de Dios gobierne en vuestros corazones, á la que asimismo fuisteis llamados en un cuerpo; y sed agradecidos."},
{"r":"Colosenses 3:16","t":"La palabra de Cristo more en abundancia en vosotros."},
{"r":"Colosenses 3:17","t":"Y todo lo que hacéis, sea de palabra ó de obra, hacedlo todo en el nombre del Señor Jesús."},
{"r":"1 Tesalonicenses 4:7","t":"Pues no nos ha llamado Dios á inmundicia, sino á santificación."},
{"r":"1 Tesalonicenses 5:16","t":"Estad siempre gozosos."},
{"r":"1 Tesalonicenses 5:17","t":"Orad sin cesar."},
{"r":"1 Tesalonicenses 5:18","t":"Dad gracias en todo; porque esta es la voluntad de Dios para con vosotros en Cristo Jesús."},
{"r":"1 Tesalonicenses 5:23","t":"Y el mismo Dios de paz os santifique en todo; y todo vuestro espíritu y alma y cuerpo sea guardado sin reprensión para la venida de nuestro Señor Jesucristo."},
{"r":"2 Tesalonicenses 1:11","t":"Por lo cual asimismo oramos siempre por vosotros, para que nuestro Dios os tenga por dignos de su vocación."},
{"r":"2 Tesalonicenses 3:3","t":"Mas fiel es el Señor, que os afirmará y guardará del mal."},
{"r":"1 Timoteo 2:1","t":"Exhorto pues, ante todo, que se hagan rogativas, oraciones, intersesiones y gracias por todos los hombres."},
{"r":"1 Timoteo 2:5","t":"Porque hay un solo Dios, y un solo mediador entre Dios y los hombres, Jesucristo hombre."},
{"r":"1 Timoteo 6:6","t":"Pero gran ganancia es la piedad con contentamiento."},
{"r":"1 Timoteo 6:12","t":"Pelea la buena batalla de la fe, echa mano de la vida eterna."},
{"r":"2 Timoteo 1:7","t":"Porque no nos ha dado Dios el espíritu de cobardía, sino de poder, de amor y de templanza."},
{"r":"2 Timoteo 2:13","t":"Si fuéremos infieles, él permanece fiel; porque no puede negarse á sí mismo."},
{"r":"2 Timoteo 3:16","t":"Toda la Escritura es inspirada divinamente y útil para enseñar, para redargüir, para corregir, para instruir en justicia."},
{"r":"2 Timoteo 4:7","t":"He peleado la buena batalla, he acabado la carrera, he guardado la fe."},
{"r":"2 Timoteo 4:8","t":"Por lo demás, me está guardada la corona de justicia."},
{"r":"Tito 2:11","t":"Porque la gracia de Dios que trae salvación se ha manifestado á todos los hombres."},
{"r":"Tito 3:5","t":"Nos salvó, no por obras de justicia que nosotros hubiésemos hecho, sino por su misericordia, por el lavamiento de la regeneración."},
{"r":"Filemón 1:6","t":"Para que la comunicación de tu fe sea eficaz en el conocimiento de todo el bien que está en vosotros para con Cristo Jesús."},
{"r":"Hebreos 1:3","t":"El cual, siendo el resplandor de su gloria, y la misma imagen de su sustancia, y quien sustenta todas las cosas con la palabra de su potencia."},
{"r":"Hebreos 4:12","t":"Porque la palabra de Dios es viva y eficaz, y más penetrante que toda espada de dos filos."},
{"r":"Hebreos 4:15","t":"Porque no tenemos un pontífice que no pueda compadecerse de nuestras flaquezas; sino uno tentado en todo según nuestra semejanza, pero sin pecado."},
{"r":"Hebreos 4:16","t":"Lleguémonos pues confiadamente al trono de la gracia, para que alcancemos misericordia, y hallemos gracia para el oportuno socorro."},
{"r":"Hebreos 10:23","t":"Mantengamos firme la profesión de nuestra esperanza sin fluctuar, porque fiel es el que prometió."},
{"r":"Hebreos 11:1","t":"Es pues la fe la certeza de lo que se espera, la demostración de lo que no se ve."},
{"r":"Hebreos 11:3","t":"Por la fe entendemos haber sido compuesto el universo por la palabra de Dios."},
{"r":"Hebreos 11:6","t":"Pero sin fe es imposible agradar á Dios; porque es necesario que el que se allega á Dios, crea que le hay."},
{"r":"Hebreos 12:1","t":"Por tanto, nosotros también, teniendo en derredor nuestro tan grande nube de testigos, despojémonos de todo peso, y del pecado que nos cerca, y corramos con paciencia la carrera que tenemos por delante."},
{"r":"Hebreos 12:2","t":"Puestos los ojos en Jesús, el autor y consumador de la fe, el cual por el gozo puesto delante de él, sufrió la cruz."},
{"r":"Hebreos 12:6","t":"Porque el Señor al que ama, disciplina; y azota á cualquiera que recibe por hijo."},
{"r":"Hebreos 12:14","t":"Seguid la paz con todos, y la santidad, sin la cual nadie verá al Señor."},
{"r":"Hebreos 13:5","t":"No te desampararé, ni te dejaré."},
{"r":"Hebreos 13:6","t":"Así que podemos decir confiadamente: El Señor es mi ayudador; no temeré lo que me haga el hombre."},
{"r":"Hebreos 13:8","t":"Jesucristo es el mismo ayer, y hoy, y por los siglos."},
{"r":"Santiago 1:2","t":"Hermanos míos, tened por sumo gozo cuando cayereis en diversas tentaciones."},
{"r":"Santiago 1:5","t":"Y si alguno de vosotros tiene falta de sabiduría, demándela á Dios, el cual da á todos abundantemente y sin reproche; y le será dada."},
{"r":"Santiago 1:12","t":"Bienaventurado el varón que soporta la prueba; porque cuando fuere probado, recibirá la corona de vida."},
{"r":"Santiago 1:17","t":"Toda buena dádiva y todo don perfecto desciende de lo alto, del Padre de las luces."},
{"r":"Santiago 2:17","t":"Así también la fe, si no tuviere obras, es muerta en sí misma."},
{"r":"Santiago 4:7","t":"Resistid al diablo, y huirá de vosotros."},
{"r":"Santiago 4:8","t":"Allegaos á Dios, y él se allegará á vosotros."},
{"r":"Santiago 4:10","t":"Humillaos delante del Señor, y él os ensalzará."},
{"r":"Santiago 5:16","t":"Confesaos vuestras ofensas los unos á los otros, y orad los unos por los otros, para que seáis sanados. La oración eficaz del justo puede mucho."},
{"r":"1 Pedro 1:3","t":"Bendito el Dios y Padre de nuestro Señor Jesucristo, que según su grande misericordia nos regeneró para una esperanza viva, por la resurrección de Jesucristo de los muertos."},
{"r":"1 Pedro 1:15","t":"Mas como aquel que os llamó es santo, sed también vosotros santos en toda vuestra manera de vivir."},
{"r":"1 Pedro 1:18","t":"Sabiendo que fuisteis rescatados de vuestra vana manera de vivir, la cual recibisteis de vuestros padres, no con cosas corruptibles."},
{"r":"1 Pedro 1:19","t":"Sino con la sangre preciosa de Cristo, como de un cordero sin defecto y sin contaminación."},
{"r":"1 Pedro 2:9","t":"Mas vosotros sois linaje escogido, real sacerdocio, gente santa, pueblo adquirido."},
{"r":"1 Pedro 2:24","t":"Quien llevó él mismo nuestros pecados en su cuerpo sobre el madero, para que nosotros, muertos á los pecados, vivamos á la justicia."},
{"r":"1 Pedro 3:15","t":"Santificad al Señor Dios en vuestros corazones, y estad siempre aparejados para responder con mansedumbre y reverencia á cada uno que os demande razón de la esperanza que hay en vosotros."},
{"r":"1 Pedro 4:8","t":"Y ante todo, tened entre vosotros fervorosa caridad; porque la caridad cubrirá multitud de pecados."},
{"r":"1 Pedro 5:6","t":"Humillaos pues bajo la poderosa mano de Dios, para que él os ensalce cuando fuere tiempo."},
{"r":"1 Pedro 5:7","t":"Echando toda vuestra solicitud en él, porque él tiene cuidado de vosotros."},
{"r":"1 Pedro 5:8","t":"Sed sobrios, y velad; porque vuestro adversario el diablo, como león rugiente, anda alrededor buscando á quien devorar."},
{"r":"1 Pedro 5:10","t":"Mas el Dios de toda gracia, que nos llamó á su gloria eterna en Cristo Jesús, después que hayáis padecido un poco de tiempo, él mismo os perfeccione, confirme, corrobore y establezca."},
{"r":"2 Pedro 1:3","t":"Como su divina potencia nos ha dado todas las cosas que pertenecen á la vida y á la piedad."},
{"r":"2 Pedro 1:4","t":"Por las cuales nos ha dado preciosas y grandísimas promesas, para que por ellas fueseis hechos participantes de la naturaleza divina."},
{"r":"2 Pedro 3:9","t":"El Señor no retarda su promesa, según algunos la tienen por tardanza; sino que es paciente para con nosotros, no queriendo que ninguno perezca, sino que todos procedan al arrepentimiento."},
{"r":"1 Juan 1:7","t":"Pero si andamos en luz, como él está en luz, tenemos comunión unos con otros, y la sangre de Jesucristo su Hijo nos limpia de todo pecado."},
{"r":"1 Juan 1:9","t":"Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad."},
{"r":"1 Juan 3:1","t":"Mirad cuál amor nos ha dado el Padre, que seamos llamados hijos de Dios."},
{"r":"1 Juan 3:16","t":"En esto hemos conocido el amor, en que él puso su vida por nosotros."},
{"r":"1 Juan 4:4","t":"Hijitos, vosotros sois de Dios, y los habéis vencido; porque mayor es el que está en vosotros, que el que está en el mundo."},
{"r":"1 Juan 4:7","t":"Amados, amémonos unos á otros; porque el amor es de Dios. Todo aquel que ama, es nacido de Dios, y conoce á Dios."},
{"r":"1 Juan 4:8","t":"El que no ama, no conoce á Dios; porque Dios es amor."},
{"r":"1 Juan 4:10","t":"En esto consiste el amor: no en que nosotros hayamos amado á Dios, sino en que él nos amó á nosotros, y ha enviado á su Hijo en propiciación por nuestros pecados."},
{"r":"1 Juan 4:16","t":"Y nosotros hemos conocido y creído el amor que Dios tiene para con nosotros. Dios es amor; y el que está en amor, está en Dios, y Dios en él."},
{"r":"1 Juan 4:18","t":"El perfecto amor echa fuera el temor."},
{"r":"1 Juan 4:19","t":"Nosotros le amamos á él, porque él nos amó primero."},
{"r":"1 Juan 5:4","t":"Porque todo lo que es nacido de Dios vence al mundo; y esta es la victoria que ha vencido al mundo, nuestra fe."},
{"r":"1 Juan 5:11","t":"Y este es el testimonio: que Dios nos ha dado vida eterna; y esta vida está en su Hijo."},
{"r":"1 Juan 5:14","t":"Y esta es la confianza que tenemos en él, que si demandamos alguna cosa conforme á su voluntad, él nos oye."},
{"r":"2 Juan 1:6","t":"Y este es el amor: que andemos según sus mandamientos. Este es el mandamiento: que andéis en amor, como vosotros habéis oído desde el principio."},
{"r":"3 Juan 1:2","t":"Amado, yo deseo que tú seas prosperado en todas las cosas, y que tengas salud, así como prospera tu alma."},
{"r":"3 Juan 1:4","t":"No tengo yo mayor gozo que este, que oiga que mis hijos andan en la verdad."},
{"r":"Judas 1:20","t":"Mas vosotros, amados, edificándoos en vuestra santísima fe, orando en el Espíritu Santo."},
{"r":"Judas 1:21","t":"Conservaos en el amor de Dios, esperando la misericordia de nuestro Señor Jesucristo para vida eterna."},
{"r":"Apocalipsis 1:8","t":"Yo soy el Alpha y la Omega, principio y fin, dice el Señor, el que es y el que era y el que ha de venir, el Todopoderoso."},
{"r":"Apocalipsis 1:18","t":"Y el que vivo, y estuve muerto; y he aquí que vivo por los siglos de los siglos, amén. Y tengo las llaves de la muerte y del Hades."},
{"r":"Apocalipsis 2:10","t":"Sé fiel hasta la muerte, y yo te daré la corona de la vida."},
{"r":"Apocalipsis 3:20","t":"He aquí, yo estoy á la puerta y llamo; si alguno oyere mi voz y abriere la puerta, entraré á él."},
{"r":"Apocalipsis 4:11","t":"Digno eres, Señor, de recibir la gloria y la honra y el poder; porque tú criaste todas las cosas, y por tu voluntad tienen ser y fueron criadas."},
{"r":"Apocalipsis 5:12","t":"El Cordero que fué inmolado es digno de tomar el poder y las riquezas y la sabiduría y la fortaleza y la honra y la gloria y la alabanza."},
{"r":"Apocalipsis 7:17","t":"Porque el Cordero que está en medio del trono los pastoreará, y los guiará á fuentes de aguas de vida; y Dios limpiará toda lágrima de los ojos de ellos."},
{"r":"Apocalipsis 11:15","t":"Los reinos del mundo han venido á ser de nuestro Señor y de su Cristo; y él reinará por los siglos de los siglos."},
{"r":"Apocalipsis 19:6","t":"Aleluya; porque el Señor nuestro Dios Todopoderoso reina."},
{"r":"Apocalipsis 21:3","t":"He aquí el tabernáculo de Dios con los hombres, y él morará con ellos; y ellos serán su pueblo, y el mismo Dios será su Dios con ellos."},
{"r":"Apocalipsis 21:4","t":"Enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte, ni habrá más lloro, ni clamor, ni dolor; porque las primeras cosas son pasadas."},
{"r":"Apocalipsis 21:5","t":"Y el que estaba sentado en el trono dijo: He aquí, yo hago nuevas todas las cosas."},
{"r":"Apocalipsis 22:13","t":"Yo soy el Alpha y la Omega, el principio y el fin, el primero y el último."},
{"r":"Apocalipsis 22:17","t":"El Espíritu y la Esposa dicen: Ven. Y el que oye, diga: Ven. Y el que tiene sed, venga; y el que quiere, tome del agua de la vida de balde."},
{"r":"Apocalipsis 22:20","t":"El que da testimonio de estas cosas dice: Sí, vengo presto. Amén."},
]

v_todos = [f"{v['r']} - {v['t']}" for v in versos]

res = {c: [] for c in categorias}

for v in versos:
    txt = v["t"].lower()
    ref = f"{v['r']} - {v['t']}"
    for c in categorias:
        if any(k in txt for k in kw.get(c, [])):
            res[c].append(ref)

for c in categorias:
    res[c] = list(dict.fromkeys(res[c]))
    if len(res[c]) < 33:
        faltan = 33 - len(res[c])
        otros = [v for v in v_todos if v not in res[c]]
        res[c].extend(otros[:faltan])

out = {"categorias": categorias, "versiculos": res, "total": len(versos)}
with open("artifacts/versiculos/public/bible_categories.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, separators=(",",":"))

print(f"OK: {len(versos)} versículos, {len(categorias)} categorías")
for c in categorias:
    print(f"  {c}: {len(res[c])}")
